var PAGE_EVENT={EVENT_LIST:[],fireEvent:function(event,arg){var result=[],_arg=QZFL.lang.arg2arr(arguments).slice(1),found=false;for(var i=0;i<this.EVENT_LIST.length;i++){var ev=this.EVENT_LIST[i];if(ev["event"]==event&&ev["handler"]){result.push(ev["handler"].apply(this,_arg));this.EVENT_LIST[i].fired=true;this.EVENT_LIST[i].args=_arg;found=true}}if(!found)this.EVENT_LIST.push({"handler":null,"event":event,"fired":true,"args":_arg});if(!result.length)return null;return result},addEvent:function(ev,
handler){if(ev==""||!handler)throw"event params error";this.EVENT_LIST.push({"handler":handler,"event":ev});return this},triggerEvent:function(event,handler){for(var i=0;i<this.EVENT_LIST.length;i++){var ev=this.EVENT_LIST[i];if(ev["event"]==event&&ev.fired==true){handler.apply(this,ev.args);return-1}}return this.addEvent(event,handler)},removeEvent:function(ev,handler){for(var i=0;i<this.EVENT_LIST.length;i++)if(this.EVENT_LIST[i]&&this.EVENT_LIST[i]["event"]==ev){var hdl=this.EVENT_LIST[i]["handler"];
if(!handler)this.EVENT_LIST[i]=null;else if(handler==hdl)this.EVENT_LIST[i]=null}}};
var PAGE_ROUTER={_historyList:[],get:function(key,defVal){var _oriHash=location.hash;var r=new RegExp("(#|&)"+key+"=([^&#]*)(&|#|$)");var m=_oriHash.match(r);return m?m[2]:defVal},getAll:function(){var args=new Object;var query=location.hash.substring(1);var pairs=query.split("&");for(var i=0;i<pairs.length;i++){var pos=pairs[i].indexOf("=");if(pos==-1)continue;var argname=pairs[i].substring(0,pos);var value=pairs[i].substring(pos+1);args[argname]=value}return args},set:function(args1,args2){var _oriHash=
location.hash;var params={};if(typeof args1!="object")params[args1]=args2;else params=args1;for(var key in params){var val=params[key];if(val===null||val===undefined)continue;var r=new RegExp("(#|&)"+key+"=([^&#]*)(&|#|$)");var m=_oriHash.match(r);if(m){var r2=new RegExp("(#|&)"+key+"=([^&#]*)");_oriHash=_oriHash.replace(r2,"")}_oriHash+=(_oriHash.indexOf("#")>=0?"&":"#")+key+"="+val}if(!frameElement){var title=document.title;location.hash=_oriHash;document.title=title}else location.hash=_oriHash;
this.addUserHistory(args1,args2)},addUserHistory:function(args1,args2){},clean:function(){var title=document.title;location.hash="#nojump=1";document.title=title;return this}};
var PAGE_CACHE={namespace:"",BLOG_CACHE_MASTER_KEY:"QZONE_BLOG_CACHE_MANAGER",BLOG_CACHE_KEY_LIST:"QZONE_BLOG_CACHE_MANAGER_KEY_LIST",CACHE_WIN:QZONE.FP._t,setNameSpace:function(ns){this.namespace=ns},add:function(key,data,expired){return this.set(key,data,expired)},set:function(key,data,expired){try{key=this.namespace+key;if(!this.CACHE_WIN[this.BLOG_CACHE_MASTER_KEY]){this.CACHE_WIN[this.BLOG_CACHE_MASTER_KEY]={};this.CACHE_WIN[this.BLOG_CACHE_KEY_LIST]={}}this.CACHE_WIN[this.BLOG_CACHE_MASTER_KEY][key]=
{"data":data,"expired":parseInt(expired,10)*1E3+(new Date).getTime()};this.CACHE_WIN[this.BLOG_CACHE_KEY_LIST][key]=true;return true}catch(ex){return false}},get:function(key){try{key=this.namespace+key;var cache_data=QZONE.FP._t[this.BLOG_CACHE_MASTER_KEY][key];if(cache_data)if(!cache_data.expired||cache_data.expired<0)return cache_data.data;else{var time=(new Date).getTime();if(cache_data.expired>time)return cache_data.data;else{this.remove(key);return null}}}catch(ex){}return null},remove:function(key){try{key=
this.namespace+key;this.CACHE_WIN[this.BLOG_CACHE_MASTER_KEY][key]=undefined}catch(ex){QZFL.console.print("ex")}},clean:function(key){if(key)this.remove(key);else try{this.CACHE_WIN[this.BLOG_CACHE_MASTER_KEY]=undefined}catch(ex){QZFL.console.print("ex")}}};window.BlogListReporter||(window.BlogListReporter={markPoint:function(){}});
(function(){if(window.BlogList)throw"BlogList ALREADY DEFINED";PAGE_CACHE.setNameSpace("BLOGLIST_");window.BlogList={inited:false,isOwner:QZBlog.Logic.SpaceHostInfo.isOwnerMode(),data:INIT_PAGE_DATA,fixAbstract:_fixAbstract,long2shorttime:_long2shorttime,Config:{pageSize:{"0":15,1:15},blogListCacheTime:20,blogReadInfoCacheTime:30},defaultFilter:{},currentFilter:{},init:function(){var self=this;self.defaultFilter={page:1,cateHex:null,cateName:null,sortType:parent.BlogListNavigator.getSortType()||0,
viewmode:parseInt(INIT_PAGE_DATA.hostFlag,10)==1?1:0,startTime:null,endTime:null};if(!!parent.BlogListNavigator.getCurrentDate()){var curDate=parent.BlogListNavigator.getCurrentDate();var curCate=parent.BlogListNavigator.getCurrentCate();var spanTime=QZBlog.Util.getMonthSpanTime(parseInt(curDate["year"],10),parseInt(curDate["month"],10));startTime=spanTime["start"];endTime=spanTime["end"];self.defaultFilter.statYear=parseInt(curDate["year"]);self.defaultFilter.startTime=startTime;self.defaultFilter.endTime=
endTime}if(!!parent.BlogListNavigator.getCurrentCate()){self.defaultFilter.cateName=parent.BlogListNavigator.getCurrentCate();self.defaultFilter.cateHex=parent.BlogListNavigator.getCurrentCatehex()}self.currentFilter=QZFL.object.extend(true,{},self.defaultFilter);self.bindPageEvent();self.updateBasicPageView();if(PAGE_CATALOG=="list")self.showPage({page:parseInt(getParameter("page"),10)||1});self.inited=!QZBlog.Logic.isSeoPage;self.updateAvatar();self.showHelpTips();self.showAd($("side_ad"));self.showBottomVipAd();
self.fireEvent("coreinited");self.clickTrack();PAGE_ROUTER.addUserHistory=function(args1,args2){if(QZONE.FP.appendHash&&!QZBlog.Logic.isSeoPage)if(typeof args1=="object"&&args1.catalog)QZONE.FP.appendHash(2,"catalog_"+args1.catalog);else if(args1=="catalog"&&args2)QZONE.FP.appendHash(2,"catalog_"+args2)};PAGE_ROUTER.set("catalog",PAGE_CATALOG);var ti=$e("a").elements[0];if(ti)ti.focus()},clickTrack:function(){var k="QZONE_BLOG_CLICK_TRACK";if(parent[k]===undefined)parent[k]=Math.random()<1.0E-4;if(parent[k])setTimeout(function(){var sc=
document.createElement("script");sc.src="http://qzonestyle.gtimg.cn/qzone/app/tracer/lib/yom/require/require-built.js";sc.setAttribute("data-main","http://qzonestyle.gtimg.cn/qzone/app/tracer/tracer/main-built.js");sc.setAttribute("data-param","bid=1&pid=1");document.body.appendChild(sc)},1E3)},showAd:function(container){if(!container||QZBlog.Logic.isInPengyou)return;QZBlog.Util.loadQBossAd("2189",function(html,adData){container.style.display="";container.innerHTML=html;$e("a",container).onClick(function(){QZBlog.Util.reportQBossState(adData.bosstrace,
3)});QZBlog.Logic.TCISDClick.batchBind({".showInVip a":"sidead.vipAd",".showInNoVip a":"sidead.noVipAd"},{url:"/BlogList",container:container})})},_bottomAdDataCache:null,showBottomVipAd:function(){if(QZBlog.Logic.isInPengyou)return;var self=this;var _hideAd=function(){if(!!$("vipBottomAdContainer"))QZFL.css.addClassName($("vipBottomAdContainer"),"none")};QZBlog.Logic.batchDelegate({"a[rel=draft-list-link]":_hideAd,"a[rel=setting-link]":_hideAd});var _render=function(data){if(!$("vipBottomAdContainer")){var parentContainer=
$e("#app_mod_blog .main").elements[0];if(!parentContainer)return;QZFL.dom.createElementIn("div",parentContainer,false,{id:"vipBottomAdContainer"})}QZFL.css.removeClassName($("vipBottomAdContainer"),"none");$("vipBottomAdContainer").innerHTML=data.html;var vipButton=$e("#blogPrivilegeAd span").elements[0];if(!!vipButton)vipButton.className=!!QZONE.FP.isVipUser(true)?"ico_vip_renew":"ico_vip_open"};BlogList.triggerEvent("showpage",function(){if(!self._bottomAdDataCache){var _loader=new QZFL.JSONGetter("http://"+
parent.siDomain+"/qzone/newblog/recommend/vip_recommend.js",void 0,null,"utf-8");_loader.onSuccess=function(re){self._bottomAdDataCache=re;_render(QZFL.lang.objectClone(self._bottomAdDataCache))};_loader.send("_Callback");_loader.onError=function(){}}else _render(QZFL.lang.objectClone(self._bottomAdDataCache))})},showHelpTips:function(){var _this=this;$e(".blog_import .icon_help").onHover(function(){var idx,t=this;$e(".blog_import .icon_help").each(function(el,i){if(el===t)idx=i});$e(".blog_import .bubble_wrap:eq("+
idx+")").removeClass("none")},function(e){$e(".blog_import .bubble_wrap").addClass("none")})},showBlogDetail:function(node){var blogid=node.getAttribute("blogid");var extParam={blogId:blogid,page:this.currentFilter.page,refererurl:location.href};if(!this.isOwner)try{var rcPool=parent.g_XDoc&&parent.g_XDoc["blogCommentCount"]?parent.g_XDoc["blogCommentCount"]:{};if(rcPool&&rcPool[blogid])rcPool[blogid].read++;var cnt=PAGE_CACHE.get("blog_read_num_"+blogid);PAGE_CACHE.add("blog_read_num_"+blogid,cnt+
1)}catch(ex){QZFL.console.print("showBlogDetail rd num:"+ex)}else PAGE_CACHE.clean();QZBlog.Router.redirectTo("blogcontent",extParam)},updateBasicPageView:function(){if($("blog-top-nav"))$("blog-top-nav").style.display="";if(!this.isOwner)$e("a[rel=blog-list-link]").elements[0].href="http://user.qzone.qq.com/"+QZBlog.Logic.SpaceHostInfo.getUin()+"/blog"},updateAvatar:function(){$e("img.current-space-avatar").each(function(img){if(img.src)return;var cache_key="avatar_"+QZBlog.Logic.SpaceHostInfo.getUin()+
"_"+img.getAttribute("_width");var src=PAGE_CACHE.get(cache_key);if(!src){src=QZBlog.Util.PortraitManager.getPortraitUrl(QZBlog.Logic.SpaceHostInfo.getUin(),img.getAttribute("_width"));PAGE_CACHE.add(cache_key,src)}if(!src)return;img.src=src;var t=QZBlog.Logic.SpaceHostInfo.isOwnerMode()?"\u6211\u7684\u5934\u50cf":"\u4e3b\u4eba\u5934\u50cf";img.setAttribute("alt",t);img.title=t})},updatePageView:function(data){$("app_mod_blog").style.display="";$("app_mod").style.display="none";this.updateAvatar();
this.updateBasicPageView();if($e("span[rel=total-blog-count]").elements[0])$e("span[rel=total-blog-count]").elements[0].innerHTML=data.totalnum||0;if(data&&data.hostFlag!=undefined)this.toggleViewMode(data.hostFlag);if(!data||!data.list.length)$("list-toolbar").style.display="none";else{$("list-toolbar").style.display="";var i,l,dataItem,blogid,label,icon,obj;for(i=0,l=data.list.length;i<l;i++){dataItem=data.list[i];blogid=dataItem.blogId;label=this.getBlogLabel(dataItem);if(label){obj=$("blog-label-"+
blogid);if(obj){obj.innerHTML=label;obj.style.display=""}}icon=this.getBlogIcon(dataItem);title=this.getBlogMediaTypeTitle(dataItem);if(icon){obj=$("blog-icon-"+blogid);if(obj){obj.title=title;obj.className=icon;obj.style.display=""}}if(this.getEffectBit(dataItem,29)&&this.isOwner){obj=$("blog-priicon-"+blogid);if(obj){obj.className="icon icon_lock";obj.style.display=""}}}}this.updateBlogOrderSelector(this.currentFilter.sortType);this.cleanMainNavHoverEffect();var side_blog_nav=$e("#main-nav a[rel=blog-list-link]:first").elements[0];
QZFL.css.addClassName(side_blog_nav,"selected")},resizeFrame:function(){setTimeout(function(){frameElement.height=Math.max(document.body.scrollHeight,document.body.offsetHeight)+"px";frameElement.parentNode.style.height="auto"},100)},getBlogIcon:function(blog){var blogIconList={"0":"icon icon_img",13:"icon icon_video"};for(var bit in blogIconList)if(this.getEffectBit(blog,bit))return blogIconList[bit];return null},getBlogMediaTypeTitle:function(blog){var blogTitleList={"0":"\u65e5\u5fd7\u4e2d\u5305\u542b\u56fe\u7247",
13:"\u65e5\u5fd7\u4e2d\u5305\u542b\u89c6\u9891"};for(var bit in blogTitleList)if(this.getEffectBit(blog,bit))return blogTitleList[bit];return null},getBlogLabel:function(blog){var blogEffectList=[["8","\u5ba1\u6838\u4e0d\u901a\u8fc7"],["22","\u5ba1\u6838\u4e2d"],["4","\u9876"],["21","\u8350"],["3","\u8f6c"],["28","\u8f6c"],["35","\u8f6c"],["36","\u8f6c"]];var _getEffStr=function(idx){for(var i=0;i<blogEffectList.length;i++)if(blogEffectList[i][0]==idx)return blogEffectList[i][1]};var label="";for(var i=
0;i<blogEffectList.length;i++){var bit=blogEffectList[i][0];if(bit==22)continue;if(this.getEffectBit(blog,bit)){label+='<span class="'+(bit==3||bit==28||bit==35||bit==36?"c_tx3":"c_tx4")+'" rel="blog-detail-link" blogid="'+blog.blogId+'"'+">["+blogEffectList[i][1]+"]</span>";if(bit==8)break}}return label},getEffectBit:function(bloginfo,nBit){if(nBit<0||nBit>63)throw new Error("nBit param error");if(nBit<32)return bloginfo.effect1&1<<nBit;else if(nBit<64)return bloginfo.effect2&1<<nBit},switchToBlogList:function(){QZFL.widget.bubble.hideAll();
$("app_mod_blog").style.display="";$("app_mod").style.display="none";this.initSideCateNavHoverEffect();try{parent.BlogListNavigator.setCurrentDate(null);parent.BlogListNavigator.setCurrentCate("");if(BlogList.Calendar)BlogList.Calendar.showDateInfo();if(BlogList.Category){BlogList.Category.disHighLightAllCate();BlogList.Category.showCategoryList()}}catch(ex){}this.showPage({"cateName":null,"cateHex":null,"startTime":null,"endTime":null,"page":1})},bindPageEvent:function(){var _this=this;QZBlog.Logic.batchDelegate({"a[rel=blog-list-link]":function(){_this.switchToBlogList()},
"a[rel=switch-abstract-mode]":function(){_this.toggleViewMode(parent.BlogListViewType["DIGEST"])},"a[rel=switch-list-mode]":function(){_this.toggleViewMode(parent.BlogListViewType["CLASSIC"])},"a[rel=blog-detail-link]":function(node){_this.showBlogDetail(node)},"a[rel=blog-list-prev-page-link]":function(){var page=_this.currentFilter.page-1;page=page>0?page:1;_this.showPage({page:page})},"a[rel=current-space-link]":function(){QZONE.FP._t.location.href=QZBlog.Logic.SpaceHostInfo.getSpaceUrl()}});QZFL.event.addEvent(document.body,
"click",QZFL.object.bind(this,this.toggleBlogOrderSelector))},cleanMainNavHoverEffect:function(){$e("#main-nav>li>a").removeClass("selected");$e("div.mod_tabs_other a").removeClass("current")},cleanSideCateNavHoverEffect:function(){var side_nav_list=$e("#cateListContainer li a").elements;for(var i=0;i<side_nav_list.length;i++){var a=side_nav_list[i];if(QZFL.css.hasClassName(a,"c_tx2"))QZFL.css.replaceClassName(a,"c_tx2","c_tx")}},initSideCateNavHoverEffect:function(){var side_nav_list=$e("#cateListContainer li a").elements;
for(var i=0;i<side_nav_list.length;i++){var a=side_nav_list[i];if(QZFL.css.hasClassName(a,"c_tx2"))QZFL.css.replaceClassName(a,"c_tx2","c_tx")}if(side_nav_list.length>0){var a=side_nav_list[0];if(QZFL.css.hasClassName(a,"c_tx"))QZFL.css.replaceClassName(a,"c_tx","c_tx2")}},showPagination:function(pageIndex,itemTotal,pageSize){pageIndex=parseInt(pageIndex,10)||0;itemTotal=parseInt(itemTotal,10)||0;pageSize=parseInt(pageSize,10)||0;if(pageIndex<1||itemTotal<1||pageSize<1||itemTotal<=pageSize){$("pagination").style.display=
"none";return}$("pagination").style.display="";var pageTotal=Math.ceil(itemTotal/pageSize);QZBlog.Util.PageIndexManager.init([$("pagination")],pageTotal,pageIndex,QZFL.object.bind(this,function(pageIndex){this.showPage({page:pageIndex});if(this.currentFilter.viewmode==parent.BlogListViewType["DIGEST"])QZBlog.Util.jumpTop(true)}))},showPage:function(filter){var _this=this;this.getPageData(filter,function(data){if(filter.page>1&&!data.list.length){filter.page-=1;_this.showPage(filter);return}_this.data=
data;if(_this.inited||QZBlog.Logic.isSeoPage&&window.BLOGLIST_SEO_RENDED)_this.renderList(data);else{_this._toggleViewModeUI(_this.currentFilter.viewmode);QZBlog.Util.Statistic.addSpeedPoint(5);QZBlog.Util.Statistic.sendSpeedStatistic(112,6)}_this.loadReadNum(data);_this.updatePageView(data);try{parent.BlogListNavigator.setSortType(_this.currentFilter.sortType)}catch(ex){}var pageIndex=_this.currentFilter.page||1;_this.showPagination(pageIndex,data.totalNum,_this.Config.pageSize[_this.currentFilter.viewmode]);
_this.fireEvent("showpage",data);filter.catalog="list";PAGE_ROUTER.clean().set(filter);QZBlog.Util.Statistic.sendPV("showlist");if(!_this.isOwner)QZBlog.Util.Statistic.sendPV("showlist.guest")})},toggleViewMode:function(viewmode){if(!this.isOwner)parent["BLOG_LIST_VIEW_MODE_"+QZBlog.Logic.SpaceHostInfo.getUin()]=viewmode;this._toggleViewModeUI(viewmode);if(viewmode==this.currentFilter.viewmode)return;var v;if(typeof viewmode=="undefined"||viewmode!=parent.BlogListViewType["DIGEST"]&&viewmode!=parent.BlogListViewType["CLASSIC"])v=
this.currentFilter.viewmode==parent.BlogListViewType["DIGEST"]?parent.BlogListViewType["CLASSIC"]:parent.BlogListViewType["DIGEST"];else v=viewmode;this.showPage({viewmode:v});if(this.isOwner)this.saveViewMode(v);this.fireEvent("toggleviewmode",v)},_toggleViewModeUI:function(v){var uin=QZBlog.Logic.SpaceHostInfo.getLoginUin();parent.g_oBlogSettingInfoMgr.setListMode(uin,v);$e("a[rel=switch-abstract-mode]").elements[0].style.display=v==1?"none":"";$e("a[rel=switch-list-mode]").elements[0].style.display=
v==0?"none":""},toggleBlogOrderSelector:function(e){var tag=QZFL.event.getTarget(e);var mnu_p=$("order-by-sel");var mnu=$("order-by-mnu");var _this=this;if(mnu.style.display=="none"&&(tag==mnu_p||tag.parentNode==mnu_p)){mnu_p.className="bor2 select_order c_tx";mnu.style.display="";var offset=[0,0];var offset_p=QZFL.dom.searchChain(mnu,"parentNode",function(node){if(QZFL.dom.getStyle(node,"position")=="relative"&&node.tagName!="BODY")return true});if(offset_p)offset=QZFL.dom.getXY(offset_p);var s=
QZFL.dom.getSize(mnu_p);var p=QZFL.dom.getXY(mnu_p);mnu.style.top=p[1]+s[1]-offset[1]+"px";mnu.style.left=p[0]-offset[0]+"px";if(!mnu.getAttribute("binded")){$e("a",mnu).bind("click",function(){var val=parseInt(this.getAttribute("val"),10);if(val!=_this.currentFilter.sortType)_this.showPage({sortType:val,page:1});QZFL.event.preventDefault();return false});mnu.setAttribute("binded","1")}}else{mnu_p.className="c_tx";mnu.style.display="none"}},updateBlogOrderSelector:function(sortType){var orders={"0":["\u53d1\u8868\u65f6\u95f4",
"\u6309\u53d1\u8868\u65f6\u95f4\u7531\u65b0\u5230\u65e7\u6392\u5e8f"],1:["\u8bc4\u8bba\u65f6\u95f4","\u6309\u6700\u65b0\u8bc4\u8bba\u65f6\u95f4\u7531\u65b0\u5230\u65e7\u6392\u5e8f"],3:["\u6700\u65b0\u4fee\u6539","\u6309\u6700\u540e\u4fee\u6539\u65f6\u95f4\u7531\u65b0\u5230\u65e7\u6392\u5e8f"],4:["\u8bc4\u8bba\u6570\u76ee","\u6309\u8bc4\u8bba\u6570\u76ee\u7531\u591a\u5230\u5c11\u6392\u5e8f"]};sortType=parseInt(sortType,10)||0;$("order-by-sel").innerHTML=orders[sortType][0]+'<span class="mod_arr"></span>';
$("order-by-sel").title=orders[sortType][1];$e("#order-by-mnu a").each(function(a){a.parentNode.style.display=a.getAttribute("val")==sortType?"none":""})},saveViewMode:function(viewmode,callback){var param="titlelist_v="+(viewmode+1);QZBlog.Logic.setBlogSetting(param,function(){parent.g_oBlogSettingInfoMgr.setListMode(QZBlog.Logic.SpaceHostInfo.getLoginUin(),viewmode)},true)},loadReadNum:function(pageData){var blogidArr=[],cache_data,need_refresh=false,_this=this;for(var i=0;i<pageData.list.length;i++){var blogid=
pageData.list[i].blogId;blogidArr.push(blogid);if(!need_refresh){var _data=PAGE_CACHE.get("blog_read_num_"+blogid);if(_data!==null){if(!cache_data)cache_data={};cache_data[blogid]=_data}else need_refresh=true}}var handler=function(data){for(var blogid in data){var viewCnt=data[blogid];if($("view-cnt-"+blogid)){$("view-cnt-"+blogid).innerHTML=viewCnt>Math.pow(10,6)?"999999+":viewCnt;if(_this.currentFilter.viewmode==0)$("view-cnt-"+blogid).parentNode.title="\u8bc4\u8bba:"+$("reply-cnt-"+blogid).getAttribute("cnt")+
"/\u9605\u8bfb:"+viewCnt}if(!parent.g_XDoc)parent.g_XDoc={};if(!parent.g_XDoc["blogCommentCount"])parent.g_XDoc["blogCommentCount"]={};if(!parent.g_XDoc["blogCommentCount"][blogid])parent.g_XDoc["blogCommentCount"][blogid]={};parent.g_XDoc["blogCommentCount"][blogid].read=viewCnt}};if(need_refresh)QZBlog.Logic.getBlogViewInfo(blogidArr,QZFL.object.bind(this,function(data){var blogid=-1;var rawData=data.data;var tmp={};for(var i=0;i<rawData.itemList.length;++i){var blogid=rawData.itemList[i].id;var _blog=
_this.getBlog(blogid);console.log("\u9605\u8bfb\u6570\uff1a\u8bc4\u8bba\u6570",rawData.itemList[i].read,_blog.getCommentCnt());tmp[blogid]=Math.max(rawData.itemList[i].read,_blog.getCommentCnt());PAGE_CACHE.add("blog_read_num_"+blogid,tmp[blogid],this.Config.blogReadInfoCacheTime)}handler(tmp)}));else handler(cache_data)},renderList:function(data){var html="";try{if(data&&data.code==0&&data.list.length){data.isOwner=this.isOwner;html=tmpl(this.currentFilter.viewmode==parent.BlogListViewType["CLASSIC"]?
LIST_PAGE_TPL:LIST_ABSTRACT_TPL,data)}else if(data&&data.code==0&&!data.list.length)if((this.currentFilter.cateHex||this.currentFilter.cateName)&&this.currentFilter.page==1){var category="";if(this.currentFilter.cateName)category=this.currentFilter.cateName;else{var catelist=INIT_PAGE_DATA.cateInfo.categorylist;for(var i=0;i<catelist.length;i++)if(catelist[i].catehex==this.currentFilter.cateHex){category=catelist[i].category;break}}html=PAGE_DATA_EMPTY_CATE_TPL.replace(/category=""/i,'category="'+
category+'"')}else if(this.currentFilter.page>1)setTimeout(QZFL.object.bind(this,function(){this.showPage({page:this.currentFilter.page-1})}),100);else html=PAGE_DATA_EMPTY_TPL;else html=PAGE_DATA_ERROR_TPL}catch(ex){html=PAGE_DATA_ERROR_TPL}$("page-container-blog").innerHTML=html},getPageData:function(filter,succCallback,errCallback){this.currentFilter=QZFL.object.extend(this.currentFilter,filter);var CGI_FILTER={verbose:0,blogType:0,cateHex:this.currentFilter.cateHex||"",cateName:(this.currentFilter.cateName||
"").toRealStr().URLencode(),pos:(this.currentFilter.page-1)*this.Config.pageSize[this.currentFilter.viewmode],num:this.Config.pageSize[this.currentFilter.viewmode],sortType:this.currentFilter.sortType,absType:this.currentFilter.viewmode,statYear:this.currentFilter.statYear,startTime:this.currentFilter.startTime,endTime:this.currentFilter.endTime};var cache_key="";for(var i in CGI_FILTER)if(CGI_FILTER[i])cache_key+=i+"_"+CGI_FILTER[i]+"__";var cache_data=PAGE_CACHE.get(cache_key);if(cache_data)succCallback(cache_data);
else if(!this.inited&&!QZBlog.Logic.isSeoPage){succCallback(INIT_PAGE_DATA);PAGE_CACHE.add(cache_key,INIT_PAGE_DATA,this.Config.blogListCacheTime)}else if(QZBlog.Logic.isSeoPage&&!window.BLOGLIST_SEO_RENDED){succCallback(INIT_PAGE_DATA);window.BLOGLIST_SEO_RENDED=true}else{var _this=this;var handler=function(retData){if(retData&&retData.data){var data=retData.data;data.code=retData.code;for(var i=0;i<data.list.length;i++){var blog=data.list[i];var len=QZFL.string.getRealLen(blog.title)*2;data.list[i]["abstract"]=
_this.fixAbstract(blog["abstract"]);data.list[i].shorttitle=blog.title;data.list[i].shortpubtime=_this.long2shorttime(blog.pubTime);var extParam={page:parseInt(getParameter("page"),10)||1};data.list[i].blogurl="http://"+(QZBlog.Logic.isInPengyou?"baseapp.pengyou.com":"user.qzone.qq.com")+"/"+QZBlog.Logic.SpaceHostInfo.getUin()+"/blog/"+blog.blogId}return data}};var url=QZBlog.CGI_URL.get("get_abs");var dataFn=function(){return QZBlog.Util.getNewBlogListUrlData(CGI_FILTER)};var req=new QZBlog.Util.NetRequest({url:url,
data:dataFn,method:"get",uniqueCGI:true,maxRequestInterval:0,domainReverted:1});req.onSuccess=function(retData){if(retData.data&&retData.code==0){var data=handler(retData);PAGE_CACHE.add(cache_key,data,_this.Config.blogListCacheTime);succCallback&&succCallback(data)}else errCallback&&errCallback(retData)};req.send()}},jumpToUrl:function(url){setTimeout(function(){location.href=url},0)},getBlog:function(blogid,blogData){if(blogid>-1)for(var i=0;i<this.data.list.length;i++)if(this.data.list[i].blogId==
blogid)blogData=this.data.list[i];if(!blogData)return;var rightinfo=new parent.BlogRightInfo;rightinfo.setType(blogData.artype);var _uins=blogData.arUins&&blogData.arUins.length?blogData.arUins.split(","):null;if(_uins){var _u=[];for(var i=0;i<_uins.length;i++){var _tmp=new parent.UserInfo;_tmp.setUin(_uins[i]);_u.push(_tmp)}}rightinfo.setUserList(_u);var bloginfo=new parent.BlogInfo;bloginfo.setCategoryName(blogData.cate);bloginfo.setID(blogid);bloginfo.setEffect(blogData.effect1);bloginfo.setEffect2(blogData.effect2);
bloginfo.setCommentCnt(blogData.commentNum);bloginfo.setType(blogData.blogType);bloginfo.setRightInfo(rightinfo);bloginfo.isPhotoBlog=blogData.blogType==1;bloginfo.isTemplateBlog=blogData.blogType==2;bloginfo.isGridBlog=!!bloginfo.getEffectBit(52);return bloginfo}};BlogList=QZFL.object.extend(BlogList,PAGE_EVENT);var _PAGE_ERROR_TM1=setTimeout(function(){if($("page-error"))$("page-error").style.display="";QZBlog.Util.Statistic.sendPV("showlist_timeout_5s")},5E3);var _PAGE_ERROR_TM2=setTimeout(function(){QZBlog.Util.Statistic.sendPV("showlist_timeout_10s")},
1E4);BlogListReporter.markPoint(6);var cb=function(){setTimeout(function(){BlogListReporter.markPoint(7);BlogList.init();if(INIT_PAGE_DATA&&INIT_PAGE_DATA.cateInfo)parent.g_oCateInfoMgr.convertJsonObject(INIT_PAGE_DATA.cateInfo);BlogListReporter.markPoint(8)},0);if($("page-error"))$("page-error").style.display="none";clearTimeout(_PAGE_ERROR_TM1);clearTimeout(_PAGE_ERROR_TM2);try{var p=QZONE.FP.getStatPackage().valueStat(400678,2,1,{"reportRate":1,"duration":0})}catch(ex){}};var isTimeoutHandled=
false;var serverTimeoutTimer=null;var renderInitialView=function(){var pageContainerBlogNode=$("page-container-blog");if(PAGE_CATALOG=="list"){if(!INIT_PAGE_DATA||INIT_PAGE_DATA.code!=0)if(INIT_PAGE_DATA.code==-204||INIT_PAGE_DATA.error=="no right"){pageContainerBlogNode.innerHTML=PAGE_ACCESS_ERROR;QZFL.event.addEvent($("returnMySpace"),"click",function(){QZONE.FP._t.location.href=QZBlog.Util.getSpaceUrl(QZBlog.Util.getLoginUin())})}else if(INIT_PAGE_DATA.error=="login")pageContainerBlogNode.innerHTML=
PAGE_DATA_LOGIN_TPL;else pageContainerBlogNode.innerHTML=PAGE_DATA_ERROR_TPL;else if(INIT_PAGE_DATA.list.length){var type=parseInt(INIT_PAGE_DATA.hostFlag,10);pageContainerBlogNode.innerHTML=tmpl(type==1?LIST_ABSTRACT_TPL:LIST_PAGE_TPL,INIT_PAGE_DATA)}else if(INIT_PAGE_DATA.list.length==0&&getParameter("cate"))pageContainerBlogNode.innerHTML=PAGE_DATA_EMPTY_CATE_TPL.replace(/category=""/i,'category="'+getParameter("cate")+'"');else pageContainerBlogNode.innerHTML=PAGE_DATA_EMPTY_TPL;$("rightCateArea").innerHTML=
tmpl(CATEGORY_TPL,INIT_PAGE_DATA);$("app_mod_blog").style.display=""}};var pageStart=function(){if(parent.BlogListNavigator){console.log("basic.js\u5df2\u52a0\u8f7d");cb()}else parent.QZFL.imports("http://"+parent.siDomain+"/qzone/newblog/v5/script/basic.js",cb)};var onInitialDataLoadSuccess=function(data){if(isTimeoutHandled)return;clearTimeout(serverTimeoutTimer);BlogListReporter.markPoint(4);if(data&&data.data&&data.code==0){INIT_PAGE_DATA=QZFL.object.extend(INIT_PAGE_DATA,data.data);INIT_PAGE_DATA.code=
data.code;if(!!INIT_PAGE_DATA.month_num)INIT_PAGE_DATA.year=curYear;if(INIT_PAGE_DATA.list){INIT_PAGE_DATA.isOwner=QZBlog.Logic.SpaceHostInfo.isOwnerMode();for(var i=0;i<INIT_PAGE_DATA.list.length;i++){var blog=INIT_PAGE_DATA.list[i];var len=QZFL.string.getRealLen(blog.title)*2;INIT_PAGE_DATA.list[i]["abstract"]=_fixAbstract(blog["abstract"]);INIT_PAGE_DATA.list[i].shorttitle=blog.title;INIT_PAGE_DATA.list[i].shortpubtime=_long2shorttime(blog.pubTime);INIT_PAGE_DATA.list[i].blogurl="http://"+(QZBlog.Logic.isInPengyou?
"baseapp.pengyou.com":"user.qzone.qq.com")+"/"+QZBlog.Logic.SpaceHostInfo.getUin()+"/blog/"+blog.blogId}}}else if(data.code==-3E3){INIT_PAGE_DATA.error="login";QZONE.FP.showLoginBox(null,function(){location.reload()})}else if(data.code==-4002){QZONE.FP.showMsgbox(data.message,1,2E3);INIT_PAGE_DATA.error="login";QZONE.FP.showLoginBox(null,function(){location.reload()})}else if(data.code==-4009){QZONE.FP.showMsgbox(data.message,1,2E3);INIT_PAGE_DATA.error="no right"}renderInitialView(INIT_PAGE_DATA);
pageStart()};var viewmode=parent["BLOG_LIST_VIEW_MODE_"+QZBlog.Logic.SpaceHostInfo.getUin()]||0;var listCgiUrl=QZBlog.CGI_URL.get("get_abs")+"?"+QZBlog.Util.buildParam(QZBlog.Util.getNewBlogListUrlData({absType:!QZBlog.Logic.SpaceHostInfo.isOwnerMode()&&typeof viewmode!=undefined?viewmode:null,verbose:currentDate["year"]&&currentDate["month"]?0:1,sortType:sortType||0,reqInfo:requestParam,statYear:curYear,startTime:spanTime["start"]||null,endTime:spanTime["end"]||null,cateName:currentCate,cateHex:currentCatehex,
pos:(pageIndex-1)*pageSize,num:pageSize}));if(PAGE_CATALOG=="list"){console.log("\u5217\u8868\u9875\uff0c\u8d70\u57df\u540d\u6536\u5f52\u903b\u8f91");var $jsonGet=null;try{$jsonGet=parent.$j.jsonGet}catch(err){}if($jsonGet){$jsonGet(listCgiUrl,null,{charset:"gb2312",callback:onInitialDataLoadSuccess,onerror:function(){clearTimeout(serverTimeoutTimer);renderInitialView();pageStart()}});serverTimeoutTimer=setTimeout(function(){renderInitialView();pageStart();isTimeoutHandled=true},1E4)}else{var snd=
new QZFL.JSONGetter(listCgiUrl,void 0,null,"gb2312");snd.onSuccess=onInitialDataLoadSuccess;snd.onError=function(){renderInitialView();pageStart()};snd.send("_Callback")}BlogListReporter.markPoint(3)}else{BlogListReporter.markPoint(12);pageStart()}})();
(function(BlogList,window,undefined){BlogList.Calendar={init:function(){if(!$("calendarTemplate"))return;var _this=this;BlogList.triggerEvent("refreshCurrentPage",function(){parent.g_oCateInfoMgr.clear();_this.showDateInfo()});BlogList.triggerEvent("coreinited",function(){var year=_this.getCurrentYear();if(INIT_PAGE_DATA&&!!INIT_PAGE_DATA.month_num)if(INIT_PAGE_DATA.year==year&&!parent.g_oCateInfoMgr.getDateInfo(year))_this.fillInitCalendar();if(typeof _this._templateHTML=="undefined")_this._templateHTML=
$("calendarTemplate").innerHTML;_this.showDateInfo();BlogListReporter.markPoint(9)})},fillInitCalendar:function(){var year=this.getCurrentYear();var data={"month_num":INIT_PAGE_DATA["month_num"],"year":year};data["year"]=year;var oDateInfo=new parent.BlogDateInfo;oDateInfo.convertJsonObject(data);parent.g_oCateInfoMgr.setDateInfo(year,oDateInfo)},getCurrentYear:function(year){var time=new Date(parent.g_NowTime*1E3);var curYear=time.getYear()<1900?1900+time.getYear():time.getYear();var _this=this;
if(!year)if(!!parent.BlogListNavigator)if(parent.BlogListNavigator.getCurrentDate()&&typeof parent.BlogListNavigator.getCurrentDate()["year"]!="undefined")year=parent.BlogListNavigator.getCurrentDate()["year"];else year=curYear;else year=curYear;if(year>curYear||year<1970)return curYear;return year},showDateInfo:function(year,month,refresh){var _this=this;year=_this.getCurrentYear(year);QZBlog.Logic.getDateInfo(year,function(dateInfo){if(!dateInfo)return;var curMonth=-1;if(month){curMonth=month;parent.BlogListNavigator.setCurrentDate({year:year,
month:month})}else{var curDate=parent.BlogListNavigator.getCurrentDate();if(curDate&&typeof curDate["month"]!="undefined"&&curDate["year"]==year)curMonth=curMonth>=0?curMonth:curDate["month"]}var oInfo={};oInfo.curMonth=curMonth;oInfo.curYear=year;oInfo.prevYear=year-1;oInfo.nextYear=year+1;oInfo.curTotalNum=dateInfo.getTotalNum();oInfo.list=[];for(var index=0;index<12;++index)oInfo.list.push(parseInt(dateInfo.getNum(index+1),10));$("calendarArea").innerHTML=tmpl(_this._templateHTML,{"dateInfo":oInfo})},
refresh)},refreshCalendar:function(){var curDateInfo=parent.BlogListNavigator.getCurrentDate();if(curDateInfo){var y=curDateInfo.year,m=curDateInfo.month;var oDateInfo=new parent.BlogDateInfo;parent.g_oCateInfoMgr.setDateInfo(y,oDateInfo);parent.BlogListNavigator.setCurrentDate(oDateInfo);this.showDateInfo(y,m,true)}else this.showDateInfo(null,null,true)},selectDate:function(year,month){BlogList.Category.disHighLightAllCate();parent.BlogListNavigator.clear();parent.BlogListNavigator.setCurrentCate("");
parent.BlogListNavigator.setCurrentCatehex("");parent.BlogListNavigator.setCurrentDate({"year":year,"month":month});this.showDateInfo(year);var startTime=null;var endTime=null;var curDate=parent.BlogListNavigator.getCurrentDate();if(curDate&&typeof curDate["year"]!="undefined"&&typeof curDate["month"]!="undefined"){var spanTime=QZBlog.Util.getMonthSpanTime(curDate["year"],curDate["month"]);startTime=spanTime["start"];endTime=spanTime["end"]}var param={"cateName":null,"cateHex":null,"statYear":curDate["year"],
"startTime":startTime,"endTime":endTime,page:1,"catalog":"list"};BlogList.showPage(param);PAGE_ROUTER.clean().set(param)}};BlogList.Calendar.init()})(BlogList,window);
(function(BlogList,window,undefined){BlogList.Category={init:function(){var _this=this;BlogList.addEvent("cateupdate",function(){_this.showCategoryList(true)});BlogList.triggerEvent("coreinited",function(){_this.bindPageEvent();try{var data=INIT_PAGE_DATA.cateInfo;if(data&&!!data.categoryList.length){parent.g_oCateInfoMgr.convertJsonObject(data);BlogList.fireEvent("sidecaterendered")}else _this.showCategoryList()}catch(ex){}if(!BlogList.currentFilter.starttime&&!BlogList.currentFilter.endtime);else _this.disHighLightAllCate()})},
toggleMoreCateNavPanel:function(isShow){var node=$e("#cateListContainer .sort_more a:first").elements[0];if(!node)return;var _isShow=isShow===undefined?$("cateListMore").style.display=="none":!!isShow;if(_isShow){$e("span",node).elements[0].className="mod_arr arr_t";QZFL.css.addClassName(node,"bg bor3");QZFL.css.addClassName(node.parentNode,"drop_list_show")}else{$e("span",node).elements[0].className="mod_arr arr_r";QZFL.css.removeClassName(node,"bg bor3");QZFL.css.removeClassName(node.parentNode,
"drop_list_show")}$("cateListMore").style.display=_isShow?"":"none"},showCategoryList:function(fresh){var _this=this;QZBlog.Logic.getCategoryInfo(function(data){INIT_PAGE_DATA.cateInfo=data.data.cateInfo;if(BlogList.Manager)BlogList.Manager.cateData=data.data.cateInfo;$("rightCateArea").innerHTML=tmpl(CATEGORY_TPL,INIT_PAGE_DATA);BlogList.updateBasicPageView();_this.highLightCate(BlogList.currentFilter.cateName,BlogList.currentFilter.cateHex);BlogList.fireEvent("sidecaterendered")},QZFL.emptyFn,fresh)},
highLightCate:function(cate,catehex){if(!$("cateListContainer"))return;this.disHighLightAllCate();var liList=$("cateListContainer").getElementsByTagName("a");for(var index=0;index<liList.length;++index)if(cate&&liList[index].getAttribute("cate")==cate||catehex&&liList[index].getAttribute("catehex")==catehex){QZFL.css.addClassName(liList[index],"c_tx2");QZFL.css.addClassName(liList[index],"bg2");QZFL.css.removeClassName(liList[index],"c_tx");if(liList[index].getAttribute("inmorenav"))this.toggleMoreCateNavPanel(true);
break}else{QZFL.css.addClassName(liList[index],"c_tx");QZFL.css.removeClassName(liList[index],"c_tx2");QZFL.css.removeClassName(liList[index],"bg2")}if(!cate&&!catehex){QZFL.css.addClassName(liList[0],"c_tx2");QZFL.css.addClassName(liList[0],"bg2");QZFL.css.removeClassName(liList[0],"c_tx")}},disHighLightAllCate:function(){if(!$("cateListContainer"))return;var liList=$("cateListContainer").getElementsByTagName("a");for(var index=0;index<liList.length;++index){QZONE.css.removeClassName(liList[index],
"c_tx2");QZONE.css.removeClassName(liList[index],"bg2");QZONE.css.addClassName(liList[index],"c_tx");QZONE.css.removeClassName(QZFL.dom.getLastChild(liList[index].parentNode.parentNode),"c_tx2")}},selectCate:function(cate,catehex){if(typeof catehex=="undefined")catehex="";parent.BlogListNavigator.setCurrentDate(null);parent.BlogListNavigator.setCurrentCate(cate);parent.BlogListNavigator.setCurrentCatehex(catehex);if(BlogList.Calendar)BlogList.Calendar.showDateInfo();this.highLightCate(cate,catehex);
BlogList.showPage({"cateName":cate,"cateHex":catehex||null,"startTime":null,"endTime":null,"page":1});BlogList.fireEvent("category_select")},bindPageEvent:function(){var _this=this;QZBlog.Logic.batchDelegate({"a[rel=category-select-link]":function(node){var cate=node.getAttribute("cate");var catehex=node.getAttribute("catehex");_this.selectCate(cate,catehex)},"a[rel=category-toggle-more-panel]":function(){_this.toggleMoreCateNavPanel()}});QZFL.event.addEvent(document.body,"click",function(ev){var tag=
QZFL.event.getTarget(ev);var rel=tag.getAttribute("rel");if(rel!="category-select-link"&&rel!="category-toggle-more-panel")if(tag&&tag!=$("cateListMore")&&rel!="category-toggle-more-panel"&&!QZFL.dom.isAncestor($("cateListMore"),tag))_this.toggleMoreCateNavPanel(false)})}};BlogList.Category.init()})(BlogList,window);
(function(BlogList,window,undefined){BlogList.TCISD={URL:"/BlogList",init:function(){var evsRel={"write-blog-link":"Add.blog","write-photoblog-link":"Add.photoblog","write-gridblog-link":"Add.gridblog","write-templateblog-link":"Add.moban","switch-abstract-mode":"Set.Summarymode","switch-list-mode":"Set.Listmode","switch-batch-mode":"Volume_Set","list-more-menu-link":"Options","blog-edit-link":"Editblog","blog-report-link":"options.Report","blog-delete-link":"options.Delete","blog-right-setting-link":"options.Permissions_Set",
"blog-category-modify-link":"options.Editcatalog","blog-set-top-link":"options.Top_Set","blog-recommend-link":"options.Recommendation","blog-convert-private-link":"options.To_Private","setting-link":"Management.Blog","blog-list-link":"Blog","draft-list-link":"Drafts","private-blog-link":"Private_Blog","recycle-list-link":"Recycle_Bin","friendblog-link":"Frinends_Blog","notepad-link":"Notepad","category-manage-link":"Catalog.Management","category-select-link":"Catalog.List","support-link":"support"};
var mapViewmode={1:"Listmode.",2:"Summarymode."};QZFL.event.addEvent(document.body,"mousedown",QZFL.object.bind(this,function(ev){var tag=QZFL.event.getTarget(ev);var rel=tag.getAttribute("rel");var text="";if(tag&&tag.textContent!=undefined)text=tag.textContent;else if(tag&&tag.innerText!=undefined)text=tag.innerText;var id=tag.id;var parent=tag.parentNode;var viewmode=BlogList.currentFilter.viewmode;if(tag&&rel&&evsRel[rel])if(rel=="blog-detail-link")if(text&&text=="\u67e5\u770b\u5168\u6587"&&parent&&
QZFL.css.hasClassName(parent,"left"))QZBlog.Logic.TCISDClick("Summarymode.readblog",BlogList.TCISD.URL);else if(text&&text.indexOf("\u9605\u8bfb")>=0&&parent&&QZFL.css.hasClassName(parent,"left"))QZBlog.Logic.TCISDClick("Summarymode.Read_count",BlogList.TCISD.URL);else if(text&&text.indexOf("\u8bc4\u8bba")>=0&&parent&&QZFL.css.hasClassName(parent,"left"))QZBlog.Logic.TCISDClick("Summarymode.Comments_count",BlogList.TCISD.URL);else if(parent&&QZFL.css.hasClassName(parent,"mod_play"))QZBlog.Logic.TCISDClick("Summarymode.video",
BlogList.TCISD.URL);else{var hottag=mapViewmode[viewmode]+evsRel[rel];QZBlog.Logic.TCISDClick(hottag,BlogList.TCISD.URL)}else if(rel=="blog-edit-link"||rel=="list-more-menu-link"){var hottag=mapViewmode[viewmode]+evsRel[rel];QZBlog.Logic.TCISDClick(hottag,BlogList.TCISD.URL)}else{var hottag=evsRel[rel];QZBlog.Logic.TCISDClick(hottag,BlogList.TCISD.URL)}else if(tag&&QZFL.css.hasClassName(tag,"icon_img"))QZBlog.Logic.TCISDClick("Listmode.Photo",BlogList.TCISD.URL);else if(tag&&QZFL.css.hasClassName(tag,
"icon_video"))QZBlog.Logic.TCISDClick("Listmode.Video",BlogList.TCISD.URL);else if(tag&&text&&parent&&QZFL.css.hasClassName(parent,"mod_pagenav_count")){var regIdx=/^[0-9]*[1-9][0-9]*$/i;if(regIdx.test(text)&&QZFL.css.hasClassName(tag,"c_tx"))QZBlog.Logic.TCISDClick("Pager.Page_Number",BlogList.TCISD.URL)}else if(tag&&text&&parent&&QZFL.css.hasClassName(parent,"mod_pagenav_main")&&QZFL.css.hasClassName(tag,"c_tx"))if(text=="\u4e0a\u4e00\u9875")QZBlog.Logic.TCISDClick("Pager.Previous_Page",BlogList.TCISD.URL);
else{if(text=="\u4e0b\u4e00\u9875")QZBlog.Logic.TCISDClick("Pager.Next_Page",BlogList.TCISD.URL)}else if(tag&&text&&parent&&QZFL.css.hasClassName(parent,"mod_pagenav_turn"))if(text=="\u786e \u5b9a")QZBlog.Logic.TCISDClick("Pager.Goto_Page",BlogList.TCISD.URL)}));QZBlog.Logic.TCISDClick.batchBind({"#app_mod_blog h4 a[rel=blog-detail-link]":"Title","#app_mod_blog .list_tit a[rel=blog-detail-link]":"Title","#app_mod_blog .mod_summary .img_show a[rel=blog-detail-link]":"Summarymode.Photo","#app_mod_blog .mod_summary .mod_video":"Summarymode.video",
"#app_mod_blog a[rel=blog-right-setting-link]":"Listmode.Permissions","#calendarArea a":"Category.Date","#importArea a":"ImportBlog","#auditHref a":"Audit","#blog_search_btn":"soso.Search","#order-by-sel":"Sort","#searchArea .mod_links a":"soso.tag","a[rel=ugc-blog-submit]":"Ugc.SubmitButton",".options a[rel=ugc-blog-edit]":"Ugc.OptionEditButton",".img_show a[rel=ugc-blog-edit]":"Ugc.ImageEditButton","a[rel=ugc-blog-delete]":"Ugc.DeleteButton","h4 a[rel=ugc-blog-edit]":"Ugc.TitleEdit","#acceptUgcTips":"shezhi.jieshou",
"#acceptUgcTipsLabel":"shezhi.jieshou","#denyUgcTips":"shezhi.bujieshou","#denyUgcTipsLabel":"shezhi.bujieshou"},{url:"/BlogList",prepare:true,eventType:"mousedown"});QZBlog.Logic.TCISDClick.batchBind({"a[static=button1]":"tj1","a[static=button2]":"tj2","a[static=button3]":"tj3","a[static=button4]":"tj4"},{url:"isd.qzonemall.blog",prepare:true,eventType:"mousedown",domain:"mall.qzone.qq.com"})}};BlogList.TCISD.init()})(BlogList,window);
(function(BlogList,window,undefined){BlogList.Search={placeholder_str:"\u8bf7\u8f93\u5165\u5173\u952e\u5b57",search:function(val){if(typeof val=="undefined"){val=this.blog_search_text.value.trim();if(val==""||val==this.placeholder_str){this.blog_search_text.value=this.placeholder_str;this.blog_search_text.focus();return}}try{setTimeout(function(){QZONE.FP.Search(val,{entryid:64,type:"blog",appname:"\u65e5\u5fd7",backurl:"/blog"})},10)}catch(ex){}},initSearchInput:function(){this.blog_search_text=
QZFL.dom.get("blog_search_text");this.blog_search_btn=QZFL.dom.get("blog_search_btn");this.blog_search_text.value=this.placeholder_str;QZFL.event.addEvent(this.blog_search_text,"focus",QZFL.event.bind(this,function(){if(this.blog_search_text.value==this.placeholder_str){this.blog_search_text.value="";QZFL.css.removeClassName(this.blog_search_text,"c_tx3")}QZFL.css.updateClassName(this.blog_search_text.parentNode,"bor2 bg","textinput_focus")}));QZFL.event.addEvent(this.blog_search_text,"blur",QZFL.event.bind(this,
function(){if(this.blog_search_text.value.trim()==""){this.blog_search_text.value=this.placeholder_str;QZFL.css.addClassName(this.blog_search_text,"c_tx3")}QZFL.css.updateClassName(this.blog_search_text.parentNode,"textinput_focus","bor2 bg")}));QZFL.event.addEvent(this.blog_search_text,"keydown",QZFL.event.bind(this,function(e){var _code=e.keyCode;if(_code==13)this.search()}));QZFL.event.addEvent(this.blog_search_btn,"click",QZFL.event.bind(this,function(){this.search();QZFL.event.preventDefault();
return false}))},show:function(oTagList){var data={};data.vipClass=QZBlog.Logic.SpaceHostInfo.isVipUser()?"":"none";data.ownerClass=QZBlog.Logic.SpaceHostInfo.isOwnerMode()?"":"none";data.ItemList=typeof oTagList!="undefined"?oTagList:[];$("searchArea").innerHTML=tmpl(this._templateHTML,{"data":data});$("searchArea").style.display="";this.initSearchInput()},init:function(){var _this=this;if(typeof _this._templateHTML!="undefined")return;_this._templateHTML=$("searchTemplate").innerHTML;this.show();
BlogListReporter.markPoint(10)}};QZONE.FP.getSecondaryBitMapFlag(function(a,b){if(b)return;BlogList.Search.init()},25,null,QZBlog.Logic.SpaceHostInfo.getUin())})(BlogList,window);
(function(BlogList,window,undefined){BlogList.ShortCut={init:function(){this.bindShortcut()},_addKeyEvent:function(el,keyMap,fn,evType){evType=evType||"keydown";var ks=keyMap.split("+");var kmo={ctrl:false,alt:false,shift:false};QZFL.object.each(ks,function(k){k=k.toLowerCase();if(k=="ctrl"||k=="alt"||k=="shift")kmo[k]=true;else if(k=="enter")kmo.keyCode==13;else if(parseInt(k,10)>10)kmo.keyCode=parseInt(k,10);else kmo.keyCode=k.toUpperCase().charCodeAt(0)});QZFL.event.addEvent(el,evType,function(ev){var evTag=
QZFL.event.getTarget();if(kmo.ctrl!=ev.ctrlKey||kmo.shift!=ev.shiftKey||kmo.alt!=ev.altKey||evTag.tagName=="INPUT"||evTag.tagName=="BUTTON")return;if(kmo.keyCode==ev.keyCode){QZBlog.Logic.TCISDClick("useshortcut."+keyMap.replace("+","_"),"/BlogList");var result=fn(ev);if(result===false){QZFL.event.preventDefault();return false}}})},bindShortcut:function(){var _this=this;var _getBlogLinkList=function(){var listArea=$("listArea");if(!listArea||listArea.offsetHeight===0||listArea.offsetWidth===0||listArea.style.display==
"none")return[];var lis=listArea.getElementsByTagName("LI");var as=[];for(var i=0;i<lis.length;i++){var a=lis[i].getElementsByTagName("A")[0];if(a&&a.rel=="blog-detail-link"&&a.getAttribute("blogid"))as.push(a)}if(!as.length)return[];var nextPageLink=$e("a:last",$("pagination")).elements[0];if(nextPageLink)as.push(nextPageLink);return as};var evs={"p":function(){var as=_getBlogLinkList();if(!as.length)return;var currentNode=null;if(_this.lastNTag)for(var i=0;i<as.length;i++)if(as[i]==_this.lastNTag){currentNode=
i>0?as[i-1]:null;break}if(!currentNode)currentNode=as[as.length-1];_this.lastNTag=currentNode;currentNode.focus()},"n":function(){var as=_getBlogLinkList();if(!as.length)return;var currentNode=null;if(_this.lastNTag)for(var i=0;i<as.length;i++)if(as[i]==_this.lastNTag){currentNode=as[i+1]||null;break}if(!currentNode)currentNode=as[0];_this.lastNTag=currentNode;currentNode.focus()},188:function(){var listArea=$("listArea");if(!listArea||listArea.offsetHeight===0||listArea.offsetWidth===0||listArea.style.display==
"none")return;if(BlogList.currentFilter.page>1)BlogList.showPage({page:BlogList.currentFilter.page-1})},190:function(){var listArea=$("listArea");if(!listArea||listArea.offsetHeight===0||listArea.offsetWidth===0||listArea.style.display=="none")return;BlogList.showPage({page:BlogList.currentFilter.page+1})}};for(var ks in evs)this._addKeyEvent(document,ks,evs[ks]);if(BlogList.isOwner){if($("batchEditHref"))$("batchEditHref").title="\u6279\u91cf\u7ba1\u7406[ctrl+a]";$e("a[rel=write-blog-link]").each(function(a){a.title=
"\u5199\u65e5\u5fd7[alt+1]"});$e("a[rel=write-templateblog-link]").each(function(a){a.title="\u5199\u6a21\u677f\u65e5\u5fd7[alt+2]"});$e("a[rel=write-gridblog-link]").each(function(a){a.title="\u5199\u9b54\u65b9\u65e5\u5fd7[alt+3]"});var evs2={"alt+1":function(){PAGE_CACHE.clean();BlogList.jumpToUrl(QZBlog.Util.getEditBlogUrl()+"?opener=refererurl&source=1&refererurl="+encodeURIComponent(location.href))},"alt+2":function(){PAGE_CACHE.clean();var p={"refererurl":location.href,"directJumpIn":1,"source":2};
BlogList.jumpToUrl(QZBlog.Util.getEditTemplateBlogUrl(p));return},"alt+3":function(){PAGE_CACHE.clean();BlogList.jumpToUrl(QZBlog.Util.getEditGridBlogUrl({"refererurl":location.href},3))},"ctrl+1":function(){BlogList.switchToBlogList()},"ctrl+2":function(){BlogList.Manager.lazyLoad("bloglist.privateblog.js","BlogList.PrivateBlog",function(){PAGE_ROUTER.clean().set("catalog","private")})},"ctrl+3":function(){BlogList.Manager.lazyLoad("bloglist.ugcblog.js","BlogList.UgcBlog",function(){PAGE_ROUTER.clean().set("catalog",
"ugc")})},"ctrl+4":function(){QZBlog.Util.Statistic.sendPV("notepad_click","rizhi.qzone.qq.com");try{parent.BlogListNavigator.setCurrentDate()}catch(ex){}BlogList.jumpToUrl("/qzone/newblog/v5/notepad/notepad.html")},"ctrl+a":function(){var batchBtn=$("batchEditHref");if(!batchBtn||batchBtn.offsetWidth===0&&batchBtn.offsetHeight===0||batchBtn.style.display=="none")return;if(BlogList.Manager.isBatchView){var selBtn=$e("*[rel=batch-check-all]").elements[0];var _checked=!selBtn.checked;selBtn.checked=
_checked;$e("#page-container-blog input[rel=batch-blog-select]").each(function(chk){chk.checked=_checked})}else{var magBtn=$e("*[rel=switch-batch-mode]").elements[0];BlogList.Manager.toggleBatchView(magBtn)}return false},46:function(){},46:function(){}};for(var ks in evs2)this._addKeyEvent(document,ks,evs2[ks]);if(!getParameter("nocontext")){QZFL.event.addEvent(document.body,"contextmenu",function(ev){var tag=QZFL.event.getTarget(ev);var mouseX=QZFL.event.mouseX(ev);var mouseY=QZFL.event.mouseY(ev);
if(QZFL.dom.isAncestor($("listArea"),tag)&&tag.getAttribute("rel")=="blog-detail-link"&&tag.parentNode.tagName=="A"&&tag.tagName!="IMG"){_this.toggleBlogOptionMenu(tag.getAttribute("blogid"),mouseX,mouseY);QZFL.event.preventDefault();return false}else _this.toggleBlogOptionMenu()});QZFL.event.addEvent(document.body,"click",function(){_this.toggleBlogOptionMenu()})}}},toggleBlogOptionMenu:function(blogid,mouseX,mouseY){if(!this.blogOptionMenu){var HIDE_IN_PENGYOU=QZBlog.Logic.isInPengyou?"display:none":
"";this.blogOptionMenu=document.createElement("DIV");QZFL.css.insertStyleSheet(null,".op_more_mouse li a {text-align:left; padding-left:8px;}");document.body.appendChild(this.blogOptionMenu);this.blogOptionMenu.className="op_more op_more_mouse";this.blogOptionMenu.innerHTML=['<ul class="bor2 bg">','<li><a href="javascript:;" rel="blog-edit-link" title="\u7f16\u8f91\u65e5\u5fd7" class="bg3_hover">\u7f16\u8f91</a></li>','<li><a href="javascript:;" rel="blog-delete-link" title="\u5220\u9664\u8be5\u65e5\u5fd7" class="bg3_hover">\u5220\u9664\u65e5\u5fd7</a></li>',
'<li style="',HIDE_IN_PENGYOU,'"><a href="javascript:;" rel="blog-right-setting-link" title="\u65e5\u5fd7\u6743\u9650\u8bbe\u7f6e" class="bg3_hover">\u8bbe\u7f6e\u6743\u9650</a></li>','<li><a href="javascript:;" rel="blog-category-modify-link" title="\u4fee\u6539\u65e5\u5fd7\u5206\u7c7b" class="bg3_hover">\u4fee\u6539\u5206\u7c7b</a></li>','<li style="',HIDE_IN_PENGYOU,'"><a href="javascript:;" rel="blog-set-top-link" title="\u8bbe\u7f6e\u8be5\u65e5\u5fd7\u7f6e\u9876" class="bg3_hover">\u8bbe\u4e3a\u7f6e\u9876</a></li>',
'<li><a href="javascript:;" rel="blog-convert-private-link" title="\u8f6c\u4e3a\u79c1\u5bc6\u65e5\u5fd7" class="bg3_hover">\u8f6c\u4e3a\u79c1\u5bc6\u65e5\u5fd7</a></li>',"</ul>"].join("");QZFL.event.addEvent(this.blogOptionMenu,"click",function(){QZBlog.Logic.TCISDClick("contextmenu.click","/BlogList")})}this.blogOptionMenu.style.display=blogid?"":"none";if(blogid){QZBlog.Logic.TCISDClick("contextmenu.show","/BlogList");$e("a",this.blogOptionMenu).each(function(link){link.setAttribute("blogid",blogid)});
var bloginfo=BlogList.getBlog(blogid);$e("a[rel=blog-set-top-link]",this.blogOptionMenu).setHtml(bloginfo.getTopFlag()?"\u53d6\u6d88\u7f6e\u9876":"\u8bbe\u4e3a\u7f6e\u9876");if(bloginfo.getEffectBit(52))$e("a[rel=blog-convert-private-link]",this.blogOptionMenu).each(function(a){a.parentNode.style.display="none"});else $e("a[rel=blog-convert-private-link]",this.blogOptionMenu).each(function(a){a.parentNode.style.display=""});QZFL.dom.setStyle(this.blogOptionMenu,{left:mouseX,top:mouseY})}}};BlogList.ShortCut.init()})(window.BlogList,
window);BlogListReporter.markPoint(11);
/*  |xGv00|a3fa520f8ffc87ae8d4ed331300b36cc */