
window.requirejSolution||(window.defineRequirejSolution=function(){var base=window.g_Parent||parent;var map={76:1,20:2,74:3};var exp=base.QZONE.FrontPage.isAlphaUser(true)&&(!base.ua.ie||base.ua.ie>8)?2:(base.location.search!='?debug'&&map[base.g_iLoginUin%100]||0);var stamp={0:20130809,1:20130809,2:20130809,3:20130809};var url=['http://',base.siDomain||'qzonestyle.gtimg.cn','/qzone/app/jSolution/jSolution_1.0_qzone',exp?'_exp_'+exp:'','.js?max_age=31536000&ver=',stamp[exp]].join('');var callbacks=[];var onReady=function(){jSolution('1.0',function(j$){if(callbacks){for(var i=0,j=callbacks.length;i<j;i++){callbacks[i](j$);}
window.requirejSolution=function(callback){callback(j$);callback=null;};url=callbacks=onReady=null;}});};window.requirejSolution=function(callback){callbacks.push(callback);callback=null;if(window.jSolution){onReady();return;}
if(callbacks.length<=1){QZFL.imports([url],onReady);}};window.requirejSolution_url=url;})();/*  |xGv00|20b26fe399d750e07a2c5e85af22822a */(function(){var t=window;try{do{t=t.parent;if(t.QZONE&&(t.QZONE.FrontPage&&t.g_iUin))break}while(t!=top)}catch(ex){}if(typeof siDomain=="undefined")siDomain=t.siDomain||"qzonestyle.gtimg.cn";g_V=t.g_V||{};g_V.jq=g_V.jq||"1.9.1";g_V.req=g_V.req||"0.0.9";window.g_cdn_proto=t.g_cdn_proto||"";window.g_proto=t.g_proto||""})();
window.seajs&&seajs.config({charset:"utf-8",timeout:5*60*1E3,debug:0,paths:{"v8":(window.g_cdn_proto||window.location.protocol)+"//"+siDomain+"/qzone/v8","photo.v7":(window.g_cdn_proto||window.location.protocol)+"//"+siDomain+"/qzone/photo/v7/js","cssBase":(window.g_cdn_proto||window.location.protocol)+"//"+siDomain,"app":(window.g_cdn_proto||window.location.protocol)+"//"+siDomain+"/qzone/app","qzact":(window.g_cdn_proto||window.location.protocol)+"//"+siDomain+"/qzone/qzact","mall.v8":(window.g_cdn_proto||
window.location.protocol)+"//"+siDomain+"/qzone/mall/v8"},alias:{"jquery":(window.g_cdn_proto||window.location.protocol)+"//"+siDomain+"/ac/lib/jquery/jquery-"+g_V.jq,"migrate-plugin":"v8/engine/migrate-plugin.js","interface":"v8/core/interface_mini.js","app_engine":"v8/core/app_engine"+(window.g_diffModules&&g_diffModules.engine?g_diffModules.engine:"")+".js?max_age=72000","changelog_data":(window.g_cdn_proto||window.location.protocol)+"//"+siDomain+"/qzone/v6/v6_config/changelog_data.js","console-plus":"v8/engine/console-plus/console-plus.js",
"embeded":"/applib/embeded.js","request":"v8/engine/request/request_"+g_V.req},map:[[/^.+\/lib\/jquery\.js$/,(window.g_cdn_proto||window.location.protocol)+"//"+siDomain+"/ac/lib/jquery/jquery-"+g_V.jq+".js"]],comboSyntax:["c/=",","],comboIncludes:/\/qzone\/v8/,comboExcludes:/jquery|app_engine|music|qzone\/v8\/index\/msgboard/,preload:window.isIframe?["jquery","migrate-plugin","console-plus","request"]:["jquery","migrate-plugin","interface","console-plus","app_engine","request"]});
window.seajs&&seajs.on("resolve",function(data){if((location.protocol==="https:"||window.g_cdn_proto==="https:")&&(data&&(data.id&&(data.refUri&&data.id.indexOf("http://")===0))))data.id=data.id.replace("http://","https://")});

define('tcisd',null,function(require,exports,module){var env=require('app/v8/env/1.0');return env.base.TCISD;});/*  |xGv00|b5a28b2352d4edc95fb47e1acee930e8 */
var throttle=function(fn,context,delay){var timer=null;return function(){var args=arguments;clearTimeout(timer);setTimeout(function(){fn.apply(context,args);},delay||100);};};MOOD.interface={callExt:function(fnName,args){var t=this;if(!QZFL.lang.isArray(args)){args=[args];}
seajs.use('app/mood_v6/script/msglist_ext',function(MsgListExt){throttle(function(){MsgListExt[fnName].apply(t,args);},MsgListExt,200)();});}};QZFL.object.extend(MOOD.util,{goProfile:function(uin,platform){if(uin){switch(platform+''){case'3':var url='http://rc.qzone.qq.com/myhome/weibo/profile/'+uin;window.open(url,'_blank');break;case'1':default:if(uin.length>30){var url='http://www.pengyou.com/index.php?mod=profile&u='+uin+'&adtag=from_profile';window.open(url,'_blank');}else{var url='index.html?tab=mine'+(uin?'&uin='+uin:'');MOOD.util.go(url);}
break;}}else{var url='index.html?tab=mine';MOOD.util.go(url);}},showMention:function(content,tid){var api='http://'+siDomain+'/qzone/app/mood_v6/api/api.js';QZFL.imports(api,function(){var content_html=QZFL.FP.removeUBB(escHTML(content));var mentionPattern=/(?:@\{uin:([^\}]*),nick:([^\},]*)(?:,who:(\d+))?\})|[^@]+/g;content_html=content_html.replace(mentionPattern,function($0,uin,nick,platform){if(uin){var mention=new MOOD.api.user({nickname:restXHTML(nick||uin),uin:uin,who:platform||1});return mention.getProfileLink();}
return $0;});var node=$e('.new_comment_content_'+tid)
node.setHtml(content_html);});},getDateStr:function(time,format){var date,year,month,day,hour,minute,second;format=format||"YY-mm-dd";date=time?new Date(time*1000):new Date();year=date.getFullYear();month=date.getMonth()+1;day=date.getDate();hour=date.getHours();minute=date.getMinutes();second=date.getSeconds();var dateStr=format.replace('YY',year).replace('mm',month).replace('dd',day).replace('H',hour).replace('i',minute).replace('s',second);return dateStr;},friendlyTime:function(time){var date=new Date(time*1000);return timeFormatString(date);},voiceFix:function(voice){return voice?'none':'';}});MOOD.event={init:function(){QZFL.event.addEvent(document.body,'click',MOOD.event.clickProxy);},clickProxy:function(e){var target=QZFL.event.getTarget(e);QZFL.dom.searchChain(target,'parentNode',function(el){if(el==window.document){return false;}
el=$e(el);if(el.hasClass('goProfile')){MOOD.sendEvent('goProfile');MOOD.util.goProfile(el.getAttr('profileUin'),el.getAttr('profilePft'));}
if(el.hasClass('goDetail')){var itemElement=MOOD.lastComment.getItemElement(el);if(!itemElement)return;var tid=$e(itemElement).getAttr('tid');mood=MOOD.DataStorage.get(tid);if(!mood||!mood.data){return;}
MOOD.util.go('index.html?ref='+location.pathname+'&_tid='+mood.data.tid,{uin:mood.data.uin,tid:mood.data.tid,source:mood.data.t1_source});}
if(el.hasClass('goSearch')){MOOD.sendEvent('goSearch');setTimeout(function(){MOOD.topic.search(el.getAttr('keyword'));},100);return false;}
if(el.hasClass('last_comment_button')){MOOD.lastComment.popupComment(el);return true;}
if(el.hasClass('last_retweet_button')){MOOD.lastComment.popupRetweet(el);return true;}
if(el.hasClass('mod-hot-change')){MOOD.sendHotClick('/hottopic_change');t.refreshHotWords();QZFL.event.preventDefault(el);return true;}
if(el.hasClass('topic_op_link')){var li=QZFL.dom.searchElementByClassName(target,"topic_item");t.dolike(li);QZFL.event.preventDefault(el);return true;}
if(el.hasClass('ico_weibo')){MOOD.sendEvent('guideToWeibo');}
if(el.hasClass('ico_qzone')){MOOD.sendEvent('guideToQZone');}
if(el.hasClass('go_home')){MOOD.sendEvent('go_home');}});}};MOOD.widget={loadPager:function(cb){window.F4A=window.F4A||{};QZFL.imports('http://'+QZONE.FP._t.siDomain+'/qzone/app/controls/pager/pager.js',cb);}};MOOD.poster={makeFakeFeed:function(feedData,poster){var mentionPattern=/(?:@\{uin:([\w-_]+),nick:([^\},]*)(?:,who:(\d+))?\})/;QZFL.console.print('new feed tid:'+feedData.t1_tid);if(poster.skipMsgbox){poster.skipMsgbox=false;}else if(feedData.secret&&mentionPattern.test(feedData.content)){QZONE.FP.showMsgbox('私密说说发表成功！该条说说仅自己可见，被提及的用户不能收到提醒！',4,3000);}else{QZONE.FP.showMsgbox('发表成功',4,2000);}
if(poster.skipMakeFeed){poster.skipMakeFeed=false;}else{feedData.uin=feedData.t1_uin;feedData.t1_name=feedData.t1_uin;feedData.name=feedData.t1_name==feedData.t1_uin?QZONE.FP.getNickname():feedData.t1_name;feedData.createTime=feedData.t1_time;feedData.tid=feedData.t1_tid;feedData.source_name=feedData.t1_source_name;feedData.source_url=feedData.t1_source_url;feedData.certified=feedData.auth_flag||0;MOOD.updateFeeds(feedData);t.loadVisiableItems();}
feedData.secret&&MOOD.sendEvent('publish_private_mood');},init:function(container){var poster;var self=this;qzlog.info({cm:"MOOD_APP",cf:"init MoodPoster START"});seajs.use('app/v8/config/1.0',function(){seajs.use(['app/v8/controls/mood_poster/1.0','app/v8/utils/monitor/1.0','app/v8/controls/mood_poster/mood_editor_config/1.0'],function(MoodPoster,monitor,MoodEditorConfig){poster=MoodPoster.create({needSideBar:true,needSyncQQ:true,needSyncWeibo:false,needSyncSetting:true,needAuthorizeSetting:true,needTimerSetting:true,pluginConfig:{basicPlugins:MoodEditorConfig.BASIC_PLUGINS,imagePlugins:MoodEditorConfig.IMAGE_PLUGINS,funnyPlugins:MoodEditorConfig.FUNNY_PLUGINS,otherPlugins:MoodEditorConfig.OTHER_PLUGINS},resourceContainerConfig:{image:{needTypeset:true,needDnd:true,needOp:true,addImageEntry:{local:true,album:true,screenCapture:true,meitu:true}}}});poster.renderOn(document.getElementById('QM_Mood_Poster_Container'));MOOD.poster=poster;poster.addListener('onTemplateMoodPostSuccess',function(d){self.makeFakeFeed(d,poster);});poster.addListener('onPluginPostSuccess',function(d){self.makeFakeFeed(d,poster);});poster.addListener('onPostSuccess',function(d){self.makeFakeFeed(d,poster);});try{if(top.location.href.indexOf('auto_show_funny')>-1){poster.onReady(function(){this.getUpupPoster(function(upup){upup.show();upup.onFlashReady(function(){this.setInitialContent('');});this.hide();});});monitor.pv('taotaoact.qzone.qq.com','/mood_poster/auto_show_funny');return;}
if(top.location.href.indexOf('poster=emoticon/avatar')>-1){poster.onReady(function(){poster.getMoodEditor().initPlugins();poster.getMoodEditor().getFuncAttachBar(function(funcAttachBar){if(funcAttachBar){funcAttachBar.callByPath('tabItems.emoticon.tabButton.onClick');}});});monitor.pv('taotaoact.qzone.qq.com','/mood_poster/auto_show_avatar');return;}
if(top.location.href.indexOf('auto_show_bubble')>-1){poster.onReady(function(){poster.callByPath('moodEditor.loadPlugins',{'template':{version:'2.0',enable:true}},{onSuccess:function(){this.fireEvent('TEMPLATE_BTN_CLICKED');}});});monitor.pv('taotaoact.qzone.qq.com','/mood_poster/auto_show_bubble');}
if(top.location.href.indexOf('auto_show_qutu')>-1){poster.onReady(function(){poster.callByPath('moodEditor.loadPlugins',{'qutu':{version:'1.0',enable:true}},{onSuccess:function(){var editor=this;editor.addEvent('MOOD_POSTER_QUTU_PLUGIN_READY',function(){editor.fireEvent('QUTU_BTN_CLICKED');});}});});monitor.pv('taotaoact.qzone.qq.com','/mood_poster/auto_show_qutu');}
if(top.location.href.indexOf('auto_show_flash_img')>-1){poster.onReady(function(){poster.callByPath('moodEditor.loadPlugins',{'flare_font':{version:'1.0',enable:true}},{onSuccess:function(){var editor=this;editor.addEvent('MOOD_POSTER_FLARE_FONT_PLUGIN_READY',function(){editor.fireEvent('FLARE_FONT_BTN_CLICKED');});}});});}}catch(e){monitor.pv('taotaoact.qzone.qq.com','/mood_poster/auto_show_error');}
qzlog.info({cm:"MOOD_APP",cf:"init MoodPoster FINISHED"});});});}};MOOD.lastComment={itemElement:null,getItemElement:function(e){var target=QZFL.event.getTarget(e);var itemElement=null;QZFL.dom.searchChain(target,'parentNode',function(el){if(el==window.document){return false;}
if(QZFL.css.hasClassName(el,'comment_feed')&&el.tagName=='LI'){itemElement=el;return true;}});this.itemElement=itemElement;return itemElement;},getMoodData:function(el){var itemElement=this.getItemElement(el);var tid=$e(itemElement).getAttr('tid');var mood=MOOD.DataStorage.get(tid);return mood&&mood.data;},dataMap:function(tid){var items=t.l.msglist;for(var i=0;i<items.length;i++){var item=items[i];if(item.tid==tid){return item;}}},popup:function(mood,type){var here=this;var cpn_src=['http://'+siDomain+'/qzone/app/mood_v6/plugin/CRPopupModel.js','http://'+siDomain+'/qzone/app/jSolution/jSolution_1.0_qzone.js'];with(QZONE.FP._t){QZFL.imports(cpn_src,function(){var popupModule=new CRPopupModel({type:type,item:{uin:mood.uin,tid:mood.tid},onPosted:function(flag){here.countAll(flag);}});});}},popupComment:function(el){var mood=this.getMoodData(el);this.popup(mood,1);MOOD.sendEvent('popup_newest_comment');},popupRetweet:function(el){var mood=this.getMoodData(el);this.popup(mood,2);MOOD.sendEvent('popup_newest_retweet');},countOne:function(type){var el=$e(this.itemElement);var node=el.find('.'+type+'_num');var num=parseInt(node.getHtml());node.setHtml(++num);},countAll:function(flag){var self=this;for(var i=0;i<flag.length;i++){self.countOne(flag[i]);}}};(function(){MOOD.mapTips={show:function(el,posx,posy){if(t.popupId){t.hide();}
var html=['<iframe id="checkinframe" src="http://',QZONE.FP._t.imgcacheDomain,'/qzone/app/controls/map/tips.html#posx=',posx,'&posy=',posy,'" allowtransparency frameborder="0" scrolling="no" style="width:300px;height:200px;"></iframe>'].join('');var opts={timeout:-1,backgroundColor:(!QZONE.FP._t.g_OFPLite?'#FFFDF4':'#F5F6F6'),contentPadding:1,noQueue:true,id:'TipsPopup',arrowPoint:1,arrowEdge:1,closeButtonSize:14,closeButtonColor:'red',width:302,height:202,x:-14,y:3};var s1=QZFL.dom.getXY(frameElement.parentNode);var s2=QZFL.dom.getXY(el);var height=QZONE.FP._t.QZFL.dom.getClientHeight();if(s1[1]+s2[1]+220>height+QZONE.FP.getScrollTop()){opts.arrowPoint=4;opts.arrowEdge=3;}
t.popupId=QZFL.widget.tips.show(html,el,opts);setTimeout(function(){QZFL.event.addEvent(document.body,'click',t.hide);},100);},hide:function(){var o=QZFL.widget.tips.instances[t.popupId];QZFL.widget.tips.close(o);QZFL.event.removeEvent(document.body,'click',t.hide);t.popupId=null;}};var t=MOOD.mapTips;})();QZFL.object.extend(MOOD.util,{Forward:function(fwinfo){QZFL.imports("http://"+siDomain+'/qzone/app/controls/forwardingBox/forwardingBoxFacade.js',function(){QZONE.ICFeeds.App.ForwardingBox.bootstrap('',fwinfo);MOOD.sendEvent('retweet');},{charset:'utf-8'});}});MOOD.sendPV=function(path){if(path){setTimeout(function(){var dm='taotao.qzone.qq.com';var url=path;if(document.domain=='pengyou.com'){dm='xiaoyou.qq.com';switch(path){case'title':url='index/twitterv2.php';break;case'mytitle':url='index/twitterv2.php';if(QZONE.PY&&QZONE.PY.hasLeftBar){if(QZONE.PY.hasLeftBar()){url='index/twitterv2/tab.php';}}
break;case'guesttitle':url='index/twitterv2/tab.php';break;case'detail':url='index/twitterv2/detail.php';break;case'setting':url='index/twitterv2/setting.php';break;default:url=path;}}
var tc=QZONE.FP.getStatPackage();tc.pv(dm,'/'+url);},0);}};MOOD.TCISDClick=function(tag,url,domain){url=url||'/';domain=domain||"taotaoact.qzone.qq.com";window.console&&console.log('TCISD:',tag,url,domain);try{QZONE.FP._t.TCISD.hotClick(tag,domain,url);}catch(ex){};};MOOD.TCISDClick.batchBind=function(tagHash,option){option=QZFL.object.extend({'eventType':'mousedown','url':null,'domain':null,'container':document},(option||{}));var map={};QZFL.each(tagHash,function(statName,tag){map[tag]=function(){MOOD.TCISDClick(statName,option.url,option.domain);};});MOOD.batchDelegate(map,option.container,option.eventType,true);}
MOOD.batchDelegate=(function(){var _hasLink=function(tag){return tag&&tag.tagName=='A'&&(tag.href||'').indexOf('http://')==0;};var _getTopLayer=function(tag,selector){var n;$e(selector).each(function(item){if(!n&&(item==tag||QZFL.dom.isAncestor(item,tag))){n=item;return false;}});return n;}
return function(map,context,eventType,defaultLinkAction){eventType=eventType||'click';context=context||document;QZFL.each(map,function(fn,selector){QZFL.event.delegate(context,selector,eventType,function(e){var btn=QZFL.event.getButton(e);var tag=QZFL.event.getTarget(e);tag=_getTopLayer(tag,selector);if(tag){if(eventType=='click'&&btn!=0&&_hasLink(tag)){}else{fn(tag);if(tag.tagName=='A'&&!defaultLinkAction){QZFL.event.preventDefault(e);}}}});});};})();MOOD.sendEvent=function(path){if(path){path=path+'/v'+MOOD.version;setTimeout(function(){var tc=QZONE.FP.getStatPackage();tc.pv('taotaoact.qzone.qq.com','/'+path);},0);}};MOOD.sendHotClick=function(path){if(path){setTimeout(function(){var tc=QZONE.FP.getStatPackage();tc.hotClick(path,'taotaoact.qzone.qq.com');},0);}};MOOD.pageStart=function(cb){cb();MOOD.event.init();};var mood=mood||{};mood.jumpPage=MOOD.jumpPage=function(uin,platform){MOOD.sendEvent('clickname');MOOD.util.goProfile(uin,platform);};MOOD.jumpToAudit=function(){window.open('http://user.qzone.qq.com/'+QZONE.FP.getQzoneConfig('loginUin')+'/mood/jumpToAudit','_blank');};MOOD.resizeImage=function(obj,maxW,maxH){if(obj.loaded==true)return;obj.loaded=true;var _img=new Image();_img.onload=function(){if(_img.width>maxW){obj.width=maxW;obj.style.width=maxW+'px';obj.style.height='auto';}else{obj.width=_img.width;obj.style.width=_img.width+'px';obj.style.height='auto';}
obj.style.display='block';}
_img.src=obj.src;};MOOD.Music=MOOD.Music||{};MOOD.Music.getAlbumImage=function(albumId){albumId=albumId||0;if(albumId>0){return['//edu.qzs.qq.com/music/photo/album/',albumId%100,'/150_albumpic_',albumId,'_0.jpg'].join('');}
return'//music.qq.com/musicbox/img/uccpic_error.jpg';};MOOD.Setting=function(meta,field,value,onsuccess){var _item_list=['sign_sync_ss','ss_sync_sign','ss_sync_tweet','ss_sync_share','sync_view'];var data={},i,key;for(i=0;i<_item_list.length;i++){key=_item_list[i];data[key]=meta[key];}
data[field]=value;data['hostuin']=t.uin;var url=MOOD.domain.getUrl('signset');var post=new QZFL.FormSender(url,'post',data,'utf-8');post.onSuccess=function(d){MOOD.sendEvent('setting_submit_success');QZONE.FP.showMsgbox('设置成功',4,2000);if(onsuccess){onsuccess();}};post.onError=function(d){MOOD.sendEvent('setting_submit_faild');QZONE.FP.showMsgbox('服务器忙，请稍后重试。');};post.send();};(function(MOOD){'use strict';var cache={};var save=function(uin,source,domain){var key='o'+uin;if(source){key=key+'_'+source;}
return cache[key]=domain;};var get=function(uin,source){uin=uin||'';var key='o'+uin;if(source){key=key+'_'+source;}
if(cache[key]=='string'){return cache[key];}else{query_location(uin);}
return'taotao.qq.com';};var update=function(d,uin){d=d||{};d.result=d.result||{};var domain='taotao.qq.com';if(d.result.code==0){if(d.idcNo==1){domain='taotao.qq.com';}else if(d.idcNo==2){domain='sh.taotao.qq.com';}}else{d={idcNo:1,result:{code:0},uin:uin};}
d.uin=d.uin||uin;window.locationCache=window.locationCache||[];window.locationCache.push(d);save(uin,'',domain);};var query_location=function(uin){};var load=function(uin,source,cbFn){var uin=MOOD.util.getHttpParams('uin')||QZONE.FP.getQzoneConfig('ownerUin');update(window._locationCache||{},uin);};MOOD.domain={load:load,get:get};})(MOOD=MOOD||{});(function(){'use strict';var _um={'index':['emotion_cgi_get_mix_v6',0],'msglist':['emotion_cgi_msglist_v6',1],'timer':['emotion_cgi_timershuoshuolist_v6',0],'del_timer':['emotion_cgi_del_timershuoshuo_v6',0],'pubnow_timer':['emotion_cgi_pubnow_timershuoshuo_v6',0],'del':['emotion_cgi_delete_v6',0],'comment':['emotion_cgi_comment_v6',0],'delcomment':['emotion_cgi_delcomment_v6',0],'reply':['emotion_cgi_addreply_v6',0],'delreply':['emotion_cgi_delreply_v6',0],'forward':['emotion_cgi_forward_v6',0],'signset':['emotion_cgi_signset_v6',0],'setting':['emotion_cgi_setting_v6',0],'mutireplies':['emotion_cgi_mutireplies_v6',0],'multitopcomments':['emotion_cgi_multitopcomments_v6',0],'addtopcomment':['emotion_cgi_addtopcomment_v6',0],'getcomments':['emotion_cgi_getcomments_v6',0],'get_pics':['emotion_cgi_get_pics_v6',0]};MOOD.domain.getUrl=function(name,uin){var item=_um[name];var domain='taotao.qq.com';if(item[1]){domain=MOOD.domain.get(uin);}
return'http://'+domain+'/cgi-bin/'+item[0];}})();(function(){function getItemElement(target){var itemElement=null;QZFL.dom.searchChain(target,'parentNode',function(el){if(el==window.document){return false;}
if(QZFL.css.hasClassName(el,'feed')&&el.tagName=='LI'){itemElement=el;return true;}});return itemElement;}
function getAudioElement(target){var itemElement=null;QZFL.dom.searchChain(target,'parentNode',function(el){if(el==window.document){return false;}
if(QZFL.css.hasClassName(el,'qz_shuoshuo_audio')&&el.tagName=='DIV'){itemElement=el;return true;}});return itemElement;}
MOOD.MsgList=function(cfg){var t=this;QZFL.object.extend(t,{extUrl:'http://'+QZONE.FP._t.siDomain+'/qzone/app/mood_v6/script/msgListExt.js?max_age=600&r='+MOOD.version,callExt:MOOD.interface.callExt,container:''},cfg);t.el=$e($(t.container));t.clickProxy();t.mouseProxy();}
MOOD.MsgList.prototype={clickProxy:function(){var t=this;var isActive=false;t.el.bind('click',function(e){var target=QZFL.event.getTarget(e);var itemElement=getItemElement(target);var tid=$e(itemElement).getAttr('data-tid');var mood=MOOD.DataStorage.get(tid);if(!mood){return;}
var fired=false;QZFL.dom.searchChain(target,'parentNode',function(el){if(el==window.document){return false;}
if(fired){return true;}
if((target.tagName=='IMG'||target.tagName=='A')&&QZFL.css.hasClassName(el,'smallPic')){if(mood.data.timershuoshuo||document.domain=="pengyou.com"){t.callExt('showBigPic',[mood,itemElement]);}else{t.callExt('showSlideView',[mood,target]);}
fired=true;return true;}
if(QZFL.css.hasClassName(el,'see-all')){if(mood.data.appid==202){return true;}
t.callExt('showBigPic',[mood,itemElement]);fired=true;return true;}
if(QZFL.css.hasClassName(el,'passwrod_required')){t.callExt('passwrodRequired',[mood,itemElement]);fired=true;return true;}
if(QZFL.css.hasClassName(el,'apply_access')){t.callExt('applyAccess',[mood,itemElement]);fired=true;return true;}
if(QZFL.css.hasClassName(el,'edit_btn')){QZONE.FP.showMsgbox('加载中...',6,5000);t.callExt('edit',[mood,itemElement]);fired=true;return true;}
if(QZFL.css.hasClassName(el,'viewmap')){t.callExt('viewMap',[mood,itemElement]);fired=true;return true;}
if(QZFL.css.hasClassName(el,'js_play_record')){var element=getAudioElement(target);t.callExt('playRecord',[mood,itemElement,element]);fired=true;return true;}
if(target.tagName=='A'&&QZFL.css.hasClassName(el,'timer_del')){t.callExt('timer_del',[mood,itemElement]);fired=true;return true;}
if(target.tagName=='A'&&QZFL.css.hasClassName(el,'del')){t.callExt('del',[mood,itemElement]);fired=true;return true;}
if(target.tagName=='A'&&QZFL.css.hasClassName(el,'timer_send_now')){t.callExt('timer_send_now',[mood,itemElement]);fired=true;return true;}
if(target.tagName=='A'&&QZFL.css.hasClassName(el,'forward_btn')){t.callExt('showForward',[mood,target]);fired=true;return true;}
if(target.tagName=='A'&&QZFL.css.hasClassName(el,'comment_btn')){controller.initCommentModule(mood.data,function(commentModule){if(commentModule.isCommentBoxVisible())return;commentModule.show();commentModule.focus();});fired=true;return true;}
if(target.tagName=='A'&&QZFL.css.hasClassName(el,'qz_like_btn')){fired=true;return true;}
if(target.tagName=='A'&&QZFL.css.hasClassName(el,'rt_forward_btn')){t.callExt('rtShowForward',[mood,itemElement]);fired=true;return true;}
if(target.tagName=='A'&&QZFL.css.hasClassName(el,'rt_comment_btn')){t.callExt('rtShowComment',[mood,itemElement]);fired=true;return true;}
if(target.tagName=='A'&&QZFL.css.hasClassName(el,'report')){t.callExt('report',[mood,itemElement]);fired=true;}
if(QZFL.css.hasClassName(el,'smallVideo')){t.callExt('playVideo',[mood,itemElement]);fired=true;return true;}
if(QZFL.css.hasClassName(el,'js_play_audio')){t.callExt('playAudio',[mood,itemElement]);fired=true;return true;}
if(QZFL.css.hasClassName(el,'js_hide_audio')){t.callExt('stopAudio',[mood,itemElement]);fired=true;return true;}
if(QZFL.css.hasClassName(el,'goDetail')){QZFL.event.preventDefault(e);t.callExt('goDetail',[mood,itemElement,el]);fired=true;return false;}
if(QZFL.css.hasClassName(el,'smallVote')){t.callExt('showVote',[mood,itemElement,target]);fired=true;return true;}
if(QZFL.css.hasClassName(el,'smallAttach')){t.callExt('showAttach',[mood,itemElement]);fired=true;return true;}
if(QZFL.css.hasClassName(el,'js_collapse')){QZFL.event.preventDefault();t.callExt('collapse',[mood,itemElement]);fired=true;return true;}
if(QZFL.css.hasClassName(el,'to_public')){t.callExt('toPublic',[mood,itemElement]);fired=true;return true;}
if(QZFL.css.hasClassName(el,'has_more_con')){var active=QZFL.css.hasClassName(el,'more_active');t.callExt('showMoreContent',[mood,itemElement,1,active]);fired=true;return true;}
if(QZFL.css.hasClassName(el,'rt_has_more_con')){var active=QZFL.css.hasClassName(el,'more_active');t.callExt('showMoreContent',[mood,itemElement,2,active]);fired=true;return true;}});if(fired){QZFL.event.preventDefault();return false;}});function delegateHover(selector,handlerin,handlerout){var dom=$('msgList');QZFL.event.delegate(dom,selector,"mouseenter",function(evt){if(typeof handlerin=="function"){handlerin.call(this,evt,this);}});QZFL.event.delegate(dom,selector,"mouseleave",function(evt){if(typeof handlerout=="function"){handlerout.call(this,evt,this);}});}
delegateHover('.qz_shuoshuo_audio',function(evt,elem){QZFL.css.addClassName(elem,"bor_bg6");QZFL.css.removeClassName(elem,"bor2");},function(evt,elem){QZFL.css.addClassName(elem,"bor2");QZFL.css.removeClassName(elem,"bor_bg6");});},mouseProxy:function(){var msgListContainer=this.el.elements[0];seajs.use(['jquery','migrate-plugin'],function(jq,migratePlugin){jq(msgListContainer).on('mouseenter','.feed',function(e){jq(e.currentTarget).addClass('feed_hover').find('.mouseOver').show();}).on('mouseleave','.feed',function(e){jq(e.currentTarget).removeClass('feed_hover').find('.mouseOver').hide();});jq(document).on('mouseenter','.more-edit-items',function(e){jq(e.currentTarget).addClass('dropdown-open');}).on('mouseleave','.more-edit-items',function(e){jq(e.currentTarget).removeClass('dropdown-open');});jq(document).on('click','a[role=menuitem]',function(){jq('.more-edit-items').removeClass('dropdown-open');});jq(document).on('mouseenter','a[role=menuitem]',function(e){jq(e.currentTarget).addClass('bg2');}).on('mouseleave','a[role=menuitem]',function(e){jq(e.currentTarget).removeClass('bg2');});});}};})();(function(){var SHUOSHUOAD=2096;var Sponsors=function(cfg){var tmp_fn=function(){};this.config={IMG_LINK_TPL:'<a href="{link}" bosstrace="{bosstrace}" target="{target}" ><img src="{img}" bosstrace="{bosstrace}" url="{link}" alt="qboss_ad_image" /></a>',img_pid:'',img_container:null,img_onload:tmp_fn,text_pid:'',text_container:null,text_onload:tmp_fn,board_id:SHUOSHUOAD,support_multi:true};cfg=cfg||{};QZFL.object.extend(this.config,cfg);};Sponsors.prototype.addImgOnLoadListener=function(listener){if(typeof listener=='function'){this.config.img_onload=listener;}};Sponsors.prototype.addTextOnLoadListener=function(listener){if(typeof listener=='function'){this.config.text_onload=listener;}};Sponsors.prototype.show=function(){var _self=this;var img_callback=function(ret){var IMG_LINK_TPL=_self.config.IMG_LINK_TPL;var _pos=0,item,items=ret||[];if(items.length>0){_pos=Math.floor(Math.random()*items.length);items[_pos].objExtData=new Function('return'+items[_pos].extdata)();items[_pos].objExtData.bosstrace=items[_pos].bosstrace;items[_pos].objExtData.target=items[_pos].objExtData.link.indexOf('javascript')!=-1?'':'_blank';_self.config.img_container.innerHTML=format(IMG_LINK_TPL,items[_pos].objExtData);}
if(items.length>1&&_self.config.support_multi){var html=[];for(var i=0;i<items.length;i++){html.push('<span>&#9679;</span>');items[i].objExtData=new Function('return'+items[i].extdata)();items[i].objExtData.bosstrace=items[i].bosstrace;}
html.push('<div class="mask"></div>');$e('.pop_apps_wrap div.switcher').setHtml(html.join(''));function switcher(){$e('.pop_apps_wrap div.switcher span').each(function(el,i){if(i==_pos){$e(el).addClass('current');}else{$e(el).removeClass('current');}});}
switcher();setInterval(function(){_pos++;if(_pos>(items.length-1)){_pos=0;}
_self.config.img_container.innerHTML=format(IMG_LINK_TPL,items[_pos].objExtData);switcher();},5000);}else{$e('.pop_apps_wrap div.switcher').setHtml('');}
_self.config.img_onload();};var board_id=this.config.board_id;var data={uin:QZONE.FP.getQzoneConfig('loginUin'),board_id:board_id};var url='http://boss.qzone.qq.com/fcg-bin/fcg_get_strategy';var getAD=new QZFL.JSONGetter(url,null,data,'utf-8');getAD.onSuccess=function(d){d=d||{};if(d.code==0&&d.data[board_id]&&d.data[board_id].items.length>0){var resultItems=d.data[board_id].items;img_callback(resultItems);}}
getAD.send("_Callback");};window.Sponsors=Sponsors;var onImgClicked=function(e){var tar=QZFL.event.getTarget(e);if(tar){var bosstrace=tar.getAttribute('bosstrace')||"";var pgvImg=new Image();pgvImg.src="http://boss.qzone.qq.com/fcg-bin/fcg_rep_strategy?from=1&uin="+QZONE.FP.getQzoneConfig('loginUin')+"&qboper=2&bosstrace="+bosstrace;}}
var sconf={img_pid:'qzone_shuoshuo_img_1',img_container:$('qzone_shuoshuo_img_1'),img_onload:function(){$e('#pop_apps_sponsors').removeClass('none');$e('#pop_apps_split').removeClass('none');$e('#qzone_shuoshuo_img_1').onClick(onImgClicked);},text_pid:'qzone_shuoshuo_imgtxt_1',text_container:$('qzone_shuoshuo_imgtxt_1'),text_onload:function(){$e('#pop_apps_sponsors').removeClass('none');$e('#pop_apps_split').removeClass('none');}};var tempAd=new Sponsors(sconf);tempAd.show();var bconf={IMG_LINK_TPL:'<a href="{link}" target="{target}"><img src="{img}" bosstrace="{bosstrace}" url="" alt="qboss_ad_image"/></a>',img_container:$('bottom-sponsor'),board_id:2199,support_multi:false,img_onload:function(){$e('#bottom-sponsor').onClick(onImgClicked);}}
setTimeout(function(){var btAd=new Sponsors(bconf);btAd.show();},3000);})();MOOD.topic={updateCount:function(container,data){data=data||[];var i,l=data.length;var keys=[];for(i=0;i<l;i++){keys.push(data[i].likekey);}
var url='http://'+QZONE.FP._t.g_R_Domain+'/cgi-bin/qzonesoso/cgi_qzonesoso_showlike';var d={uin:QZONE.FP.getQzoneConfig('loginUin'),keys:keys.join(','),t:(new Date()).getTime()};if(l>0){var g=new QZFL.JSONGetter(url,null,d,'utf-8');g.onSuccess=function(d){var items=d.data||[];if(keys.length==items.length){for(var i=0,id;i<items.length;i++){id='#'+keys[i];$e(id).setHtml(items[i].count+items[i].liked);}}};g.send('callback');}},showHot:function(container){var self=this;var data={uin:QZONE.FP.getQzoneConfig('loginUin')};var url='http://r.qzone.qq.com/cgi-bin/qzonesoso/cgi_qzonesoso_hotword';var g=new QZFL.JSONGetter(url,null,data,'utf-8');g.onSuccess=function(d){if(d.ret==0&&d.data&&(d.data.resultdata=d.data.resultdata||[])){var html=tmpl(MOOD.tmp.hotTopic,{items:d.data.resultdata});$e($(container)).setHtml(html);self.updateCount(container,d.data.resultdata);}};g.send('callback');var sconf={img_pid:'qzone_shuoshuo_img_1',img_container:$('qzone_shuoshuo_img_1'),img_onload:function(){$e('#pop_apps_sponsors').removeClass('none');$e('#pop_apps_split').removeClass('none');},text_pid:'qzone_shuoshuo_imgtxt_1',text_container:$('qzone_shuoshuo_imgtxt_1'),text_onload:function(){$e('#pop_apps_sponsors').removeClass('none');$e('#pop_apps_split').removeClass('none');}};var s=new Sponsors(sconf);s.show();},search:function(keyword){var isQzone=document.domain=='qq.com';if(isQzone){QZONE.FP.Search(keyword,{type:'mood'});}else{var url='http://www.pengyou.com/index.php?mod=twitterv2&act=topic#key='+encodeURI(keyword);window.open(url);}
return false;}};function searchHot(el){var e=QZFL.event.getEvent();if(e.keyCode==13){QZONE.FP.sendPV('taotao.qzone.qq.com','search');MOOD.topic.search(el.value);}};$e('#hotkeysearch').onBlur(function(){if(this.value==''){this.value='搜索其他热门话题...';}});$e('#hotkeysearch').onFocus(function(){if(this.value=='搜索其他热门话题...'){this.value='';}})
$e('#hotkeysearch').onKeyPress(function(){searchHot(this)});$e('#hotkeysearchbtn').onClick(function(){QZONE.FP.sendPV('taotao.qzone.qq.com','search');MOOD.topic.search($('hotkeysearch').value);});window.MOOD=window.MOOD||{};window.QZONE=window.QZONE||{};QZONE.FP=QZONE.FP||parent.QZONE.FrontPage;parent.QZFL.object.map(parent.QZFL.string,window);parent.QZFL.object.map(parent.QZFL.util,window);parent.QZFL.object.map(parent.QZFL.lang,window);MOOD.tmp=MOOD.tmp||{};MOOD.util=MOOD.util||{};QZFL.object.extend(MOOD.util,{initLoader:function(loader){var callbacks=loader.callbacks;loader.onSuccess||(loader.onSuccess=function(){for(var callback;callback=callbacks.shift();){callback.apply(null,arguments);}});},loaders:{F4A:function(){var loader=arguments.callee;MOOD.util.initLoader(loader);if(window.F4A){loader.onSuccess();return;}
QZFL.imports('http://'+parent.siDomain+'/qzone/app/f4a/F4A_1.2.lite.js?max_age=600&ver=20120111',loader.onSuccess);},jSolution:function(){var loader=arguments.callee;MOOD.util.initLoader(loader);if(window.jSolution){loader.onSuccess();return;}
MOOD.util.require('F4A',function(){QZFL.imports('http://'+parent.siDomain+'/qzone/app/jSolution/jSolution_1.0_qzone.js',loader.onSuccess);});},attachmentThumbnail:function(){var loader=arguments.callee;MOOD.util.initLoader(loader);MOOD.util.require('jSolution',function(){jSolution['1.0'].load({resName:'ThumbnailFacade',nsName:'/controls/attachBar',nsVer:'3.0',onSuccess:loader.onSuccess});});}},require:function(id,onSuccess){var loader=MOOD.util.loaders[id];var callbacks=loader.callbacks||(loader.callbacks=[]);callbacks.push(onSuccess);loader();},getHttpParams:function(name){var r=new RegExp('(\\?|#|&)'+name+'=([^&#]*)(&|#|$)');var m=location.href.match(r);return decodeURIComponent(!m?'':m[2]).replace(/\+/g,' ');},go:function(link,hash){var url='';if(!link.match(/^http/)){url='http://'+parent.imgcacheDomain;if(!link.match(/^\//)){url+='/qzone/app/mood_v6/html/';}}
url+=link;if(hash){url+='#'+genHttpParamString(hash);}
try{window.location.href=url;}catch(e){frameElement.src=url;}},HTML:function(str){str=(str||'')+'';var mentionPattern=/(?:@\{uin:([^\}]*),nick:([^\},]*)(?:,who:(\d+))?\})|[^@]+/g;var metionDecodingMap={'%7D':'}','%2C':',','%25':'%'};var decodeMention=function(content){if(content){for(var i in metionDecodingMap){content=content.replace(i,metionDecodingMap[i]);}}
return content;}
var tags=str.split(/(#(?:.|<br\/>)+?#)/g);var _currentlen=0;var _content='',tag='',_tagcon,_mencon,_doneTag,_doneMention;for(var i=0;i<tags.length;i++){tag=tags[i];_doneTag=false;_tagcon='';_mencon='';_tagcon=tag.replace(/#((?:.|<br\/>)+?)#/g,function(a,b,c){_doneTag=true;var icon='';icon='<a href="http://rc.qzone.qq.com/qzonesoso/?search='+encodeURIComponent(b)+'" target="_blank">#'+escHTML(b)+'#</a>';return icon;});if(!_doneTag){_tagcon='';mentions=tag.split(/(@(?!^\{)[\{]uin\:[a-z\d]+\,nick\:[^}]*[\}])/g);for(var j=0;j<mentions.length;j++){mention=mentions[j];_doneMention=false;mention=mention.replace(mentionPattern,function($0,uin,nick,platform){nick=decodeMention(nick);if(uin){_doneMention=true;return format('@<a title="{uin}" target="_blank" href="http://user.qzone.qq.com/{uin}" class="c_tx">{name}</a>',{uin:uin,name:escHTML(nick)});}
return escHTML($0);});if(!_doneMention){mention=mention.replace(/((?:https|ftp|http):\/\/[-A-Z0-9+&@#\/%?=~_|!:,.;]*[-A-Z0-9+&@#\/%=~_|])/ig,'<a href=\"$1\" target=\"_blank\">$1</a>');}
_mencon=_mencon+mention;}
_tagcon=_mencon;}
_content=_content+_tagcon;}
return QZFL.FP.removeUBB(_content);},getContent:function(conList,oContent,tid,uin,certified,nosafecheck){var self=MOOD.util.getContent;self.tmpFn=self.tmpFn||tmpl(MOOD.tmp.content);return self.tmpFn({items:conList,tid:tid,uin:uin,certified:certified,nosafecheck:nosafecheck||0})||MOOD.util.HTML(oContent);},parseContent:function(s){s=(s||'')+'';var tags=s.split(/(#(?:.|<br\/>)+?#)/g);var _doneTag=false;var result='',content='';for(var i=0;i<tags.length;i++){tag=tags[i];_doneTag=false;result='';result=tag.replace(/#((?:.|<br\/>)+?)#/g,function(a,b,c){_doneTag=true;var html=QZONE.FP.removeUBB(QZONE.FP.replaceIconTag(escHTML(b)));var icon='<a href="http://rc.qzone.qq.com/qzonesoso/?search='+encodeURIComponent(b)+'" target="_blank">#'+html+'#</a>';return icon;});if(!_doneTag){result=QZONE.FP.removeUBB(QZONE.FP.replaceIconTag(escHTML(tag)));}
content+=result;}
return content;},getRemark:function(uin,name){var map;QZONE.FP.getRemarkList(function(d){map=d;$e('.remarkUin').each(function(){var el=$e(this);var uin=el.getAttr('uin');if(map[uin]){el.setHtml(escHTML(restHTML(map[uin])));}});});this.getRemark=function(uin,name){if(map&&map[uin]){return escHTML(restHTML(map[uin]||name||uin));}else{return['<span class="remarkUin" uin="',uin,'">',escHTML(name||uin),'</span>'].join('');}}
return this.getRemark(uin,name);},applyAccess:function(uin){var PRE_APPLY_ENTRY_MSG='http://'+QZONE.FP._t.g_W_Domain+'/cgi-bin/tfriend/applyentryright.cgi';var _loader=new QZONE.FormSender(PRE_APPLY_ENTRY_MSG,'POST',{'vUin':QZONE.FP._t.g_iLoginUin,'hUin':uin,'fupdate':1,'rd':Math.random()},'utf-8');_loader.onSuccess=function(re){if(re.ret=="succ"||re.code==0){QZONE.FP.showMsgbox('申请已发送，请注意查看“好友消息通知"',4,2000);}
else{QZONE.FP.showMsgbox((re.msg||re.message),1,2000);}};_loader.onError=function(){QZONE.FP.showMsgbox('很抱歉，当前使用的人数过多，请休息一会儿再来',1,2000);}
_loader.send();}});(function(){var cache={};this.tmpl=function tmpl(str,data){var fn=!/\W/.test(str)?cache[str]=cache[str]||tmpl(document.getElementById(str).innerHTML):new Function('obj','var p=[],print=function(){p.push.apply(p,arguments);};'+"with(obj){p.push('"+
str.replace(/[\r\t\n]/g,' ').split('<%').join('\t').replace(/((^|%>)[^\t]*)'/g,'$1\r').replace(/\t=(.*?)%>/g,"',$1,'").split('\t').join("');").split('%>').join("p.push('").split('\r').join("\\'")
+"');}return p.join('');");return data?fn(data):fn;};})();(function(){var cbSplit;if(!cbSplit){cbSplit=function(str,separator,limit){if(Object.prototype.toString.call(separator)!=='[object RegExp]'){return cbSplit._nativeSplit.call(str,separator,limit);}
var output=[],lastLastIndex=0,flags=(separator.ignoreCase?'i':'')+
(separator.multiline?'m':'')+
(separator.sticky?'y':''),separator=RegExp(separator.source,flags+'g'),separator2,match,lastIndex,lastLength;str=str+'';if(!cbSplit._compliantExecNpcg){separator2=RegExp('^'+separator.source+'$(?!\\s)',flags);}
if(limit===undefined||+limit<0){limit=Infinity;}else{limit=Math.floor(+limit);if(!limit){return[];}}
while(match=separator.exec(str)){lastIndex=match.index+match[0].length;if(lastIndex>lastLastIndex){output.push(str.slice(lastLastIndex,match.index));if(!cbSplit._compliantExecNpcg&&match.length>1){match[0].replace(separator2,function(){for(var i=1;i<arguments.length-2;i++){if(arguments[i]===undefined){match[i]=undefined;}}});}
if(match.length>1&&match.index<str.length){Array.prototype.push.apply(output,match.slice(1));}
lastLength=match[0].length;lastLastIndex=lastIndex;if(output.length>=limit){break;}}
if(separator.lastIndex===match.index){separator.lastIndex++;}}
if(lastLastIndex===str.length){if(lastLength||!separator.test('')){output.push('');}}else{output.push(str.slice(lastLastIndex));}
return output.length>limit?output.slice(0,limit):output;};cbSplit._compliantExecNpcg=/()??/.exec('')[1]===undefined;cbSplit._nativeSplit=String.prototype.split;}
String.prototype.split=function(separator,limit){return cbSplit(this,separator,limit);};})();var resizeImage=function(obj,maxW,maxH){if(obj.loaded==true)return;obj.loaded=true;var _img=new Image();_img.onload=function(){if(_img.width>maxW){obj.width=maxW;obj.style.width=maxW+'px';obj.style.height='auto';}else{obj.width=_img.width;obj.style.width=_img.width+'px';obj.style.height='auto';}
obj.style.display='block';}
console.log('resizeImage',this);_img.src=obj.src;};var resizeImageHandler=function(){var obj=this;var src=this.getAttribute('data-src');var limit_info=this.getAttribute('data-limit')||'';var limit=limit_info.split(',');var width=this.width;var maxH=this.height;if(limit.length==2){var ew=parseInt(limit[0],10);var eh=parseInt(limit[1],10);var _img=new Image();_img.onload=function(){var imgWHRatio=this.width/this.height;var expectWHRatio=ew/eh;if(this.width>ew&&this.height>eh){if(imgWHRatio<=expectWHRatio){obj.width=ew;}else{obj.height=eh;}}
obj.style.display='block';_img.onload=null;}
_img.src=src;}};(function(){window.controller={tab:MOOD.env.tab,uin:MOOD.env.uin,login_uin:''+QZONE.FP.getQzoneConfig('loginUin'),login_name:''+QZONE.FP.getQzoneConfig('loginUin'),updateLoginInfo:function(d){console.log('updateLoginInfo',d);if(d&&typeof d.logininfo=='object'){this.login_name=d.logininfo.name;this.login_uin=d.logininfo.uin;}},getTitle:function(){return'';},updateTitle:function(d){if(d&&d.usrinfo&&d.usrinfo.uin!=QZONE.FP.getQzoneConfig('loginUin')){var html=(escHTML(d.usrinfo.name)+'的说说');$e('.mod_tab .friend_feed_head').setHtml(html).show();}},getDetailSuc:function(d){if(d.code<0){return{code:d.code,msg:d.message};}
var item={};item.source_name=((d.source_name=='朋友网'||d.source_name=='QQ空间')&&!isQzone)?'':d.source_name;item.rt_source_name=((d.rt_source_name=='朋友网'||d.rt_source_name=='QQ空间')&&!isQzone)?'':d.rt_source_name||'';item.auth_flag=d.auth_flag||0;item.right=d.right||1;item.commentlist=d.commentlist||[];item.replies=d.replies||d.msgTotal||item.commentlist.length;item.total=1;item.msglist=[d];t.updateTitle(d);return item;},getProfileHtml:function(){var d=window._preloadCache;if(d&&d.usrinfo){d.usrinfo.msgnum=d.usrinfo.msgnum||0;return tmpl(MOOD.tmp.profile)(d.usrinfo);}else{return"";}},getLastCommentHtml:function(){}};var t=controller;})();var t=t||controller;controller.image_displayDetail=function(imageInfo){var topic=imageInfo.comment.getTopic();QZONE.FP.openViewer({appid:311,from:"shuoshuo",ownerUin:topic.getHostUin(),topicId:topic.getId()+'_1',picKey:topic.getId().split('_')[1]+','+imageInfo.id,pre:imageInfo.url,timeStamp:new Date()});};QZFL.object.extend(controller,{commentModuleConfig:{commentListConfig:{pageSize:5,showPaginationForm:false,showAllLinkConfig:{innerTemplate:'查看全部<span id="${id}_totalNumLabel"></span>条评论',urlTemplate:function(topic){var platform='';if(topic.getPlatform){platform=topic.getPlatform();}
if(topic){if(document.domain=='qq.com'){return'http://user.qzone.qq.com/'+topic.getByPath('poster.id')+'/mood/'+topic.getId()+'.'+platform;}
return'http://baseapp.pengyou.com/'+topic.getByPath('poster.id')+'/mood/'+topic.getId()+'.'+platform;}
return'';},onClick:function(e){var topic=e.topic;if(t.tab=='detail'){topic.setByPath('comments.pageNum',1);return false;}
location.href='index.html?uin='+topic.getByPath('poster.id')+'&tid='+topic.getId().split('_').pop()+'&need_cmt=1&source='+topic.getByPath('platform')||0;return false;}},showRepliesByDefault:true,itemConfig:{imageIconConfig:{},imageButtonConfig:{},userLinkConfig:{target:'_self',urlTemplate:function(user){if(user){switch(user.getPlatform()){case user.PLATFORM.PENGYOU:return'http://baseapp.pengyou.com/'+user.getId()+'/mood/';case user.PLATFORM.QZONE:return'http://user.qzone.qq.com/'+user.getId()+'/mood/';}}
return'#';},onClick:function(e){var user=e.user;mood.jumpPage(user.getId(),user.getPlatform());return false;}},topicLinkConfig:{template:function(topicCode,topicWords){if(topicCode&&topicWords){return['<a href="javascript:void(0);" onclick="MOOD.topic.search(unescape(\'',escape(topicWords),'\'));return false;" class="c_tx">',escHTML(topicCode),'</a>'].join('');}
return'';}}}},commentBoxConfig:{contentMaxLength:500,emoticonSupported:true,presentTargetUin:0,checkBoxConfig:[],needPrivateComment:1},appid:311},updateFeeds:function(d){if(QZFL.lang.isArray(d)){QZFL.each(d,function(d){t.updateFeed(d);});}else{t.updateFeed(d);}},updateFeed:function(item){var mood_id=('mood_'+item.tid);if(!MOOD.DataStorage.get(item.tid)){QZFL.console.print('updateFeed: '+mood_id);item.created_time=(new Date()).valueOf();item.source_name=((item.source_name=='朋友网'||item.source_name=='QQ空间')&&!isQzone)?'':item.source_name;item.rt_source_name=((item.rt_source_name=='朋友网'||item.rt_source_name=='QQ空间')&&!isQzone)?'':item.rt_source_name;var mood=MOOD.DataStorage.set(item.tid,item);var c=document.createElement('div');c.innerHTML=mood.getItemHTML();var l=$e(c).find('li').elements[0];var refchild=$('msgList');if(refchild.childNodes[0]){refchild.insertBefore(l,refchild.childNodes[0]);}else{refchild.appendChild(l);}
t.initCommentModule(item);t.loadVisiableItems();try{var count=$e('.feed_num a').getHtml();count=parseInt(count,10);count++;$e('.feed_num a').setHtml(count);$e('.empty_pic_message').hide();}catch(e){}}else{QZFL.console.print(mood_id+' existed.');}},renderLikeButton:function(mmc){$e('.mod_feed_lst#msgList li.feed').each(function(){var tid=this.getAttribute('data-tid');var mood=MOOD.DataStorage.get(tid);if(mood){t.likeButton(mood);}});},likeButton:function(item){var like_btn=$('like_btn_'+item.data.tid);if(like_btn){if(like_btn.getAttribute('data-handled')==1){return;}
(function(d,like_btn){var item=d;var data=item.data;var uniKey='';var curKey='';var isSinglePic=data.pictotal==1?true:false;if(isSinglePic){var unilikekey=data.pic[0].unilikekey;var curlikekey=data.pic[0].curlikekey;}
if(data.rt_tid&&data.rt_nosrc){uniKey=['http://user.qzone.qq.com/119/mood/',data.rt_tid,'.',data.rt_source].join('');curKey=['http://user.qzone.qq.com/',data.uin,'/mood/',data.tid,'.',data.t1_source].join('');}else if(data.rt_tid){uniKey=['http://user.qzone.qq.com/',data.rt_uin,'/mood/',data.rt_tid,'.',data.rt_source].join('');curKey=['http://user.qzone.qq.com/',data.uin,'/mood/',data.tid,'.',data.t1_source].join('');}else if(isSinglePic&&(unilikekey||curlikekey)){uniKey=unilikekey||curlikekey;curKey=curlikekey||unilikekey;}else{uniKey=['http://user.qzone.qq.com/',data.uin,'/mood/',data.tid,'.',data.t1_source].join('');curKey=uniKey;}
var keys={key:['http://user.qzone.qq.com/',data.owneruin||data.uin,'/mood/',data.tid].join(''),uniKey:uniKey,curKey:curKey};var keys=item.getLikeKeys();QZONE.FP.addUGCLike(like_btn,{uniKey:keys.uniKey,curKey:keys.curKey},{btnStyle:3,template:{keepInSameRow:true,refreshTipBack:function(likeNode,likeWord){if(!document){return;}
var el=document.getElementById('feed_like_'+data.tid);if(el){if(likeWord){el.innerHTML=likeWord;el.style.display='';}else{el.style.display='none';}}},TIP:['<span><i class="ui_ico icon_hand ui_ico_f qz_like_hand hand"></i>','<?if {ilike}>"0"?>我<?/if?>','<?if {ilike}>"0"?><? cif{rCnt}>"0"?>和<?/cif?><?/if?>','<?loop times="2" ?><a href="http://user.qzone.qq.com/{uin}" target="_blank" class="c_tx" title="{nick}">{shortNick}</a><?if {count}<{length}?>、<?/if?>&nbsp;<?/loop?>','{etc}','<?if {rCnt}>"0"?>','<a href="javascript:void(0);" onclick="QZONE.FP.getLikeList(\'',uniKey,'\');MOOD.sendEvent(\'clickLikePeopleNum\');return false;" class="c_tx">','{peopleCount}</a>','<?/if?>','<?if {cnt}>"0"?>觉得很赞<?/if?>','</span>'].join('')},onLike:function(){try{MOOD.sendEvent('like'+location.pathname);}catch(e){}},onCancelLike:function(){try{MOOD.sendEvent('unlike'+location.pathname);}catch(e){}}});})(item,like_btn);like_btn.setAttribute('data-handled',1)}},isAbleTo:function(actionName,data){var posterUin=data.getByPath('poster.uin');var loginUin=QZONE.FP.getQzoneConfig('loginUin');var topicPosterUin=data.getByPath('topic.poster.id');if(actionName=='reportComment'){return posterUin!=loginUin;}
if(actionName=='reportReply'){return false;}
if(actionName=='removeComment'){if(topicPosterUin==loginUin){return true;}
if(posterUin==loginUin){return true;}
return false;}
if(actionName=='removeReply'){if(topicPosterUin==loginUin){return true;}
if(posterUin==loginUin){return true;}
return false;}
if(actionName=='postReply'){return true;}
return false;},isAbleTo4Share:function(actionName,data){if(actionName=='reportComment'||actionName=='reportReply'){return false;}
return t.isAbleTo(actionName,data);},extendCommentSync:function(mood){if(mood.ugc_right>=4){return[];}
var checkBoxConfig=[{checkBoxChecked:0,checkBoxLabel:'同时转发',checkBoxLocalKey:'with_fwd',showCheckBox:1}];if((mood.to_tweet||mood.wbid)&&QZONE.FP.getUserBitmap(41)&&QZONE.FP.getLoginBitmap(41)){checkBoxConfig.push({checkBoxChecked:0,checkBoxLabel:'点评到微博',checkBoxLocalKey:'to_tweet',showCheckBox:1});}
return checkBoxConfig;},adaptMoodCommentData:function(commentlist){var commentInfo={};var result=[];var replies;for(var i=0;i<commentlist.length;i++){var commentInfo=commentlist[i];replies=[];if(commentInfo.list_3){for(var j=0;j<commentInfo.list_3.length;j++){var replyInfo=commentInfo.list_3[j];replies.push({id:replyInfo.tid,content:replyInfo.content,pic:replyInfo.pic,poster:{id:replyInfo.uin,name:replyInfo.name,platform:replyInfo.t3_source},postTime:replyInfo.create_time});}}
result.push({id:commentInfo.tid,content:commentInfo.content,poster:{id:commentInfo.uin,name:commentInfo.name,platform:commentInfo.t2_source},pic:commentInfo.pic,postTime:commentInfo.create_time,replies:replies,source:'','private':commentInfo['private'],targetImage:commentInfo.targetImage});}
return result;},initCommentModule:function(data,onSuccess){var mood=data;MOOD.commentModule=MOOD.commentModule||{};var commentModule=MOOD.commentModule[mood.tid];if(commentModule){onSuccess&&onSuccess(commentModule);return;}
if(mood.timershuoshuo){return;}
mood.auth_flag=mood.auth_flag||0;mood.source_name=(mood.source_name&&(mood.source_name=='朋友网'||mood.source_name=='QQ空间')&&!isQzone)?'':mood.source_name;mood.rt_source_name=(mood.rt_source_name&&(mood.rt_source_name=='朋友网'||mood.rt_source_name=='QQ空间')&&!isQzone)?'':mood.rt_source_name;mood.commentTotal=mood.replies;var commentListItemConfig=controller.commentModuleConfig.commentListConfig.itemConfig;if(controller.tab=='detail'){commentListItemConfig.imageIconConfig.onClick=null;commentListItemConfig.imageButtonConfig.onClick=controller.image_displayDetail;}
else{commentListItemConfig.imageIconConfig.onClick=controller.image_displayDetail;commentListItemConfig.imageButtonConfig.onClick=null;}
if(controller.tab=='detail'){controller.commentModuleConfig.commentListConfig.pageSize=20;controller.commentModuleConfig.commentListConfig.defaultPageNum=1;}else{controller.commentModuleConfig.commentListConfig.pageSize=5;controller.commentModuleConfig.commentListConfig.defaultPageNum=0;}
if(mood.source_type=='share'){requirejSolution(function(j$){j$.load({ids:['/controls/commentModule:3.0:prototype','/controls/commentModule/viewModel:3.0_common:prototype','/requests/base:3.0:prototype'],onSuccess:function(CommentModule,ViewModel,BaseRequest){MOOD.commentModule[mood.tid]=CommentModule.create({config:controller.commentModuleConfig,dataContext:ViewModel.create({id:mood.uin+'_'+mood.tid,hostUin:QZONE.FP.getQzoneConfig('ownerUin'),poster:ViewModel.UserViewModel.create({id:mood.uin,name:mood.name}),cgiUrls:{postReply:'http://sns.qzone.qq.com/cgi-bin/qzshare/cgi_qzshareaddcomment?fupdate=2',postComment:'http://sns.qzone.qq.com/cgi-bin/qzshare/cgi_qzshareaddcomment?fupdate=2',removeComment:'http://sns.qzone.qq.com/cgi-bin/qzshare/cgi_qzsharedeletecomment?fupdate=2',loadComments:'http://sns.qzone.qq.com/cgi-bin/qzshare/cgi_qzshareget_comment?fupdate=2'},strategy:{isAbleTo:t.isAbleTo4Share},request:BaseRequest.create({get_onReceived:function(o){if(o.code!==0){o.code=0;o.message="";o.data={comments:[]};}else{if(o.data.total){$('comment_btn_'+mood.tid).innerHTML='评论('+o.data.total+')';}}}}),inCharset:'utf-8',outCharset:'utf-8'}),placeHolder:$('comment_list_'+mood.tid)});onSuccess&&onSuccess(MOOD.commentModule[mood.tid]);}});});return;}
requirejSolution(function(j$){j$.load({ids:['/controls/commentModule:3.0:prototype','/controls/commentModule/viewModel:3.0_common:prototype','/requests/moodRequest:3.1:prototype','/strategies/moodRequestStrategy:3.1:prototype'],onSuccess:function(CommentModule,ViewModel,Request,RequestStrategy){var locationCache=(window._locationCache||{idcNo:1});var domainPrefix=locationCache.idcNo==2?'sh.':'';var config={id:mood.uin+'_'+mood.tid,hostUin:QZONE.FP.getQzoneConfig('ownerUin'),poster:{id:mood.uin,name:mood.name,platform:mood.t1_source},CommentViewModel:ViewModel.CommentViewModel.derive({className:'moodCommentViewModel',methods:{getReportData:function(){var comment=this;return{appname:'qzone',subapp:'shuoshuo_comment',jubaotype:'article',t1_tid:(comment.getByPath('topic.id')||'').replace(comment.getByPath('topic.poster.id')+'_',''),t1_uin:comment.getByPath('topic.poster.id'),t1_source:comment.getByPath('topic.platform')||1,t2_tid:comment.getByPath('id'),t2_uin:comment.getByPath('poster.id')};}}}),cgiUrls:{entopComment:format('http://taotao.{domain}/cgi-bin/emotion_cgi_addtopcomment_v6',{domain:document.domain=='qq.com'?'qzone.qq.com':document.domain}),loadComments:format('http://taotao.{domain}/cgi-bin/emotion_cgi_getcmtreply_v6?need_private_comment=1',{domain:document.domain=='qq.com'?'qzone.qq.com':document.domain,domainPrefix:t.tab=='mine'?domainPrefix:''}),postComment:format('http://taotao.{domain}/cgi-bin/emotion_cgi_addcomment_ugc',{domain:document.domain=='qq.com'?'qzone.qq.com':document.domain}),removeComment:format('http://taotao.{domain}/cgi-bin/emotion_cgi_delcomment_ugc',{domain:document.domain=='qq.com'?'qzone.qq.com':document.domain}),postReply:format('http://taotao.{domain}/cgi-bin/emotion_cgi_addreply_ugc',{domain:document.domain=='qq.com'?'qzone.qq.com':document.domain}),removeReply:format('http://taotao.{domain}/cgi-bin/emotion_cgi_delreply_ugc',{domain:document.domain=='qq.com'?'qzone.qq.com':document.domain})},strategy:{isAbleTo:t.isAbleTo},request:Request.create({get_onReceived:function(o){if(o.code!==0){o.code=0;o.message="";o.data={comments:[]};}}})};if(controller.tab=='mine'||controller.tab=='detail'){config.CommentListViewModel=ViewModel.CommentListViewModel.derive({properties:{pageNum:{initialValue:(function(){if(controller.tab=='detail'){return 1}
return 0;})()},pageSize:{initialValue:(function(){if(controller.tab=='detail'){return 20;}
return 5;})()},order:{initialValue:0}},methods:{load:function(){var pageNum=this.getPageNum();var topic=this.getTopic();if(controller.tab=='detail'){if(topic&&pageNum===1&&mood.commentlist&&mood.commentlist.length){this.setSourceData({comments:controller.adaptMoodCommentData(mood.commentlist),total:mood.cmtnum})
this.load=arguments.callee.base;return;}}else{if(topic&&pageNum===0&&mood.commentlist&&mood.commentlist.length){this.setSourceData({comments:controller.adaptMoodCommentData(mood.commentlist),total:mood.cmtnum})
this.load=arguments.callee.base;return;}}
return arguments.callee.base.apply(this,arguments);}}})}else{config.CommentListViewModel=ViewModel.CommentListViewModel.derive({properties:{pageNum:{initialValue:0},pageSize:{initialValue:5},coverPageSize:{initialValue:5},converOrder:{initialValue:1}}});}
var commentModuleConfig=controller.commentModuleConfig;commentModuleConfig.commentBoxConfig.checkBoxConfig=t.extendCommentSync(mood);MOOD.commentModule[mood.tid]=CommentModule.create({config:commentModuleConfig,dataContext:ViewModel.create(config),placeHolder:$('comment_list_'+mood.tid)});onSuccess&&onSuccess(MOOD.commentModule[mood.tid]);}});});},actionResponse:function(commentModule){switch(MOOD.env.action){case'comment':if(commentModule){commentModule.show();commentModule.focus();}
break;case'forward':break;default:break;}},appScrollHandler:function(){console.log('appScrollHandler');},viewport_:function(_w){_w=_w||window;var scrollY=0;if(typeof(_w.pageYOffset)=='number'){scrollY=_w.pageYOffset;}else if(_w.document.body&&_w.document.body.scrollTop){scrollY=_w.document.body.scrollTop;}else if(_w.document.documentElement&&_w.document.documentElement.scrollTop){scrollY=_w.document.documentElement.scrollTop;}
var height=_w.innerHeight||_w.document.documentElement.clientHeight||_w.document.body.clientHeight;return{top:scrollY,bottom:scrollY+height,height:height};},getFrameNode:function(){var node;if(parent.g_version==5){node=parent.QZFL.dom.get('frameContainer');}else{node=parent.QZFL.dom.get('LayPageContainer')||parent.QZFL.dom.get('pageApp');}
return node;},isVisiable:function(element){var node=this.getFrameNode();var innerScrollTop=node?node.scrollTop:0;var viewport=t.viewport_(parent);var el=$e(element);var buffer_=0;var position=QZFL.dom.getPosition(element);top_diff=position.top-viewport.bottom-innerScrollTop;bottom_diff=position.bottom-viewport.top-innerScrollTop;var result=(top_diff<=buffer_&&bottom_diff+buffer_>=0);return result;},loadIfVisiable:function(element,index){var imageLoadFlag=element.getAttribute('data-img-load');var commentModuleLoadFlag=element.getAttribute('data-comment-load');var result=t.isVisiable(element);var LOAD_PHOTO_EXT_PARAM='rf=mood_app';var isSupportWebp=QZONE.FP._t.QZFL.cookie.get('QZ_FE_WEBP_SUPPORT')=="1";if(isSupportWebp){LOAD_PHOTO_EXT_PARAM+='&t=5';}
var tid=element.getAttribute('data-tid');if(result&&imageLoadFlag!='load'){element.setAttribute('data-img-load','load');$e(element).find('img').each(function(){if($e(this).hasClass('typeset-lazyload')){$e(this).removeClass('typeset-lazyload');var src=this.getAttribute('data-src');var midSrc=this.getAttribute('data-midsrc');var bigSrc=this.getAttribute('data-bigsrc');if((src||midSrc||bigSrc).indexOf('http://p.qpimg.cn/cgi-bin/cgi_imgproxy')>-1){LOAD_PHOTO_EXT_PARAM='';}
if(src&&LOAD_PHOTO_EXT_PARAM){src+=(src.indexOf('?')>-1?'&':'?')+LOAD_PHOTO_EXT_PARAM;}
if(midSrc&&LOAD_PHOTO_EXT_PARAM){midSrc+=(midSrc.indexOf('?')>-1?'&':'?')+LOAD_PHOTO_EXT_PARAM;}
if(bigSrc&&LOAD_PHOTO_EXT_PARAM){bigSrc+=(bigSrc.indexOf('?')>-1?'&':'?')+LOAD_PHOTO_EXT_PARAM;}
var picWidth=this.getAttribute('pic-width');var picHeight=this.getAttribute('pic-height');var index=parseInt(this.getAttribute('pic-index'),10)+1;if(src){var imageItemContainer;QZFL.dom.searchChain(this,'parentNode',function(node){if(!node){return;}
if($e(node).hasClass('img-item-'+index)){imageItemContainer=node;return true;}});var size=QZFL.dom.getSize(imageItemContainer);var holderWidth=size[0];var holderHeight=size[1];var isbigHolder=(holderWidth==400||holderHeight==400);var showImage=this;var loadImage=new Image();loadImage.onload=function(){if(this.width<holderWidth||this.height<holderHeight){if(this.width/this.height>holderWidth/holderHeight){showImage.height=holderHeight;}else{showImage.width=holderWidth;}
if(picWidth>holderHeight&&picHeight>holderHeight){showImage.src=bigSrc;}else{showImage.src=this.src;}
return;}
if(this.width/this.height>holderWidth/holderHeight){showImage.height=holderHeight;}else{showImage.width=holderWidth;}
showImage.src=this.src;};loadImage.src=isbigHolder?bigSrc:src;}}
if($e(this).hasClass('lazyload')){$e(this).removeClass('lazyload');var src=this.getAttribute('data-src');var isphoto=this.getAttribute('data-isphoto');if(src.indexOf('http://p.qpimg.cn/cgi-bin/cgi_imgproxy')>-1){LOAD_PHOTO_EXT_PARAM='';}
if(src){if(isphoto==1&&LOAD_PHOTO_EXT_PARAM){src+=(src.indexOf('?')>-1?'&':'?')+LOAD_PHOTO_EXT_PARAM;}
var limit_info=this.getAttribute('data-limit')||'';var limit=limit_info.split(',');if(limit.length!=2){limit=[400,300];};var bigPic=limit[0]==400;QZFL.media.reduceImage((bigPic?0:1),limit[0],limit[1],{trueSrc:src,img:this,callback:function(obj,type,tagW,tagH,p){if(bigPic){return;}
var newW=parseInt(QZFL.dom.getStyle(obj,'width'),10),newH=parseInt(QZFL.dom.getStyle(obj,'height'),10);var offH=-(newH-tagH)/2,offW=-(newW-tagW)/2;if(offH){QZFL.dom.setStyle(obj,'margin-top',offH+'px');}
if(offW&&offW<0){QZFL.dom.setStyle(obj,'margin-left',offW+'px');}}});}}});}
if(result&&commentModuleLoadFlag!='load'){element.setAttribute('data-comment-load','load');var mood=MOOD.DataStorage.get(tid);if(!mood){console.log('tid:'+tid);return;}
if(mood.data.right>1){return;}
qzlog.info({cm:"MOOD_APP",cf:"initCommentModule-"+index+" START"});t.initCommentModule(mood.data,t.tab=='detail'?function(){t.actionResponse();qzlog.info({cm:"MOOD_APP",cf:"initCommentModule-"+index+" FINISHED"});}:function(){qzlog.info({cm:"MOOD_APP",cf:"initCommentModule-"+index+" FINISHED"});});}},loadVisiableItems:function(){qzlog.info({cm:"MOOD_APP",cf:"loadVisiableItems START"});var self=this;if(self.loadVisiableItems._loadTimer){return;}
self.loadVisiableItems._loadTimer=setTimeout(function(){var feeds=$e('.mod_feed_lst#msgList li.feed');var count=0;feeds.each(function(item,index){t.loadIfVisiable(this,index);if(item.getAttribute('data-like-handled')!=1&&count<10){count++;var tid=item.getAttribute('data-tid');var mood=MOOD.DataStorage.get(tid);t.likeButton(mood);item.setAttribute('data-like-handled',1);}});self.loadVisiableItems._loadTimer=null;},100);},resetScrollHandler:function(){t._scroll_timer=null;t._min_scroll_time=200;t._last_scroll_time=0;t._last_scroll_top=0;},_scroll_timer:null,_min_scroll_time:200,_last_scroll_time:0,_last_scroll_top:0,scrollHandler:function(){if(!t._scroll_timer){var now=new Date().getTime();var timeout_ms=t._min_scroll_time;if(now-t._last_scroll_time>t._min_scroll_time){timeout_ms=0;}
t._scroll_timer=window.setTimeout(function(){t._last_scroll_time=new Date().getTime();t.loadVisiableItems();var screen_height=QZONE.FP._t.QZFL.dom.getClientHeight();var scroll_top=QZONE.FP._t.QZFL.dom.getScrollTop();var height=QZONE.FP._t.QZFL.dom.getScrollHeight();if(t.tab=='feedlist'&&(screen_height+scroll_top>height-200)&&scroll_top-10>t._last_scroll_top){t._last_scroll_top=scroll_top;if(t.mmc){t.mmc.fetch();console.log('滚动加载哦');}
console.log(height,screen_height+scroll_top,screen_height,scroll_top);}
t._scroll_timer=null;},timeout_ms);}},fixNum:function(){seajs.use('app/v8/requests/mood_request/1.0',function(mr){mr.get({id:'shuoshuoinfo_v6',data:{uin:t.uin},onSuccess:function(d){if(d&&d.total>=0){$e('.feed_num a').setHtml(d.total);}},onError:function(d){if(d==undefined){}}});});},loadBanner:function(){t.MenuHandler();if(isOwner){QZFL.imports('/qzone/v6/v6_config/moodbanner.js');}},updateMenu:function(tabIndex){switch(tabIndex){case'detail':$e('.feed_wrap .feed_head').show();break;case'weibo':$e('.feed_wrap .feed_head').hide();$e('.nav_weibo').find('a').addClass('selected');break;case'feedlist':case'mine':case'schedule':$e('.feed_wrap .feed_head').show();$e('.nav_my').find('a').addClass('selected');break;case'index':$e('.feed_wrap .feed_head').hide();$e('.nav_home').find('a').addClass('selected');break;case'hot':$e('.feed_wrap .feed_head').hide();$e('.nav_hot').find('a').addClass('selected');break;default:$e('.feed_wrap .feed_head').hide();}},MenuHandler:function(){if(!QZONE.FP.getUserBitmap(41)||!QZONE.FP.getQzoneConfig('loginUin')){$e('.nav_weibo').addClass('none');}
$e('.shuoshuo_menu ul li a').onClick(function(event){var target=QZFL.event.getTarget(event);if(target.getAttribute('id')=='menu_wall'||target.parentNode.getAttribute('id')=='menu_wall'){return true;}
QZFL.event.preventDefault(event);var tab=$e(this).getAttr('data-tab');$e('.shuoshuo_menu ul li a').removeClass('selected');$e(this).addClass('selected');t.tab=tab;if(!isQzone&&t.tab=='feedlist'){t.tab='mine';}
if(t.tab=='hot'){t.getHotList(1,function(){t.load(t.tab);});}else{t.load(t.tab);}
t.updateMenu(t.tab);t.updateTitle();t.resetScrollHandler();return false;});t.updateMenu(t.tab);},userTracker:function(opt){if(document.domain!='qq.com'){return;}
var data={uin:'',mod:0,src:9,id:''};QZFL.object.extend(data,opt);var actionURL='http://g.qzone.qq.com/cgi-bin/friendshow/cgi_content_visitor';var fs=new QZFL.FormSender(actionURL,'POST',data,'utf-8');fs.onSuccess=function(d){};fs.send();}});var t=t||controller;QZFL.object.extend(controller,{load:function(tabIndex,page){if(window._preloadCache&&window._preloadCache.code==9999){window._preloadCache=null;}else if(window._preloadCache&&window._preloadCache.code==0){window._preloadCache.msglist=window._preloadCache.msglist||window._preloadCache.posts;}
t.updateTitle(window._preloadCache);t.updateCurrentTabStyle(tabIndex);MOOD.commentModule={};MOOD.load('*',function(M){t.mmc=new M.MoodModelCollection({uin:t.uin,type:tabIndex,hostUin:t.uin,initialData:window._preloadCache,success:function(mmc){if(!window._preloadCache){mmc.setConfig({mood:{comment:{max_comments_count:0}}});var mod_feed_lst=document.getElementById('msgList');var pageinfo=mmc.getPagination();if(t.tab=='feedlist'&&pageinfo.page>1){QZFL.dom.insertAdjacent(mod_feed_lst,2,mmc.getHTML());}else{if(QZFL.object.route(mmc,'opts.initialData.code')<0){console.log('[ERROR] mood/index.js controller.load 加载数据异常，错误码:',QZFL.object.route(mmc,'opts.initialData.code'));mod_feed_lst.innerHTML=QZFL.object.route(mmc,'opts.initialData.message')||QZFL.object.route(mmc,'opts.initialData.msg')||'';return;}
if(mmc.getSizeSync()>0){mod_feed_lst.innerHTML=mmc.getHTML();}else{mod_feed_lst.innerHTML=t.getEmptyPageTip();}}}
controller.onPageRendered(tabIndex,mmc);}});if(!window._preloadCache){t.mmc.fetch();}else{window._preloadCache=null;}});},init:function(){qzlog.info({cm:"MOOD_APP",cf:"controller.init START"});t.reportPV();new MOOD.MsgList({container:'msgList'});$e('.profile').setHtml(t.getProfileHtml());if(window._preloadCache&&window._preloadCache.code===9999){document.getElementById('error_tip_cont').style.display="block";}
t.showReview();if(window._preloadCache&&window._preloadCache.code!=9999){t.load(t.tab);}
MOOD.poster.init('poster');t.getLastCommentHtml();var referer=MOOD.util.getHttpParams('referer');if(referer&&referer.indexOf('hot_topic')!=-1){$('hot_topic_bd').onclick=function(e){var target=QZFL.event.getTarget(e);while(target&&target!=this){if(target.className=='topic_item'){MOOD.sendHotClick('/hottopic_click');return;}
target=target.parentNode;}};t.showHotWords();$('msgList').setAttribute('data-tab','hot_topic');}
t.eventHandler();t.loadBanner();t.runStyleFailedMonitor();setTimeout(function(){QZFL.imports('http://'+(window.siDomain||'qzonestyle.gtimg.cn')+'/utp/dnsget.js');},5000);switch(t.tab){case'hot':t.updateNickname();t.updateCount();break;case'feedlist':t.updateTabUrl();break;case'mine':t.updateTabUrl();break;case'schedule':break;case'detail':t.updateTabUrl();break;default:break;}
if(t.tab=='detail'){QZFL.event.addEvent(window,'hashchange',function(){window.console&&console.log('hashchange');try{window.location.reload();}catch(err){}});}
qzlog.info({cm:"MOOD_APP",cf:"controller.init FINISHED"});},eventHandler:function(){QZFL.event.removeEvent(parent,'scroll',t.scrollHandler);QZFL.event.addEvent(parent,'scroll',t.scrollHandler);try{var node;if(parent.g_version==5){node=parent.QZFL.dom.get('frameContainer');}else{node=parent.QZFL.dom.get('LayPageContainer');}
QZFL.event.removeEvent(node,'scroll',t.scrollHandler);QZFL.event.addEvent(node,'scroll',t.scrollHandler);}catch(e){}
QZFL.event.addEvent(window,'unload',function(){window.console&&console.log('mood app unload fired!');try{QZFL.event.removeEvent(parent,'scroll',t.scrollHandler);var node=parent.QZFL.dom.get('LayPageContainer');QZFL.event.removeEvent(node,'scroll',t.scrollHandler);}catch(e){}});},_reportString:function(id,string,reportRate){try{if(!id){return;}
var TCISD=window.TCISD;if(!TCISD&&window.QZONE&&window.QZONE.FP&&window.QZONE.FP.getStatPackage){TCISD=QZONE.FP.getStatPackage();}
if(TCISD&&TCISD.stringStat){TCISD.stringStat('1000100',{bid:id,rc:string},{reportRate:reportRate||100});}}catch(err){}},initFavoriteWidget:function(){window.seajs&&window.seajs.use(['app/favorite/script/favorite_for_app/1.0','jquery'],function(F,jQuery){if(!F){return;}
if(!jQuery){return;}
var uin=QZONE.FP.getQzoneConfig().loginUin;jQuery('#msgList').find('.add_favorite_container').each(function(index,ele){var container=jQuery(ele);var li=container.parents('li:first');var moodId=li.attr('data-tid');var ownerUin=li.attr('data-uin');var f=F.init({data:{id:moodId,owneruin:ownerUin,uin:uin},container:container[0],who:'shuoshuo'});if(f){if(container.hasClass('need_bg2')){jQuery(f.template).mouseenter(function(){container.addClass('bg2');}).mouseleave(function(){container.removeClass('bg2');});}}});qzlog.info({cm:"MOOD_APP",cf:"init favorite widget FINISHED"});});},onPageRendered:function(tabIndex,moodModelCollection){var mmc=moodModelCollection;if(mmc.getSizeSync()>0){document.getElementById('error_tip_cont').style.display="none";}
controller.initFavoriteWidget();var pageinfo=mmc.getPagination();qzlog.info({cm:"MOOD_APP",cf:"init pager widget START"});tabIndex!='feedlist'&&MOOD.widget.loadPager(function(){t.pager=new F4A.widget.Pager($('pager'),{pageSize:pageinfo.rowsPerPage,currentPage:pageinfo.page,totalNum:pageinfo.totalRecords,onTurn:function(page){if(t.tab=='hot'){t.getHotList(page,function(page){t.load(t.tab,page);});}else{MOOD.commentModule={};t.mmc.fetch({page:page});}}});qzlog.info({cm:"MOOD_APP",cf:"init pager widget FINISHED"});});t.loadVisiableItems();if(tabIndex=='hot'){t.updateCount();}
var frameTop=frameElement&&QZFL.dom.getPosition(frameElement).top||0;var scrollTop=t.viewport_(parent).top;if(tabIndex!='feedlist'&&scrollTop>frameTop){QZONE.FP.setScrollTop(0);}
t.reportPV();},runStyleFailedMonitor:function(){try{var errorDisplay=$e('.network_busy').getStyle('display');if(errorDisplay==='block'){window.console&&console.log('load css failed');t.pingCDN(function(data){data.uin=MOOD.env.getLoginUin();window.console&&console.log('go css failed');t._reportString('101004',obj2str(data),100);});}}catch(err){}},pingCDN:function(onComplete){var data={};var st1=new Date();var img=new Image();var timeToCDN;img.onload=function(){this.onload=null;timeToCDN=new Date()-st1;};setTimeout(function(){if(!timeToCDN){timeToCDN=-1;}
data.timetocdn=timeToCDN;try{data.ie=ua.ie;data.chrome=ua.chrome;data.firefox=ua.firefox;}catch(err){}
onComplete&&onComplete(data);},3000);img.src='http://qzonestyle.gtimg.cn/qzone/app/mood_v6/images/blank.gif?r='+Math.random();},showHotMood:function(){var hot_mood_msg=$e('.feed_commend_note');hot_mood_msg.removeClass('none');if(t.showHotMood._inited){$e('.feed_commend').hide();return;}
hot_mood_msg.onClick(function(){$e('.feed_commend').show();QZFL.imports('/qzone/app/mood_v6/plugin/popular_mood.js',function(){QZONE.FP._t.MoodUseHot=window.UseHot=new HotMood();});});hot_mood_msg.onHover(function(){hot_mood_msg.addClass('bg2');});hot_mood_msg.onMouseOut(function(){hot_mood_msg.removeClass('bg2');});t.showHotMood._inited=true;},hideHotMood:function(){$e('.feed_commend_note').addClass('none');$e('.feed_commend').hide();},showHotWords:function(){var url='http://r.qzone.qq.com/cgi-bin/right_frame.cgi';var data={uin:QZONE.FP.getQzoneConfig('loginUin'),param:4};var r=new QZFL.JSONGetter(url,'_get'+Math.random(),data,'utf-8');r.onSuccess=function(d){if(d.code==0){var data=d.data.module_4.data;MOOD.hot_topic=data;t.refreshHotWords();}};r.onError=function(d){};r.send('_Callback');},refreshHotWords:function(){var data=MOOD.hot_topic||[];MOOD.lang.randomArray(data);var html='';for(var i=0;i<data.length&&i<3;i++){html+=data[i].html;}
if(html){html=html.replace(/_blank/g,'_top');$('hot_topic_bd').innerHTML=html;$e('#hot_topic').removeClass('none');}},showRecVideo:function(){var url='http://boss.qzone.qq.com/fcg-bin/fcg_get_strategy';var data={uin:QZONE.FP.getQzoneConfig('loginUin'),board_id:2049};var r=new QZFL.JSONGetter(url,'_get'+Math.random(),data,'utf-8');r.onSuccess=function(d){if(d.code==0){var data=JSON.parse(d.data['2049'].items[0].extdata);var html=['<div class="mod-sec-hd">','<h3>{text}</h3>','</div>','<div class="mod-sec-bd">','<div class="vedio-wrap">','<img src="{picUrl}" data-link="{link}" />','<a href="{link}" target="_top" class="btn-play-m {isVideo}" role="button"><i class="hide_clip">播放</i></a>','</div>','</div>'].join('');html=format(html,data);$('rec_vedio').innerHTML=html;$e('#rec_vedio').removeClass('none');}};r.onError=function(d){};r.send('_Callback');},dolike:function(li){var key=li&&li.getAttribute("key");if(!key){return;}
var url="http://"+top.g_W_Domain+"/cgi-bin/likes/internal_dolike_app";sd=new QZFL.FormSender(url,"post",{opuin:top.g_iLoginUin,unikey:key,curkey:key,from:0},"gb2312");sd.onSuccess=function(d){if(d.ret==0){var a='<a href="{key}?referer=hot_topic" target="_top"><span class="act_text c_tx">看详情</span></a>';a=format(a,{key:key});$e(li).find(".topic_op").setHtml(a);}}
sd.send();},getEmptyPageTip:function(){var tip='';switch(t.tab){case'weibo':tip='<img class="empty_pic_message" src="http://ctc.qzonestyle.gtimg.cn/qzone_v6/img/shuoshuo/empty_home_sync.png">';break;case'index':tip='<img class="empty_pic_message" src="http://ctc.qzonestyle.gtimg.cn/qzone_v6/img/shuoshuo/empty_feed_post.png">'
break;case'feedlist':case'mine':if(isOwner){tip='<img class="empty_pic_message" src="http://ctc.qzonestyle.gtimg.cn/qzone_v6/img/shuoshuo/empty_home_post.png">';}else{tip='<img class="empty_pic_message" src="http://ctc.qzonestyle.gtimg.cn/qzone_v6/img/shuoshuo/empty_guest_post.png">';}
break;case'schedule':tip='<img class="empty_pic_message" src="http://ctc.qzonestyle.gtimg.cn/qzone_v6/img/shuoshuo/empty_timing_post.png">'
break;case'detail':tip='该条说说已被删除';}
return tip;},reportPV:function(){t.isIndex=false;switch(t.tab){case'detail':MOOD.sendPV('detail');break;case'list':MOOD.sendPV('microblog');break;case'mine':if(isOwner){MOOD.sendPV('mytitle');}else{MOOD.sendPV('guesttitle');}
break;case'timer':MOOD.sendPV('timer');break;case'index':MOOD.sendPV('title');break;default:MOOD.sendPV(t.tab);}},showReview:function(){var d=window._preloadCache;var r=$('censor_count');if(r&&d){r.innerHTML='当前待审核评论 ('+(d.censor_count||0)+')';}},getLocalDb:function(key){if(QZONE.FP.noShareDb){try{return QZONE.FP.noShareDb.get(key);}catch(e){}}
return'';},setLocalDb:function(key,value){if(QZONE.FP.noShareDb){try{QZONE.FP.noShareDb.set(key,value);return true;}catch(e){}}
return false;},getHotPageNum:function(){var last=t.getLocalDb('mood_hot_page_time');if(last){var getDiffDays=function(time){var differ=8.5*60*60*1000-8*60*60*1000;var oneDay=24*60*60*1000;var days=Math.floor((time-differ)/oneDay);return days;}
var now=QZONE.FP.getSvrTime();var last_days=getDiffDays(parseInt(last));var curr_days=getDiffDays(now.getTime());if(last_days==curr_days){var num=t.getLocalDb('mood_hot_page_num');num=parseInt(num);return num?num+1:1;}}
return 1;},getHotList:function(page,callback){var random=t.getHotPageNum();var url=OOP.tpl.format('//{{siDomain}}/qzone_v6/act/hotTopic/top20_{{random}}.js',{siDomain:siDomain,random:random});var g=new QZFL.JSONGetter(url,null,{},'utf-8');g.onSuccess=function(d){var msglist=[];var data=window._LocalCacheCallbackData=d;for(var i=0;i<data.data.length&&i<20;i++){msglist.push(window._fakeData(data.data[i]));}
MOOD.lang.randomArray(msglist);window._LocalCacheData=window._LocalCacheData||{};window._LocalCacheData.msglist=msglist;window._LocalCacheData.total=data.totalCnt;window._preloadCache=window._LocalCacheData;callback(page);var now=QZONE.FP.getSvrTime();t.setLocalDb('mood_hot_page_num',random);t.setLocalDb('mood_hot_page_time',now.getTime());};g.send('_Callback');},updateNickname:function(){var uinList=[];$e('.mod_feed_lst#msgList li.feed').each(function(){var tid=this.getAttribute('data-tid');var mood=MOOD.DataStorage.get(tid);if(mood){uinList.push(mood.data.uin);}});QZFL.FP.getPortraitList(uinList,function(o){$e('.nickname').each(function(x){var el=$e(this);var _uin=el.getAttr('data-uin');try{if(typeof o[_uin+'']!='undefined'){el.setHtml(escHTML(restHTML(o[_uin][6])));}}catch(e){}});});},updateCurrentTabStyle:function(tab){tab=tab||t.tab
var selector=".feed_tab";if(tab=='feedlist'){selector+=' .all_tab';}else if(tab=='mine'){selector+=' .mood_tab';}else if(tab=='schedule'){selector+=' .timer_tab';}
if(!isOwner){selector+='_visitor';}
$e('.feed_tab a').removeClass('current');$e(selector).addClass('current');},updateTabUrl:function(){var allTab=$e('.feed_tab .all_tab_visitor');var allTabHref=allTab.getAttr('href');var moodTab=$e('.feed_tab .mood_tab_visitor');var moodTabHref=moodTab.getAttr('href');var queryUin=MOOD.util.getHttpParams('uin')||QZONE.FP.getQzoneConfig('ownerUin');if(QZONE.FP.getQzoneConfig('isOwner')){if(queryUin>10000&&queryUin!=QZONE.FP.getQzoneConfig('ownerUin')){allTab.setAttr('href',allTabHref+'&uin='+queryUin);moodTab.setAttr('href',moodTabHref+'&uin='+queryUin);}}else{allTab.setAttr('href',allTabHref+'&uin='+queryUin);moodTab.setAttr('href',moodTabHref+'&uin='+queryUin);}},updateCount:function(){var unikey;var keys=[];var maps={};$e('.mod_feed_lst#msgList li.feed').each(function(){var tid=this.getAttribute('data-tid');var mood=MOOD.DataStorage.get(tid);if(mood&&!this.getAttribute('data-countloaded')){var item=mood.data;unikey=['http://user.qzone.qq.com/',item.uin,'/mood/',item.tid,'.',item.t1_source].join('');keys.push(unikey);maps[['http://user.qzone.qq.com/',item.uin,'/mood/',item.tid].join('')]=format('{uin}_{tid}_{t1_source}',item);this.setAttribute('data-countloaded',1);}});var url='http://rsh.qzone.qq.com/cgi-bin/user/qz_opcnt2_sh';var data={fupdate:1,'unikey':keys.join('<|>'),'rd':Math.random()};var _loader=new QZFL.JSONGetter(url,null,data,'utf-8');_loader.onSuccess=function(o){if(o.code==0){o.data=o.data||[];var data;for(var i=0;i<o.data.length;i++){var item=o.data[i];data=item.current.newdata;if(maps[item.current.key]){var comment_btn='comment_btn_'+maps[item.current.key];var forward_btn='forward_btn_'+maps[item.current.key];if(data.CS>0&&$(comment_btn)){$(comment_btn).innerHTML=format('评论({CS})',data);}
if(data.ZS>0&&$(forward_btn)){$(forward_btn).innerHTML=format('转发({ZS})',data);}}}}};_loader.onError=function(){};_loader.send('_Callback');}});MOOD.updateFeeds=t.updateFeeds;QZFL.event.onDomReady(function(){timeStampsPool[7]=(new Date());if(top==window){$e(document.body).setStyle('width','900px').setStyle('margin','0 auto');};gTimeStampsPool[2]=(new Date());MOOD.domain.load();MOOD.pageStart(controller.init);gTimeStampsPool[3]=(new Date());timeStampsPool[8]=(new Date());setTimeout(function(){var chance=Math.floor(Math.random()*10)<3;var pageId=6;if(typeof pageId!='undefined'&&chance){var id=pageId||0;var timeStat=QZONE.FP.getStatPackage().createTimeStat("moodPageTime"+id,[175,367,id]);timeStat.zero=gTimeStampsPool[0];timeStat.timeStamps=gTimeStampsPool;timeStat.report();}
var timeStatMap={'mine':[175,367,23],'detail':[175,367,24]}
var timeStatId=timeStatMap[MOOD.env.tab];if(timeStatId){var pageTimeStat=QZONE.FP.getStatPackage().createTimeStat("moodPageTime_"+MOOD.env.tab,timeStatId);pageTimeStat.zero=timeStampsPool[0];pageTimeStat.timeStamps=timeStampsPool;pageTimeStat.report();}
if(QZFL.userAgent.ie&&QZFL.userAgent.ie>=9){window._timing_config={'f1':175,'f2':367,'f3':9};QZFL.imports('/qzone/app/timing/timing.js',function(){});}},0);if(document.domain=='pengyou.com'){var body=$e('body');body&&body.addClass('mod_py');}
$e('.mod_tab_nav').removeClass('none');MOOD.TCISDClick.batchBind({'#msgList[data-tab=hot_topic] .ft .op .qz_like_btn':'hot_topic.likeButton','#msgList[data-tab=hot_topic] .ft .op .comment_btn':'hot_topic.commentButton','#msgList[data-tab=hot_topic] .ft .op .forward_btn':'hot_topic.forwardButton','.mod_tab_op a':'old_mood_entry'});});qzlog.info({cm:"MOOD_APP",cf:"LOAD_JS_FINISHED"});gTimeStampsPool[1]=(new Date());timeStampsPool[6]=(new Date());