seajs.use(["v8/toolbar/core","v8/ic/accessory","v8/index/like","v8/core/qme","v8/api/interface/vip"].concat(window.g_moreModules||[]),function(toolbar,accessory,like){var cpujs={"load":function(cb,args){if(typeof cb=="function")cb(args);else{var i=0;for(i=0;i<cb.length;i++)if(args&&args.length)cb[i](args[i]);else cb[i]()}}};window.cpujs=cpujs;QZONE.GFP={isInit:false,bootstrap:function(){var p=QZONE.GFP;if(!p.isInit){p.beforeInitQM();p.initQMReloadEvent();p.isInit=true}},beforeInitQM:function(){var suid,
j=0;if(suid=QZONE.FrontPage.getParameter(location.href,"oldft"))QZONE.dressDataCenter.setWindows(g_Dressup.windows=QZONE.dressDataCenter.convert2XWMode(suid,QZONE.dressDataCenter.getWindows()));while(g_Dressup.windows&&j<g_Dressup.windows.length)if(g_Dressup.windows[j].appid==330||(g_Dressup.windows[j].appid==323||(g_Dressup.windows[j].appid==332||(g_Dressup.windows[j].appid==400||(g_Dressup.windows[j].appid==324||g_Dressup.windows[j].appid==326)))))g_Dressup.windows.splice(j,1);else j++;QZONE.GFP.initQM()},
checkQM:function(o){if(!QZONE.FrontPage.isVipUser())o&&QZFL.object.each(o.container||[],function(module){if(module&&module.appid==99){module.posx=Math.max(module.posx,0);module.posy=Math.max(module.posy,0);module.width=Math.min(module.width,900)}});return o},initQM:function(){var o={widgetdata:{g_Dressup:{windows:[]},g_StaticFlag:"",g_ReadOnly:0,g_Errno:0,g_Needfix:0,g_Abapps:[]}},fs,c=QME.turnOldWindowListToNewConfig(o,fs);c=QZONE.GFP.checkQM(c);QME.setConfig(c);QME.setModulePathPrefix("/qzone/v6/old_qm/qm_");
QME.setModuleTemplate('<div id="QM_Container_{index}" class="collet_box mod_wrap QM_{appid}_Wrap" style="{left} {top} {width} {height}">\t\t\t\t\t\t\t\t\t<div class="box_inner mod_wrap_inner">\t\t\t\t\t\t\t\t\t\t<div class="box_hd mod_wrap_hd" id="QM_{appid}_Title"></div>\t\t\t\t\t\t\t\t\t\t<div class="box_bd mod_wrap_bd" id="QM_{appid}_Body">\t\t\t\t\t\t\t\t\t\t\u6a21\u5757\u6b63\u5728\u521d\u59cb\u5316...\t\t\t\t\t\t\t\t\t\t</div>\t\t\t\t\t\t\t\t\t</div>\t\t\t\t</div>');QME.loadModules()},initQMReloadEvent:function(){QZONE.qzEvent.addEventListener("QZ_CUSTOM_CHANGE_STYLE",
function(evtObj,dataObj){window.g_StyleID=dataObj.styleid;var items=QME.extendedModulePool,fn;for(var k in items)if(items[k].dataType&&items[k].dataType=="iframe"){fn=QME.bootstrapPool["a"+items[k].appid];if(typeof fn=="function")fn()}})},setCustom:function(){var ins=QZONE.Module.instances,re=/<a[^>]*>([\s\S]*)<\/a>/i;for(var i in ins){var h3=ins[i].title&&$e(ins[i].title).find("h3");h3&&(h3.elements.length&&h3.setHtml(h3.getHtml().replace(re,"$1")))}}};function _report(type,val,opt){if(QZONE.FrontPage.isInteractZone()&&
location.href.indexOf("qz_gdt=")>-1){var id="index_v8_checkInteractZoneVisit";opt=opt||{};opt.uin=window.g_iUin;window.TCISD&&(TCISD.valueStat&&TCISD.valueStat(id,type,val,opt))}}var page={bootstrap:function(){_report(1,14);toolbar.bootstrap();like.bootstrap();var url="http://"+siDomain+"/qzone/v8/index/v6/old_qm_4_module.js";if(QZONE.FrontPage.isInteractZone())url="http://"+siDomain+"/c/=/qzone/v8/index/v6/old_qm_4_module.js,/qzone/biz/vpage/v6/v.js";else if(QZONE.FrontPage.isFamousZone())url="http://"+
siDomain+"/c/=/qzone/v8/index/v6/old_qm_4_module.js,/qzone/biz/vpage/v6/f.js";if(QZONE.FrontPage.isInDressMode())QZFL.imports(url,function(){QZONE.shop.initDressUp();QZONE.FrontPage.toApp(window.location.href);QZONE.qzEvent.addEventListener("QZ_CUSTOM_TOP_TAB_CHANGED",function(a,b){if(b!=1)QZONE.GFP.bootstrap()});if(window.g_app_identifier=="preview")QZONE.GFP.bootstrap()});else{$j.jsonGet("http://"+window.g_Statistic_Domain+"/fcg-bin/cgi_emotion_list.fcg",{uin:window.g_iUin,loginUin:window.g_iLoginUin,
rd:Math.random(),num:3,noflower:1},function(o){ENV.set("visitorData",o)});setTimeout(function(){accessory.bootstrap()},1E3);_report(1,15);QZFL.imports(url,function(){_report(1,16);window.g_app_identifier&&QZONE.FrontPage.toApp(window.location.href);QZONE.GFP.bootstrap();QZONE.shop.initDressUp()})}seajs.use("http://"+siDomain+"/qzone/v8/engine/compatible.js");seajs.use("http://"+siDomain+"/qzone/v8/api/interface/gift4visitor.js");TCISD&&TCISD.pv("home.qzone.qq.com","v8index")}};page.bootstrap();setTimeout(function(){seajs.use(location.protocol+
"//qzonestyle.gtimg.cn/qzone/hybrid/common/security/aq_pc.js")})});
