
var OOP=OOP||{};(function(OOP){'use strict';if(apiInited){return;}
OOP.tpl=OOP.tpl||{};var getByPath=function(obj,path,parma){obj=obj||{};var paths=path.split('.'),len,i;len=paths.length;for(i=0;i<len;i++){obj=obj[paths[i]];if(typeof obj=='function'){obj=obj();}
if(obj===undefined||obj===null){break;}}
return obj;}
OOP.tpl.format=function(tpl,obj){var formatRegex=/\{{([\d\w\.]+)\}}/g,v;return tpl.replace(formatRegex,function(m,n){v=getByPath(obj,n);return v===undefined?'':v;});}})(OOP);var MOOD=MOOD||{};(function(MOOD){'use strict';if(apiInited){return;}
var _seed=0;var get_item_seed=function(){return _seed++;};(function(scope){var cache={};var tmpl=function tmpl(str,data){var fn=!/\W/.test(str)?cache[str]=cache[str]||tmpl(document.getElementById(str).innerHTML):new Function("obj","var p=[],print=function(){p.push.apply(p,arguments);};"+"with(obj){p.push('"+
str.replace(/[\r\t\n]/g," ").replace(/'(?=[^%]*%>)/g,"\t").split("'").join("\\'").split("\t").join("'").replace(/<%=(.+?)%>/g,"',$1,'").split("<%").join("');").split("%>").join("p.push('")+"');}return p.join('');");return data?fn(data):fn;};scope.tmpl=tmpl;})(window);var isInVisibleMode=!QZONE.FP.getQzoneConfig('isOwner')&&QZONE.FP.getUserBitmap(36)==1;var formatTime=function(time){if(typeof time=='string'){return time;}
if(!time){return'';}
var nt;nt=(new Date().getTime()/1000);try{nt=QZONE.FP.getSvrTime().getTime()/1000;}catch(err){}
var ut=time;var vt=nt-ut;if(vt<=0){return'刚刚';}
var date=new Date(ut*1000);var now=new Date(nt*1000);if(vt<60*60*24){if(date.getDate()==now.getDate()){return date.getHours()+":"+(date.getMinutes()>9?date.getMinutes():("0"+""+date.getMinutes()));}else{return"昨天"+date.getHours()+":"+(date.getMinutes()>9?date.getMinutes():("0"+""+date.getMinutes()));}}else{if(vt<60*60*24*2){if(date.getDate()==(new Date(nt*1000-60*60*24*1000-1)).getDate()){return"昨天"+date.getHours()+":"+(date.getMinutes()>9?date.getMinutes():("0"+""+date.getMinutes()));}else{return"前天"+date.getHours()+":"+(date.getMinutes()>9?date.getMinutes():("0"+""+date.getMinutes()));}}else{if(vt<60*60*24*3){if(date.getDate()==(new Date(nt*1000-60*60*24*2*1000-1)).getDate()){return"前天"+date.getHours()+":"+(date.getMinutes()>9?date.getMinutes():("0"+""+date.getMinutes()));}else{return date.getFullYear()+'年'+(date.getMonth()+1)+"月"+date.getDate()+"日";}}else{if((new Date(nt*1000).getFullYear())==date.getFullYear()){return date.getFullYear()+"年"+(date.getMonth()+1)+"月"+date.getDate()+'日';}else{return(date.getFullYear()+"年"+(date.getMonth()+1)+"月"+date.getDate())+'日';}}}}};var ItemDataStorage={};var UserObject=function(data){this.data=QZFL.object.extend(true,{uin:'',nickname:'',who:1},data);this.avatar_tpl=['<div class="ui_avatar">','<a href="{{profile_url}}"  target="_blank" title="{{nickname}}({{uin}})" data-uin="{{uin}}">','<img src="{{avatar_url}}" alt="{{nickname}}({{uin}})">','</a>','</div>'].join('');};UserObject.prototype.getUin=function(){return escHTML(this.data.uin+'');};UserObject.prototype.getName=function(){return escHTML(this.data.nickname+'');};UserObject.prototype.getProfileURL=function(){var url='';var data={nickname:this.getName()||this.getUin(),uin:this.getUin(),who:this.data.who};switch(this.data.who){case 3:url=format('http://rc.qzone.qq.com/myhome/weibo/profile/{uin}',data);break;case 2:url=format('http://www.pengyou.com/index.php?mod=profile&u={uin}&adtag=from_profile',data);break;default:url=format('http://user.qzone.qq.com/{uin}',data);break;}
return url;};UserObject.prototype.getAvatarURL=function(size,tpl){if(window.QZONE&&QZONE.FP&&QZONE.FP.getPURL){return QZONE.FP.getPURL(this.data.uin,size||100);}
tpl='http://qlogo{{host}}.store.qq.com/qzone/{{uin}}/{{uin}}/{{size}}'||tpl;var isQzone=(document.domain=="qq.com");if(!isQzone){tpl='http://py.qlogo.cn/friend/{{uin}}/audited/60'||tpl;}
return OOP.tpl.format(tpl,{uin:this.data.uin,size:size||100,host:this.data.uin%4||1});};UserObject.prototype.getProfileLink=function(noAtChar){var USERTPL='<a href="{url}" target="_blank" class="qz_311_author nickname" data-uin="{uin}">'+(noAtChar?'':'@')+'{parsedNickname}</a>';var data={parsedNickname:QZONE.FP.removeUBB(this.getName()||this.getUin()),nickname:this.getName()||this.getUin(),uin:this.getUin(),who:this.data.who,url:this.getProfileURL()};return format(USERTPL,data);};UserObject.prototype.getUserLink=function(){var USERTPL='<a href="{url}" onclick="return false;"  class="qz_311_author c_tx nickname goProfile" profileUin="{uin}" profilePft="{who}" data-uin="{uin}">{parsedNickname}</a>';var data={parsedNickname:QZONE.FP.removeUBB(this.getName()||this.getUin()),nickname:this.getName()||this.getUin(),uin:this.getUin(),who:this.data.who,url:this.getProfileURL()+(this.data.who==1?'/mood':'')};return format(USERTPL,data);};UserObject.prototype.getAvatarLink=function(size){var data={nickname:this.getName()||this.getUin(),uin:this.getUin(),who:this.data.who,avatar_url:this.getAvatarURL(size),profile_url:this.getProfileURL()};return OOP.tpl.format(this.avatar_tpl,data);};UserObject.prototype.toJSON=function(){return QZFL.object.extend(true,{},this.data);};var MoodModel=function MoodModel(mood){this.data=QZFL.object.extend(true,{},mood);if(this.data.rt_con&&this.data.rt_con.conlist){this.data.rtitem={};this.data.rtitem.rich_info=this.data.pic;this.data.rtitem.created_time=this.data.rt_created_time;this.data.rtitem.createTime=this.data.rt_createTime;this.data.rtitem.nosrc=this.data.rt_nosrc;this.data.rtitem.rt_account=this.data.rt_account;this.data.rtitem.wbid=this.data.rt_wbid;this.data.rtitem.t1_source=this.data.rt_source;this.data.rtitem.t1_subtype=this.data.rt_subtype;this.data.rtitem.source_name=this.data.rt_source_name;this.data.rtitem.source_url=this.data.rt_source_url;this.data.rtitem.rt_sum=this.data.rt_sum;this.data.rtitem.tid=this.data.rt_tid;this.data.rtitem.uin=this.data.rt_uin;this.data.rtitem.name=this.data.rt_uinname;this.data.rtitem.conlist=this.data.rt_con.conlist;this.data.rtitem.content=this.data.rt_con.content;this.data.rtitem.cmtnum=this.data.rt_cmtnum;this.data.rtitem.has_more_con=this.data.rt_has_more_con;this.data.rtitem.long_article=this.data.rt_long_article;}
this.data.commentlist=this.data.commentlist||[];this.cmc=new CommentModelCollection(this.data.commentlist||{});this.seed=get_item_seed();ItemDataStorage[this.data.tid||('item-'+this.seed)]=this;};MoodModel.prototype.getText=function(opts){opts=QZFL.object.extend({emoji:true,hashtag:true,link:true},opts);var conlist=this.data.conlist||[];var i,item,r;var text=[];for(i=0;i<conlist.length;i++){item=conlist[i];switch(item.type){case 0:text.push('@'+escHTML(item.nick));break;case 1:if(opts.link){text.push(escHTML(item.url));}
break;case 2:text.push(escHTML(item.con));break;}}
r=text.join('');if(!opts.emoji){r=r.replace(/\[em\]e(\d{1,8})\[\/em\]/ig,'');}
if(!opts.hashtag){r=r.replace(/#((?:.|<br\/>)+?)#/ig,'');}
r=r.replace(/^[\s\xA0]+/,'').replace(/[\s\xA0]+$/,'');return r;};MoodModel.prototype.replaceEmoticon=function(str,shouldShowEmoticon){if(shouldShowEmoticon){return QZONE.FP.removeUBB(str);}else{return str.replace(/\[em\]e(\d{1,8})\[\/em\]/ig,'');}};MoodModel.prototype.processRichContent=function(str){str=(str||'')+'';var mentionPattern=/(?:@\{uin:([^\}]*),nick:([^\},]*)(?:,who:(\d+))?\})|[^@]+/g;var metionDecodingMap={'%7D':'}','%2C':',','%25':'%'};var decodeMention=function(content){if(content){for(var i in metionDecodingMap){content=content.replace(i,metionDecodingMap[i]);}}
return content;}
var xSplit=function(oString,_regEx){if('a~b'.split(/(~)/).length===3){return oString.split(_regEx);}
if(!_regEx.global){_regEx=new RegExp(_regEx.source,'g'+(_regEx.ignoreCase?'i':''));}
var m,str='',arr=[];var i,len=oString.length;for(i=0;i<len;i++){str+=oString.charAt(i);m=str.match(_regEx);if(m){arr.push(str.replace(m[0],''));arr.push(m[0]);str='';}}
if(str!='')arr.push(str);return arr;}
var tags=xSplit(str,/(#(?:.|<br\/>)+?#)/g);var _content='',tag='',_tagcon,_mencon,_doneTag,_doneMention,mentions,mention;for(var i=0;i<tags.length;i++){tag=tags[i];_doneTag=false;_tagcon='';_mencon='';_tagcon=tag.replace(/#((?:.|<br\/>)+?)#/g,function(a,b,c){_doneTag=true;var icon='';icon='<a href="http://rc.qzone.qq.com/qzonesoso/?search='+encodeURIComponent(b)+'&entry=99&businesstype=mood" target="_blank">#'+escHTML(b)+'#</a>';return icon;});if(!_doneTag){_tagcon='';mentions=tag.split(/(@(?!^\{)[\{]uin\:[a-z\d]+\,nick\:[^}]*[\}])/g);for(var j=0;j<mentions.length;j++){mention=mentions[j];_doneMention=false;mention=mention.replace(mentionPattern,function($0,uin,nick,platform){nick=decodeMention(nick);if(uin){_doneMention=true;return format('@<a title="{uin}" target="_blank" href="http://user.qzone.qq.com/{uin}" class="c_tx">{name}</a>',{uin:escHTML(uin),name:escHTML(nick)});}
return escHTML($0);});if(!_doneMention){mention=mention.replace(/((?:https|ftp|http):\/\/[-A-Z0-9+&@#\/%?=~_|!:,.;]*[-A-Z0-9+&@#\/%=~_|])/ig,'<a href=\"$1\" target=\"_blank\">$1</a>');}
_mencon=_mencon+mention;}
_tagcon=_mencon;}
_content=_content+_tagcon;}
return _content;};MoodModel.prototype.replaceTopic=function(s){s=restHTML(s);return this.processRichContent(s);};MoodModel.prototype.getHTML=function(opts){if(this.data.right>1){return'更新了说说';}
opts=QZFL.object.extend({emoji:true,hashtag:true,link:true,wrapper:true},opts);var HTMLTPL='<div class="qz_311_content">{content}</div>';var MENTIONTPL='<a href="{url}" target="_blank" class="qz_311_mention nickname">@{nickname}</a>';var URLTPL='<a href="{url}" target="_blank" class="qz_311_url">{text}</a>';var HASHTAGTPL='<a href="http://rc.qzone.qq.com/qzonesoso/?search={keyword}&entry=99&businesstype=mood" target="_blank" class="c_tx qz_311_hashtag">{name}</a>';var conlist=this.data.conlist||[];var i,item,r;var text=[];var linkCount=0;for(i=0;i<conlist.length;i++){item=conlist[i];switch(item.type){case 0:switch(item.who){case 3:item.url=format('http://rc.qzone.qq.com/myhome/weibo/profile/{uin}',item);break;case 2:item.url=format('http://www.pengyou.com/index.php?mod=profile&u={uin}&adtag=from_profile',item);break;default:item.url=format('http://user.qzone.qq.com/{uin}',item);break;}
item.nickname=QZONE.FP.removeUBB(escHTML(item.nick));text.push(format(MENTIONTPL,item));break;case 1:linkCount++;if(opts.link){item.url=escHTML(item.url);item.text=this.getURLTitle(linkCount)||item.url;text.push(format(URLTPL,item));}
break;case 2:if(item.con){text.push(this.replaceEmoticon(this.replaceTopic(item.con),opts.emoji));}
break;}}
r=text.join('');r=r.replace(/^[\s\xA0]+/,'').replace(/[\s\xA0]+$/,'');if(r.length===0){r=this.replaceEmoticon(this.replaceTopic(this.data.content),opts.emoji);}
if(opts.wrapper){r=format(HTMLTPL,{content:r});}
return r;};MoodModel.prototype.getMedia=function(){var HTMLTPL='<div class="qz_311_media">{media}</div>';var PHOTOTPL='<img src="{url1}" class="qz_311_photo" data-meta=""/>';var VIDEOTPL='<img src="{vimg}" class="qz_311_video" data-meta=""/>';var r='',i,media;var medias=this.data.rich_info||[];var html=[];for(i=0;i<medias.length;i++){media=medias[i];switch(media.type){case 1:html.push(format(PHOTOTPL,media));break;case 3:html.push(format(VIDEOTPL,media));break;}}
if(medias.length>0){r=format(HTMLTPL,{media:html.join('')})}
return r;};MoodModel.prototype.getFullContent=function(){return this.getHTML()+this.getMedia();};MoodModel.prototype.getCreatedTime=function(){return formatTime(this.data.created_time)||this.data.createTime;};MoodModel.prototype.getTimestamp=function(){return this.data.create_time;};MoodModel.prototype.getType=function(){var r='original';if(this.data.isSignIn==1){r='sign'}
var medias=this.data.rich_info||[];var i;for(i=0;i<medias.length;i++){switch(medias[i].type){case 1:r='photo';break;case 2:r='video';break;}}
if(this.data.rtitem||this.data.rt_con){r='retweet';}
return r;};MoodModel.prototype.getSubType=function(){};MoodModel.prototype.getCommentCount=function(){return this.data.replies||this.data.reply_num||this.data.cmtnum||0;};MoodModel.prototype.getRTCount=function(){if(this.data.rtitem){return this.data.rtitem.rt_sum||0;}
return this.data.rt_sum||0;};MoodModel.prototype.getForwardNum=function(){if(this.data.rtitem){return this.data.fwdnum||0;}
return this.data.rt_sum||0;};MoodModel.prototype.getUserData=function(){var data={who:this.data.nosrc==1?3:1,uin:this.data.nosrc==1?this.data.rt_account:(this.data.owneruin||this.data.uin||(this.data.owner&&this.data.owner.uin)),nickname:this.data.ownername||this.data.name||(this.data.owner&&this.data.owner.name)};if(document.domain!='qq.com'){data.who=2;}
if(this.data.wc_uin&&this.data.wc_uin!=''){data.who=2;data.uin=this.data.wc_uin;}
return data;};MoodModel.prototype.getAuthor=function(){var data=this.getUserData();var user=new UserObject(data);return user;};MoodModel.prototype.getUserLink=function(){var data=this.getUserData();var user=new UserObject(data);return user.getProfileLink();};MoodModel.prototype.getBroadcast=function(opts){opts=QZFL.object.extend({retweets:true,origin:false},opts);var HTMLTPL='<div class="qz_311_content">{content}</div>';var RTHTMLTPL='<div class="qz_311_rtcontent">{content}</div>';var item,items,i,m;var html=[],retweet=[];if(this.data.rt_con){retweet.push(this.getHTML({wrapper:false}));if(this.data.rtlist&&opts.retweets){items=this.data.rtlist||[];for(i=items.length-1;i>=0;i--){item=QZFL.object.extend({},items[i]);m=new MoodModel(item);retweet.push(format('{user}: {content}',{user:m.getUserLink(),content:m.getHTML({wrapper:false})}));}}
html.push(format(HTMLTPL,{content:retweet.join(' || ')}));if(opts.origin){m=new MoodModel(this.data.rtitem);html.push(format(RTHTMLTPL,{content:m.getFullContent()}));}}
return html.join('');};MoodModel.prototype.getURLTitle=function(index){return this.data['url_title_'+index]||'';};MoodModel.prototype.getTid=function(){return this.data.tid;};MoodModel.prototype.getRTTid=function(){return this.data.rt_tid||'';};MoodModel.prototype.getUin=function(){return this.data.owneruin||this.data.uin||'';};MoodModel.prototype.getRTUin=function(){return this.data.rt_uin||'';};MoodModel.prototype.getRTMood=function(){if(this.data.rtitem){return new MoodModel(this.data.rtitem);}};MoodModel.prototype.getPhotosSync=function(){if(this.data.pictotal>0){var items=[],obj,item;this.data.pic=this.data.pic||[];for(var i=0;i<this.data.pic.length;i++){obj=this.data.pic[i];if(obj.hd_pic){item={pre:(obj.smallurl||'').replace('qp.qq.com','p.qpimg.cn'),origin:(obj.big_pic||'').replace('qp.qq.com','p.qpimg.cn'),big_pic:(obj.big_pic||'').replace('qp.qq.com','p.qpimg.cn'),big_width:obj.big_width,big_height:obj.big_height,hd_pic:(obj.hd_pic||'').replace('qp.qq.com','p.qpimg.cn'),hd_width:obj.hd_width,hd_height:obj.hd_height,tid:this.data.tid,uin:this.data.uin,pic_id:obj.pic_id,index:i};}else{item={pre:(obj.smallurl||'').replace('qp.qq.com','p.qpimg.cn'),origin:(obj.url2||'').replace('qp.qq.com','p.qpimg.cn'),big_pic:(obj.url3||'').replace('qp.qq.com','p.qpimg.cn'),big_width:obj.b_width||obj.width,big_height:obj.b_height||obj.height,tid:this.data.tid,uin:this.data.uin,pic_id:obj.pic_id,index:i};}
items.push(item);}
return items;}
return[];};MoodModel.prototype.getPhotos=function(callback){var self=this;if(!this._photos){var data={tid:this.data.tid,uin:this.data.owneruin||this.data.uin,plattype:this.data.t1_source,success:function(o){callback(o);self._photos=o;}};_get_photos(data);}else{callback(this._photos);}};MoodModel.prototype.getVoiceList=function(){if(this.data.voice){var d=[];var voice=this.data.voice||[];for(var i=0,item;i<voice.length;i++){d.push({id:voice[i].id,time:voice[i].time,url:voice[i].url});}
return d;}
return;}
MoodModel.prototype.getPlatformType=function(){return this.data.t1_source;};MoodModel.prototype.getRTPlatformType=function(){return this.data.rt_source;};MoodModel.prototype.getLikeKeys=function(picIndex){var isPic=typeof picIndex=='number'?true:false;var isEmotion=false;if(isPic){var pic=this.data.pic[picIndex];var isEmotion=(pic.url1.indexOf('qzone/em/recommendedImages')!=-1)?true:false;var keys={key:pic.curlikekey||pic.unilikekey,uniKey:pic.unilikekey,curKey:pic.curlikekey};if(!isEmotion)return keys;}
var uniKey='';var curKey='';var item=this.data;var isSinglePic=item.pictotal==1?true:false;if(isSinglePic){var unilikekey=item.pic[0].unilikekey;var curlikekey=item.pic[0].curlikekey;}
if(item.rt_tid&&item.rt_nosrc){uniKey=['http://user.qzone.qq.com/119/mood/',item.rt_tid,'.',item.rt_source].join('');curKey=['http://user.qzone.qq.com/',item.uin,'/mood/',item.tid,'.',item.t1_source].join('');}else if(item.rt_tid){uniKey=['http://user.qzone.qq.com/',item.rt_uin,'/mood/',item.rt_tid,'.',item.rt_source].join('');curKey=['http://user.qzone.qq.com/',item.uin,'/mood/',item.tid,'.',item.t1_source].join('');}else if(isSinglePic&&!isEmotion&&(unilikekey||curlikekey)){uniKey=unilikekey||curlikekey;curKey=curlikekey||unilikekey;}else{uniKey=['http://user.qzone.qq.com/',item.uin,'/mood/',item.tid,'.',item.t1_source].join('');curKey=uniKey;}
var keys={key:['http://user.qzone.qq.com/',this.data.owneruin||this.data.uin,'/mood/',this.data.tid].join(''),uniKey:uniKey,curKey:curKey};return keys;};MoodModel.prototype.getCommentsHTML=function(){return this.cmc.getHTML();};MoodModel.prototype.getComments=function(opts){opts=QZFL.object.extend({max_comments_count:-1,max_replies_count:-1,order:'asc',callback:function(){}},opts);this.cmc.setConfig(opts);opts.callback(this.cmc);};MoodModel.prototype.setConfig=function(opts){opts=opts||{};this.cmc.setConfig(opts.comment||{});};MoodModel.prototype.getPermalink=function(){if(this.data.nosrc==1){return'http://rc.qzone.qq.com/myhome/weibo/agg/'+this.data.wbid;}
return['http://user.qzone.qq.com/',this.data.owneruin||this.data.uin,'/mood/',this.data.tid,'.',this.data.source||this.data.t1_source].join('');};MoodModel.prototype.getStoryInfo=function(){if(!this.data.story_info||!this.data.story_info.time||!this.data.story_info.lbs){return'';}
return['<div class="md">','<div>',(this.data.story_info&&this.data.story_info.time)?('拍摄于 '+formatTime(this.data.story_info.time)):'',' '+(this.data.story_info&&this.data.story_info.lbs&&(this.data.story_info.lbs.idname||this.data.story_info.lbs.name)),'</div>','</div>'].join('');};MoodModel.prototype.getSourceName=function(){return this.data.source_name;};MoodModel.prototype.getSourceHTML=function(){if(document.domain!="qq.com"&&(this.data.source_name=='QQ空间'||this.data.source_name=='朋友网')){return'';}
if(!this.data.source_name&&!this.data.t1_source_name){return'';}
if(this.data.source_url){var sourceData={source_name:escHTML(this.data.source_name),formated_source_name:QZONE.FP.removeUBB(getRealLen(this.data.source_name)>20?escHTML(cut(this.data.source_name,18,'..')):this.data.source_name),source_url:this.data.source_url};if(this.data.source_name.indexOf('话题圈')>-1){sourceData={source_name:'话题圈',formated_source_name:QZONE.FP.removeUBB(this.data.source_name),source_url:this.data.source_url}}
return OOP.tpl.format('<span class="c_tx3">来自<a href="{{source_url}}" target="_blank" title="{{source_name}}"">{{formated_source_name}}</a></span>',sourceData);}
return'<span class="c_tx3">来自<span class="custom-tail" title="'+escHTML(this.data.source_name||this.data.t1_source_name)+'">'+escHTML(this.data.source_name||this.data.t1_source_name)+'</span></span>';};MoodModel.prototype.getLocationHTML=function(){var lbs=this.data.lbs;var tpl=['','<a href="javascript:void(0);" class="c_tx viewmap icon-location" data-location="{{pos_x}},{{pos_y}}" title="点击查看地图">','<i class="icon-location"></i>','</a>',''].join('');if(lbs&&lbs.pos_x&&lbs.pos_y){return OOP.tpl.format(tpl,{name:escHTML(lbs.name),pos_x:escHTML(lbs.pos_x),pos_y:escHTML(lbs.pos_y)});}
return'';};MoodModel.prototype.toJSON=function(opts){var r={content:this.data.content,seed:this.seed,tid:this.data.tid,uin:this.data.uin,tags:this.data.tags,mood_type:this.getTypeHTML(),voice_html:this.getVoiceHTML(),op_button_html:this.getButtonHTML(),content_html:this.getHTML({wrapper:false}),media_preview_html:this.getMediaPreviewHTML(),feed_private_style:this.data.ugc_right==64?'feed_private':'',has_right_style:this.data.right>1?'none':'',nickname:this.getAuthor().getName(),user_link:this.getAuthor().getUserLink(),avatar_url:this.getAuthor().getAvatarURL(),profile_url:this.getAuthor().getProfileURL(),created_time:this.getCreatedTime(),comment_module:this.getCommentModuleHTML(),mod_comments:this.getCommentsHTML(),comment_count:this.getCommentCount()||0,comment_count_html:(function(cmtCount){if(isInVisibleMode){return'评论';}
return cmtCount?'评论('+cmtCount+')':'评论'})(this.getCommentCount()),retweet_count:this.getRTCount()||0,retweet_count_html:(function(forwardCount){if(isInVisibleMode){return'转发';}
return forwardCount?'转发('+forwardCount+')':'转发'})(this.getRTCount()),source_html:this.getSourceHTML(),source_name:this.getSourceName(),info_html:this.getInfoHTML(),apply_access_html:this.getApplyAccessHTML(),location_html:this.getLocationHTML(),story_info:this.getStoryInfo(),permalink:this.getPermalink(),private_show:this.data.ugc_right==64?'':'none',ellipsis:this.data.has_more_con==1?'......':'',more_words:this.data.has_more_con==1?'展开查看全文':'',more_active:''};if(this.data.long_article){r.more_words='收起';r.more_active='more_active';}
if(this.getRTMood()){r['media_preview_html']=this.getRTHTML();r['voice_html']='';}
return r;};MoodModel.prototype.getRTButtonHTML=function(){var mood=this.getRTMood();if(mood){var tpl=['<div class="op">','<a href="javascript:void(0);" class="c_tx mouseOver none">举报</a>','<a href="{{permalink}}#action=comment" class="c_tx rt_comment_btn" target="_blank" onclick="return false;">{{comment_count_html}}</a>','<a href="{{permalink}}#action=forward" class="c_tx rt_forward_btn" target="_blank" onclick="return false;">{{retweet_count_html}}</a>','</div>'].join('');var no_src_tpl=['<div class="op">','<a href="javascript:void(0);" class="c_tx mouseOver none">举报</a>','<a href="{{permalink}}#action=comment" class="c_tx" target="_blank" >{{comment_count_html}}</a>','<a href="{{permalink}}#action=forward" class="c_tx" target="_blank" >{{retweet_count_html}}</a>','</div>'].join('');var r=mood.toJSON();return OOP.tpl.format(mood.data.nosrc?no_src_tpl:tpl,r);}
return'';};MoodModel.prototype.getRTHistoryHTML=function(){var rtlist=this.data.rtlist;if(rtlist){var tpl=['<div class="chain c_tx3">','{{retweet_list}}','</div>'].join('');var userRT=new Object();var lists=new Array();var words='';var uHtml='<a href="javascript:void(0);" onclick="return false;" target="_blank" class="c_tx goProfile" profileUin="{{uin}}">{{name}}</a>';for(var i=0;i<rtlist.length;i++){var item=rtlist[i];var line=new Object();line[item.uin]=item;QZFL.object.extend(userRT,line);}
for(var index in userRT){var li=userRT[index];if(li.uin==QZONE.FP.getQzoneConfig("loginUin")){lists.unshift('我');}else{lists.push(OOP.tpl.format(uHtml,{uin:li.uin,name:escHTML(li.name)}));}}
for(var i=0;i<lists.length;i++){if(i==lists.length-1){var extra_word='';}else if(lists[0]=='我'){var extra_word=i==0?'和':'、';}else{var extra_word=i==lists.length-2?'和':'、';}
words+=lists[i]+extra_word;}
return OOP.tpl.format(tpl,{retweet_list:words+'也转发过'});}
return'';};MoodModel.prototype.getRTHTML=function(){var mood=this.getRTMood();if(mood){var tpl=['<div class="md rt_content"><div class="quote bor2">','<div class="bd">','{{user_link}} <pre style="display:inline;">{{content_html}}</pre><span>{{ellipsis}}</span>','<div class="f_toggle">','<a href="javascript:void(0);" onclick="return false;" class="rt_has_more_con {{more_active}}">{{more_words}}</a>','</div>','{{voice_html}}','</div>','{{media_preview_html}}','<div class="ft">','<div class="info">','<span class="c_tx3"><a href="{{permalink}}" onclick="return false" isroot="1" class="c_tx c_tx3 goDetail" title="{{created_time}}" data-timestamp={{createTime}}>{{created_time}}</a></span>','{{source_html}}','</div>','{{rt_op_button_html}}','</div>','{{rt_history_html}}','</div></div>'].join('');var r=mood.toJSON();r['media_preview_html']=this.getMediaPreviewHTML();r['voice_html']=this.getVoiceHTML();r.rt_op_button_html=this.getRTButtonHTML();r.rt_history_html=this.getRTHistoryHTML();return OOP.tpl.format(tpl,r);}
return'';};MoodModel.prototype.getMediaPreviewHTML=function(){var tpl=['<div class="md">','{{video_thumb_html}}','{{pic_thumb_html}}','{{audio_thumb_html}}','{{magic_thumb_html}}','{{attach_thumb_html}}','{{vote_thumb_html}}','<div class="md_op {{extend_status}}" data-extend="" >','<a href="#fold" class="md_unfold {{operate_type}}" data-tips="{{extend_tips}}" data-topmedia="{{topmedia}}" >','{{extend_tips}} 查看详情','<i class="ico_arr"><b></b></i>','</a>','</div>','</div>'].join('');var meida_id_list=['video','pic','audio','magic','attach','vote'];var media_list={'video':{'bitmap':3,'name':'视频','status':0},'pic':{'bitmap':1,'name':'图片','status':0},'audio':{'bitmap':7,'name':'音乐','status':0},'magic':{'bitmap':6,'name':'动画','status':0},'attach':{'bitmap':5,'name':'附件','status':0},'vote':{'bitmap':4,'name':'投票','status':0}};var obj=this.data;var used_list=[];if(obj.attach_type){var attachBitmap=obj.attach_type.toString(2);var bitmapLen=16;attachBitmap=new Array(bitmapLen-attachBitmap.length+1).join('0')+attachBitmap;for(var i=0,field;i<meida_id_list.length;i++){field=meida_id_list[i];var fieldBitmapIndex=media_list[field]['bitmap'];if(attachBitmap.charAt(bitmapLen-fieldBitmapIndex)==1){used_list.push(field);media_list[field]['status']=1;}}}else{for(var i=0,field;i<meida_id_list.length;i++){field=meida_id_list[i];if(obj[field]){used_list.push(field);media_list[field]['status']=1;}}}
var extend_tips='内包含';var extend_status='none';var topmedia='';for(var i=0,field;i<used_list.length;i++){field=used_list[i];if(used_list.length-1==i){extend_tips=extend_tips+'和'+media_list[field]['name'];}else if(i==0){extend_tips=extend_tips+media_list[field]['name'];}else{extend_tips=extend_tips+'、'+media_list[field]['name'];}}
if(used_list.length<2){extend_tips='';}else{topmedia=used_list[0];extend_status='';}
var data={extend_status:extend_status,extend_tips:extend_tips,topmedia:topmedia,operate_type:obj.attach_type?'goDetail':' js_collapse'};for(var i=0,field,config;i<used_list.length;i++){field=used_list[i];config={};if(i>0){config={'className':'none'};}
var html='';switch(field){case'video':html=this.getVideoThumbHTML(config);break;case'pic':html=this.getPhotoThumbHTML(config);break;case'audio':html=this.getMusicThumbHTML(config);break;case'magic':html=this.getMagicHTML(config);break;case'attach':html=this.getAttachHTML(config);break;case'vote':html=this.getVoteHTML(config);break;}
data[field+'_thumb_html']=html;}
return OOP.tpl.format(tpl,data);};MoodModel.prototype.getVoteHTML=function(opt){if(!this.data.vote){return'';}
opt=opt||{};var tpl=['<div class="vote vote_box bg bor3 smallVote">','<ul class="vote_box_list">','<%for(var i=0; i<vote.options.length; ++i){%>','<li>','<input type="<%if(vote.limit == 1){%>radio<%}else{%>checkbox<%}%>" class="input_chkrad"><label class="bg2"><%=vote.options[i]%></label>','</li>','<%}%>','</ul>','<%if(vote.num > 3){%>','<p class="vote_box_more bg2"><a href="javascript:void(0);" onclick="return false;" class="c_tx">更多<%=vote.num-3%>项↓</a></p>','<%}%>','</div>'].join('');return tmpl(tpl,this.data);};MoodModel.prototype.getAttachHTML=function(opt){opt=opt||{};var tpl=['<div title="点击查看附件" class="feeds_attach bor bg3 smallAttach {{className}}>">','<div class="feeds_attach_icon rbor bg2"></div>','<div class="feeds_attach_content ">','<a href="javascript:void(0);" onclick="return false;" class="c_tx attach_name">{{name}}</a>','</div>','</div>'].join('');var attach=this.data.attach;var html=[];if(attach){attach.className=opt.className;attach.name=escHTML(attach.name);html.push(OOP.tpl.format(tpl,attach));}
return html.join('');};MoodModel.prototype.getMagicHTML=function(opt){opt=opt||{};var tpl=['<div class="magic {{className}}">','<img src="/ac/b.gif" data-id={{id}} onload="var _img = this; MOOD.util.require(\'attachmentThumbnail\', function(ATF) { var $atf = new ATF; $atf.resInfo = null; $atf.resInfo={\'$type\':\'magicEmoticon\',\'id\': _img.getAttribute(\'data-id\')};$atf.renderAt(_img); _img = null; });" />','</div>'].join('');var magic=this.data.magic||[];var html=[];var magicPattern=/{"\$type":"magicEmoticon","id":(\d+)}/;for(var i=0;i<magic.length;i++){var magicId;try{magicId=magic[i].url1.match(magicPattern)[1];}catch(err){}
if(magicId){magic[i].id=escHTML(magicId);magic[i].className=opt.className;html.push(OOP.tpl.format(tpl,magic[i]));}}
return html.join('');};MoodModel.prototype.getVoiceHTML=function(opt){var tpl=['<div class="qz_shuoshuo_audio js_play_record ','qz_shuoshuo_audio_{{size}} js-voice-hover bor_bg6" data-id="{{id}}" data-time="{{time}}">','<div class="shuoshuo_audio_inner bg_bor2" style="width:0%">','<div class="audio_icon">','<b class="icon_play bor_bg6"></b>','<b class="icon_pause">','<span class="icon_pause_left bor_bg6"></span>','<span class="icon_pause_right bor_bg6"></span>','</b>','</div>','<div class="audio_time">','<span class="c_tx2">{{time}}"</span>','</div>','</div>','</div>'].join('');var audio_size=function(time){if(time>=40)return'XXL';if(time>25)return'XL';if(time>15)return'L';if(time>5)return'M';return'S';};var html=[];var voice=this.data.voice||[];for(var i=0,item;i<voice.length;i++){item=voice[i];item.size=audio_size(item.time);html.push(OOP.tpl.format(tpl,item));}
return html.join('');};MoodModel.prototype.getPhotoThumbHTML=(function(){var CLASS_MAP={1:'imgscale-big',2:'imgscale-middle',3:'imgscale-small',4:'imgscale-middle',5:'imgscale-small',6:'imgscale-small',7:'imgscale-small',8:'imgscale-small',9:'imgscale-small'};var SIZE_MAP={1:'400,300',2:'200,200',3:'128,128',4:'200,200',5:'128,128',6:'128,128',7:'128,128',8:'128,128',9:'128,128'};var TPL_MAP={'tpl-2-2':2,'tpl-2-3':2,'tpl-3-2':3,'tpl-3-3':3,'tpl-4-2':4,'tpl-4-3':4,'tpl-4-4':4,'tpl-4-5':4,'tpl-5-2':5,'tpl-5-3':5,'tpl-5-4':5,'tpl-6-2':6,'tpl-6-3':6,'tpl-6-4':6,'tpl-6-5':6,'tpl-7-2':7,'tpl-7-3':7,'tpl-8-2':8,'tpl-8-3':8,'tpl-8-4':8,'tpl-9-2':9,'tpl-9-3':9,'tpl-9-4':9,'tpl-9-5':9}
var MAX_COUNT=9;var CON_TPL='<div class="img-attachments img_thumb {{className}}"><div class="img-attachments-inner clearfix">{{photo_list}}</div></div>';var fixUrl=function(url){var fixedUrl=escHTML(url.replace(/\/[acmboi]\//ig,'/c/').replace('qp.qq.com','p.qpimg.cn'));if(fixedUrl.indexOf('http://')!==0){fixedUrl='http://'+fixedUrl;}
return fixedUrl;};var getGridHtml=function(opt){if(!this.data.pictotal){return'';}
opt=opt||{};var html='';var showCount=Math.min(this.data.pic.length,MAX_COUNT);var className=(opt.className||'')+' '
+CLASS_MAP[showCount]
+' smallPic'
+' pic';for(var i=0;i<showCount;i++){var item=this.data.pic[i];item.url1=fixUrl(item.url1);item.index=i;var tpl='<a href="{{url1}}" title="查看大图">'+'<img oncontextmenu="this.src=this.src.replace(&#39;&t=5&#39;,&#39;&#39;);this.oncontextmenu=null" src="/qzone/app/mood_v6/images/blank.gif" pic-index="{{index}}" data-src="{{url1}}" data-isphoto="1" class="lazyload" data-limit="'+SIZE_MAP[showCount]+'"/>'+
(item.pictype==2?'<span class="gif-flag"></span>':'')+'</a>';html+=OOP.tpl.format(tpl,item);}
html+=this.data.pictotal>MAX_COUNT?'<a href="javascript:;" class="see-all"><span>查看全部'+this.data.pictotal+'张照片</span></a>':'';return OOP.tpl.format(CON_TPL,{'photo_list':html,'className':className});};var countPic=function(){var picCount=0;for(var i=0;this.data.pic&&i<this.data.pic.length;i++){if(this.data.pic[i].richsubtype!=2&&this.data.pic[i].richsubtype!=7){picCount++;}}
return picCount;}
var getTypeSetHTML=function(opt){var pic_template=(this.data.pic_template||'');var template=['<div class="tpl-item smallPic <%=tplClass%>">','<ul>','<%for(var i=0;i<pics.length;i++){%>','<li class="img-item-<%=i+1%>">','<a href="<%if(pics[i].url1.indexOf(\'http://\')!==0){%>http://<%}%><%=escHTML(pics[i].url1)%>" title="查看大图"><img oncontextmenu="this.src=this.src.replace(&#39;&t=5&#39;,&#39;&#39;);this.oncontextmenu=null" src="/ac/b.gif" data-isphoto="1" pic-width="<%=escHTML(pics[i].b_width)%>" pic-height="<%=escHTML(pics[i].b_height)%>" pic-index="<%=i%>" class="typeset-lazyload" data-bigsrc="<%if(pics[i].url3.indexOf(\'http://\')!==0){%>http://<%}%><%=escHTML(pics[i].url3)%>" data-midsrc="<%if(pics[i].url2.indexOf(\'http://\')!==0){%>http://<%}%><%=escHTML(pics[i].url2)%>" data-src="<%if(pics[i].url1.indexOf(\'http://\')!==0){%>http://<%}%><%=escHTML(pics[i].url1)%>" >','<span class="gif-flag <%if(pics[i].pictype!=2){%>none<%}%>"></span>','</a>','</li>','<%}%>',' </ul>','<%=showAllLinkHTML%>',' </div>'].join('');var pics=[];for(var i=0;this.data.pic&&i<this.data.pic.length;i++){if(this.data.pic[i].richsubtype!=2&&this.data.pic[i].richsubtype!=7){pics.push(this.data.pic[i]);}}
try{return tmpl(template,{tplClass:pic_template,pics:pics,showAllLinkHTML:countPic.call(this)!=this.data.pictotal?'<a href="javascript:;" class="see-all" pic-index="0"><span pic-index="0">查看全部'+this.data.pictotal+'张照片</span></a>':''});}catch(err){window.console&&console.log('[ERR] 生成排版模版时出错：',err.message);}
return'';};return function(opt){return(this.data.pic_template&&TPL_MAP[this.data.pic_template]&&TPL_MAP[this.data.pic_template]==countPic.call(this))?getTypeSetHTML.call(this,opt):getGridHtml.call(this,opt)}})();MoodModel.prototype.getVideoThumbHTML=function(opt){opt=opt||{};var r=[];var item_tpl=['<div class="video {{className}}" data-video="{{id}}">','<span class="video_wrap smallVideo js-small-video">','<a href="javascript:void(0);" onclick="return false;">','<span class="play_op"></span>','<img alt="视频缩略图" src="/qzone/app/mood_v6/images/blank.gif" width="400" data-src="{{url1}}" data-limit="400,300" class="lazyload">','</a>','</span>','</div>'].join('');if(this.data.videototal>0){var i,video=this.data.video||[];for(i=0;i<video.length;i++){video[i].id=i;video[i].className=opt.className;r.push(OOP.tpl.format(item_tpl,video[i]));}}else{return'';}
return r.join('');};MoodModel.prototype.getMusicThumbHTML=function(opt){opt=opt||{};var tpl=['<div class="music_wrap bor3 bg audio {{className}}">','<div class="music_item">','<a class="img" href="http://music.qq.com/musicbox/html/music.html?songid={{id}}" target="_blank">','<img data-src="{{albumthumb}}" src="/qzone/app/mood_v6/images/blank.gif" class="lazyload">','<span class="tip icon_music_sign"></span>','</a>','<div class="info c_tx">','<p class="name">','<a href="javascript:void(0);" target="_blank">{{formatedName}}</a>','</p>','<p class="singer">{{singername}}</p>','</div>','<div class="op">','<a class="btn_play c_tx bor2 bg js_play_audio" href="javascript:void(0);">','<b class="trig c_tx"></b>','</a>','</div>','</div>','<div class="player_holder none">','<a class="c_tx js_hide_audio" href="javascript:void(0);">收起</a>','<div class="flash_holder" id="qzshare_music_box-{{tid}}"></div>','</div>','<div class="extra c_tx3 none">','<span class="ui_mr10 qz_orgin_cnt" cnttype="share"></span>','</div>','</div>'].join('');var r=[];if(this.data.audiototal>0){var i,audio=this.data.audio||[];for(i=0;i<audio.length;i++){if(i>0){break;}
if(audio[i].albumid>0){audio[i].albumthumb=['//i.gtimg.cn/music/photo/album/',audio[i].albumid%100,'/150_albumpic_',audio[i].albumid,'_0.jpg'].join('');}else if(audio[i].albumimg){audio[i].albumthumb=audio[i].albumimg;}else{audio[i].albumthumb='//music.qq.com/musicbox/img/uccpic_error.jpg';}
audio[i].singername='';audio[i].tid=this.data.tid;audio[i].className=opt.className;audio[i].formatedName=escHTML(audio[i].name);r.push(OOP.tpl.format(tpl,audio[i]));}}else{return'';}
return r.join('');};MoodModel.prototype.getTypeHTML=function(){return'';};MoodModel.prototype.getCommentModuleHTML=function(){if(this.data.timershuoshuo===1){return'';};var TPL=['<!-- 评论区 -->','<div class="mod_comment" id="comment_list_{{tid}}">','{{mod_comments}}','<!--发表框 默认-->','<div class="mod_commnets_poster"><!--如果，发表框在评论列表上面，请加上 class mod_commnets_poster_top 谢谢-->','<div class="comments_poster_bd comments_poster_default">','<div class="comments_box">','<div class="textinput textinput_default bor2" contentEditable="true" placeholder="我也说一句">我也说一句</div>','</div>','</div>','</div>','</div>'].join('');return OOP.tpl.format(TPL,{tid:this.getTid(),mod_comments:this.getCommentsHTML()});};MoodModel.prototype.getButtonHTML=function(){var isOwner=this.getUin()==QZONE.FP.getQzoneConfig('loginUin');var timer_tpl=['{{timeshuoshuo_status}}','<a href="javascript:void(0);" class="c_tx timer_del" >删除</a>'].join('');var tab;if(window.t||window.MOOD&&MOOD.env){tab=(window.t&&t.tab)||(MOOD.env&&MOOD.env.tab);}
var needEditButton=(isOwner&&!this.data.voice&&this.data.t1_source!=2&&this.data.t1_subtype!=33&&this.data.isEditable!==0);if(isOwner&&this.data.video&&this.data.video.length){needEditButton=false;}
var more_op_tpl=['<div class="dropdown more-edit-items">',' <a href="javascript:void(0);" class="dropdown-trigger c_tx" id="dLabel_'+this.data.tid+'" data-toggle="dropdown" aria-haspopup="ture" aria-expanded="true">更多<i class="ui_trig ui_trig_b"></i></a>','  <div class="dropdown-menu menu-item-list bor2 bg" role="menu" aria-labelledby="dLabel_'+this.data.tid+'" aria-hidden="false">','   <ul role="presentation">',needEditButton?'<li><a href="javascript:void(0);" class="edit_btn author_display" role="menuitem">编辑</a></li>':'',(tab!='detail')?'<li class="add_favorite_container need_bg2"></li>':'',(tab!='detail')?'<li><a href="javascript:void(0);" class="goDetail" role="menuitem">详情</a></li>':'',isOwner?'<li><a href="javascript:void(0);" class="del del_btn author_display" role="menuitem">删除</a></li>':'','   </ul>','  </div>','</div>'].join('');var my_normal_tpl=['<a href="javascript:void(0);" class="c_tx none">赞</a>','<span id="like_btn_{{tid}}"></span>','<a href="{{permalink}}" class="c_tx comment_btn" target="_blank" onclick="return false;" id="comment_btn_{{uin}}_{{tid}}_{{t1_source}}">{{comment_count_html}}</a>','<a href="{{permalink}}" class="c_tx forward_btn{{voice_class_fix}}" target="_blank" onclick="return false;" id="forward_btn_{{uin}}_{{tid}}_{{t1_source}}">{{forward_num_html}}</a>',(tab=='detail')?'<span class="add_favorite_container"></span>':'',more_op_tpl].join('');var normal_tpl=['<a href="javascript:void(0);" class="c_tx mouseOver report report_btn" style="display:none;">举报</a>','<a href="javascript:void(0);" class="c_tx none">赞</a>','<span id="like_btn_{{tid}}"></span>','<a href="{{permalink}}" class="c_tx comment_btn" target="_blank" onclick="return false;" id="comment_btn_{{uin}}_{{tid}}_{{t1_source}}">{{comment_count_html}}</a>','<a href="{{permalink}}" class="c_tx forward_btn{{voice_class_fix}}" target="_blank" onclick="return false;" id="forward_btn_{{uin}}_{{tid}}_{{t1_source}}">{{forward_num_html}}</a>',(tab=='detail')?'<span class="add_favorite_container"></span>':'',(tab!='detail')?more_op_tpl:''].join('');var private_tpl=['<a href="{{permalink}}" class="c_tx comment_btn public_show none" target="_blank" onclick="return false;" id="comment_btn_{{uin}}_{{tid}}_{{t1_source}}">{{comment_count_html}}</a>','<a href="{{permalink}}" class="c_tx forward_btn public_show none" target="_blank" onclick="return false;" id="forward_btn_{{uin}}_{{tid}}_{{t1_source}}">{{forward_num_html}}</a>',more_op_tpl].join('');if(this.data.secret===1){return'<div class="op">'+OOP.tpl.format(private_tpl,{permalink:this.getPermalink(),comment_count:this.getCommentCount(),retweet_count:this.getRTCount(),uin:this.data.uin,comment_count_html:(function(cmtCount){if(isInVisibleMode){return'评论';}
return cmtCount?'评论('+cmtCount+')':'评论'})(this.getCommentCount()),forward_num_html:(function(forwardCount){if(isInVisibleMode){return'转发';}
return forwardCount?'转发('+forwardCount+')':'转发'})(this.getForwardNum()),tid:this.data.tid,t1_source:this.data.t1_source})+'</div>';}
if(this.data.right>1){return'';}
if(this.data.timershuoshuo===1){var timershuoshuo='<a href="javascript:void(0);" class="c_tx timer_send_now" >立即发送</a>';if(this.data.haspublish){timershuoshuo='已经发送';}
return'<div class="op">'+OOP.tpl.format(timer_tpl,{timeshuoshuo_status:timershuoshuo})+'</div>';}
return'<div class="op">'+OOP.tpl.format(isOwner?my_normal_tpl:normal_tpl,{permalink:this.getPermalink(),comment_count:this.getCommentCount(),retweet_count:this.getRTCount(),uin:this.data.uin,comment_count_html:(function(cmtCount){if(isInVisibleMode){return'评论';}
return cmtCount?'评论('+cmtCount+')':'评论'})(this.getCommentCount()),forward_num_html:(function(forwardCount){if(isInVisibleMode){return'转发';}
return forwardCount?'转发('+forwardCount+')':'转发'})(this.getForwardNum()),voice_class_fix:this.data.voice?' none':'',tid:this.data.tid,t1_source:this.data.t1_source})+'</div>';};MoodModel.prototype.getApplyAccessHTML=function(){if(this.data.right==2){return'<div class="secret c_tx3"><span class="encrypt_feeds">该空间已经加密</span>&nbsp;<a href="javascript:void(0);" class="c_tx apply_access">申请访问</a></div>';}
if(this.data.right==3){return'<div class="secret c_tx3"><span class="encrypt_feeds">该空间已经加密</span>&nbsp;<a href="javascript:void(0);" class="c_tx passwrod_required">输入密码并查看</a>&nbsp;<a href="javascript:void(0);" class="c_tx apply_access">申请访问</a></div>';}
return'';};MoodModel.prototype.getInfoHTML=function(){var normal_tpl=['<div class="info">','<span class="c_tx3">','<a class="c_tx c_tx3 goDetail" title="{{created_time}}" href="{{permalink}}">{{created_time}}</a>','</span>','{{source_html}}','{{location_html}}','{{authorize_html}}','</div>'].join('');var timer_tpl='<div class="info"><span class="c_tx3">预定于 {{createTime2}} 发送</span></div>';var isOwner=false;try{isOwner=QZONE.FP._t.isOwnerMode();}catch(err){}
if(this.data.right>1){return'';}
if(this.data.timershuoshuo===1){return OOP.tpl.format(timer_tpl,{createTime2:this.data.createTime2});}
return OOP.tpl.format(normal_tpl,{permalink:this.getPermalink(),created_time:this.getCreatedTime(),source_html:this.getSourceHTML(),location_html:this.getLocationHTML(),authorize_html:(function(data){if(!isOwner){return'';}
var result;switch(data.ugc_right){case 4:result='<span class="icon-lock" title="QQ好友可见"></span>';break;case 16:result='<span class="icon-lock" title="部分好友可见"></span>';break;case 64:result='<span class="icon-lock" title="仅自己可见"></span>';break;case 128:result='<span class="icon-lock" title="部分好友不可见"></span>';break;default:result=''
break;}
return result;})(this.data)});};MoodModel.prototype.getItemHTML=function(){var TPL=['<li class="feed {{feed_private_style}}" data-tid="{{tid}}" data-uin="{{uin}}" data-seed="item-{{seed}}">','<div class="private_hd private_show {{private_show}}">','<div class="private_bg"></div>','</div>','<div class="avatar"><a href="{{profile_url}}" onclick="return false;" class="goProfile" profileUin="{{uin}}" title="{{nickname}}({{uin}})">','<span class="skin_portrait_round"></span>','<img data-src="{{avatar_url}}" src="/qzone/app/mood_v6/images/blank.gif" class="lazyload" alt="{{nickname}}({{uin}})"></a>','</div>','<div class="box bgr3">','<div class="arr bor3"><div class="bor_bg3"></div></div>','<div class="bd">','{{user_link}} {{mood_type}} <pre style="display:inline;" class="content">{{content_html}}</pre><span>{{ellipsis}}</span>','<div class="f_toggle">','<a href="javascript:void(0);" onclick="return false;" class="has_more_con {{more_active}}">{{more_words}}</a>','</div>','{{voice_html}}','</div>','{{media_preview_html}}','{{story_info}}','<div class="ft">','{{apply_access_html}}','{{info_html}}','{{op_button_html}}','</div>','<div class="box_extra bor3 {{has_right_style}}">','<div class="box_extra_arr bor3"><div class="bor_bg3"></div></div>','<div class="feed_like" id="feed_like_{{tid}}" style="display:none;">','<i class="icon_zan"></i>4917人觉得很赞','</div>','{{comment_module}}','</div>','</div>','<div class="box_shadow"><div class="shadow_left"></div><div class="shadow_right"></div></div>','</li>'].join('');return OOP.tpl.format(TPL,this.toJSON());};var CommentModel=function(data){this.data=data||{};this.template=['<li class="comments_item bor3">',' <div class="comments_item_bd">','  <div>','   {{ui_avatar}}','   <div class="comments_content">','    <a class="nickname" href="http://user.qzone.qq.com/{{uin}}/mood/" target="_self">{{parsedNickname}}</a>','    {{privateText}}','    {{replyTarget}}','    :','    <span>{{content_html}}</span>','    {{commentPhotos}}','    <div class="comments_op">','     <span class="c_tx3 ui_mr10">{{create_time}}</span>','     <a href="javascript:void(0);" class="c_tx none" >回复</a>','    </div>','   </div>','  </div>','  {{mod_comments_sub}}',' </div>','</li>'].join('');this._author=new UserObject({nickname:this.data.name||(this.data.owner&&this.data.owner.name)||this.data.uin,uin:this.data.uin||(this.data.owner&&this.data.owner.uin),who:!!this.data.t3_wc_uin*2||this.data.t3_source||!!this.data.t2_wc_uin*2||this.data.t2_source||1});this.replies_tpl='<div class="mod_comments_sub ">{{comments_list}}</div>';this.config={max_replies_count:-1,show_avatar:true};if(this.data.list_3){if(this.data.private){for(var i=0;i<this.data.list_3.length;i++){this.data.list_3[i].private=this.data.private;this.data.list_3[i].isReply=1;}}
this.replies_list=new CommentModelCollection(this.data.list_3);this.replies_list.setTemplate(this.replies_tpl);}};CommentModel.prototype.getHTML=function(noCommentPhoto){var mentionEncodingMap={'}':/%7D/g,',':/%2C/g,'%':/%25/g};var decodeMention=function(content){if(content){for(var i in mentionEncodingMap){content=content.replace(mentionEncodingMap[i],i);}}
return content;};var formatTime=function(time){if(typeof time=='string'){return time;}
if(time==0){return'';}
var nt;nt=(new Date().getTime()/1000);try{nt=QZONE.FP.getSvrTime().getTime()/1000;}catch(err){}
var ut=time;var vt=nt-ut;if(vt<=0){return'刚刚';}
var date=new Date(ut*1000);var now=new Date(nt*1000);if(vt<60){return Math.floor(vt)+"秒前";}else{if(vt<60*60){return Math.floor(vt/60)+"分钟前";}else{if(vt<60*60*24){if(date.getDate()==now.getDate()){return"今天"+date.getHours()+":"+(date.getMinutes()>9?date.getMinutes():("0"+""+date.getMinutes()));}else{return"昨天"+date.getHours()+":"+(date.getMinutes()>9?date.getMinutes():("0"+""+date.getMinutes()));}}else{if(vt<60*60*24*2){if(date.getDate()==(new Date(nt*1000-60*60*24*1000-1)).getDate()){return"昨天"+date.getHours()+":"+(date.getMinutes()>9?date.getMinutes():("0"+""+date.getMinutes()));}else{return"前天"+date.getHours()+":"+(date.getMinutes()>9?date.getMinutes():("0"+""+date.getMinutes()));}}else{if(vt<60*60*24*3){if(date.getDate()==(new Date(nt*1000-60*60*24*2*1000-1)).getDate()){return"前天"+date.getHours()+":"+(date.getMinutes()>9?date.getMinutes():("0"+""+date.getMinutes()));}else{return(date.getMonth()+1)+"月"+date.getDate()+"日";}}else{if((new Date(nt*1000).getFullYear())==date.getFullYear()){return date.getFullYear()+"-"+(date.getMonth()+1)+"-"+date.getDate();}else{return(date.getFullYear()+"-"+(date.getMonth()+1)+"-"+date.getDate());}}}}}}};if(this.data.list_3){var config=QZFL.object.extend({},this.config);config.max_comments_count=this.config.max_replies_count;this.replies_list.setConfig(config);this.data.mod_comments_sub=this.replies_list.getHTML(false);}
this.data.author_link=this._author.getUserLink();if(this.config.show_avatar){this.data.ui_avatar=this._author.getAvatarLink(50);}
var autoMentionPattern=/(?:@\{uin:([\w-_]+),nick:([^\},]*)(?:,who:(\d+))?(?:,auto:(\d+))?\})|[^@]+/g;var mentionPattern=/(?:@\{uin:([^\}]*),nick:([^\},]*)(?:,who:(\d+))?\})|[^@]+/g;var content_html=escHTML(this.data.content);var isPrivate=this.data.private;this.data.replyTarget=content_html.replace(autoMentionPattern,function($0,uin,nick,platform,auto){if(uin&&auto){var mention=new UserObject({nickname:restXHTML(decodeMention(nick)||uin),uin:uin,who:platform||1});return'<span class="<%if(isPrivate){%>private-txt<%}%>">'+(isPrivate?'私密':'')+'回复 '+mention.getProfileLink(true)+'</span>';}
return'';});content_html=QZFL.FP.removeUBB(content_html);var privateText='';if(this.data.private){if(!this.data.isReply){privateText='<span class="private-txt">私密评论</span>';}else{if(!this.data.replyTarget){privateText='<span class="private-txt">私密回复</span>';}}}
this.data.content_html=content_html.replace(autoMentionPattern,function($0,uin,nick,platform,auto){if(uin){if(auto){return'';}
var mention=new UserObject({nickname:restXHTML(nick||uin),uin:uin,who:platform||1});return mention.getProfileLink();}
return $0;});var pics=this.data.pic;this.data.commentPhotos=(function(){if(noCommentPhoto){return'';}
if(!pics||!pics.length){return'';}
var imgs=[];for(var i=0;i<pics.length;i++){imgs.push({m_url:pics[i].s_url.replace(/\/[acmboi]\//ig,'/m/'),s_url:pics[i].s_url,b_url:pics[i].b_url});}
var template=['<div class="cmt-figure">',' <div>','  <%for(var i=0; pics && i<pics.length;i++){%>','   <a href="javascript:void(0)">','    <img rel="comment_photo" onload="this.onload=null;var imgTag = this;var img=new Image();img.onload=function(){var holderWidth =100;var holderHeight=75;var holderSize=QZFL.dom.getSize(imgTag.parentNode);holderWidth=holderSize[0];holderHeight=holderSize[1]; var width = this.width; var height = this.height;var holderRatio = holderWidth/holderHeight;if(width/height >holderRatio){imgTag.height = holderHeight;}else{imgTag.width = holderWidth;}imgTag.src = img.src;};img.src=imgTag.getAttribute(\'data-murl\');" src="/ac/b.gif" data-murl="<%=escHTML(pics[i].m_url)%>" data-burl="<%=escHTML(pics[i].b_url)%>" data-surl="<%=escHTML(pics[i].s_url)%>">','   </a>','  <%}%>',' </div>','</div>'].join('');return tmpl(template,{pics:imgs});})();return OOP.tpl.format(this.template,{parsedNickname:QZONE.FP.removeUBB(escHTML(this.data.name)),nickname:escHTML(this.data.name),uin:this.data.uin,ui_avatar:this.data.ui_avatar,content_html:this.data.content_html,create_time:formatTime(this.data.create_time),mod_comments_sub:this.data.mod_comments_sub,replyTarget:this.data.replyTarget,privateText:privateText,commentPhotos:this.data.commentPhotos});};CommentModel.prototype.setConfig=function(opts){this.config=QZFL.object.extend(this.config,opts);};CommentModel.prototype.toJSON=function(){return{};};var CommentModelCollection=function(datas,opts){this._models=[];this.config=QZFL.object.extend({max_comments_count:-1,max_replies_count:-1,order:'asc',show_avatar:true},opts);this.template=['<div class="mod_comments">','<div class="comments_list">','{{comments_list}}','</div><!-- list end -->','<!-- poster -->','</div><!-- qz_comments end-->'].join('');if(datas){this.init(datas);}};CommentModelCollection.prototype.init=function(datas){datas=datas||[];var item,i;for(i=0;i<datas.length;i++){var cm=new CommentModel(datas[i]);this._models.push(cm);}};CommentModelCollection.prototype.setTemplate=function(tpl){this.template=tpl;};CommentModelCollection.prototype.setConfig=function(opts){this.config=QZFL.object.extend(this.config,opts);if(this.config.order=='desc'){this._models.reverse();}};CommentModelCollection.prototype.getHTML=function(noCommentPhoto){var i,html=[];var max_comments_count=this._models.length>this.config.max_comments_count?this.config.max_comments_count:this._models.length;max_comments_count=max_comments_count<0?this._models.length:max_comments_count;for(i=0;i<max_comments_count;i++){this._models[i].setConfig(this.config);html.push(this._models[i].getHTML(noCommentPhoto));}
return OOP.tpl.format(this.template,{comments_list:'<ul>'+html.join('')+'</ul>'});};var MoodModelCollection=function MoodModelCollection(opts){this.opts=opts||{};this._models=[];this._pagination={totalRecords:0,rowsPerPage:20,total:0,page:0};this.config={mood:{comment:{},reply:{}}};if(this.opts.initialData){this._pagination.page++;this.init(this.opts.initialData);if(typeof this.opts.success=='function'){this.opts.success(this);}}};MoodModelCollection.prototype.init=function(d){this._models=[];d=d||{};this._pagination.totalRecords=typeof d.total=='undefined'?d.usrinfo&&d.usrinfo.msgnum||0:d.total;this._pagination.total=Math.ceil(this._pagination.totalRecords/this._pagination.rowsPerPage);var datas=d.msglist||d.posts||[];var item,i;for(i=0;i<datas.length;i++){var mood;if(datas[i].source_type=='share'){mood=new ShareModel(datas[i]);}else{mood=new MoodModel(datas[i]);}
this._models.push(mood);}};MoodModelCollection.prototype.setConfig=function(opts){this.config=QZFL.object.extend(this.config,opts);var i,mood;for(i=0;i<this._models.length;i++){mood=this._models[i];mood.setConfig(this.config.mood);}};MoodModelCollection.prototype.apis=function(id){var item,i;var r=[];for(i=0;i<this._models.length;i++){var mood=this._models[i];r.push({type:mood.getType(),isOriginal:mood.getType()=='original',isRetweet:mood.getType()=='retweet',isPhoto:mood.getType()=='photo',write_time:mood.getTimestamp(),original_content:function(mood){return function(){return mood.getHTML()};}(mood),content:function(mood){return function(){return mood.getFullContent()};}(mood),broadcast_content1:function(mood){return function(){return mood.getBroadcast()};}(mood),broadcast_content2:function(mood){return function(){return mood.getBroadcast({retweets:false})};}(mood),comment_count:mood.getCommentCount(),rt_count:mood.getRTCount()});}
return r;};MoodModelCollection.prototype.getHTML=function(){var i,r=[],mood;for(i=0;i<this._models.length;i++){mood=this._models[i];r.push(mood.getItemHTML());}
return r.join('');};MoodModelCollection.prototype.fetch=function(opt){opt=opt||{};var self=this;this._pagination.page++;if(opt.page){this._pagination.page=opt.page;}
this.opts.pos=(this._pagination.page-1)*this._pagination.rowsPerPage;var type=this.opts.type;if(typeof cgi_list[type]!='undefined'){this.opts.cgi_host=cgi_list[type];_get_list(this.opts,function(d){d.msglist=d.msglist||d.posts;self.init(d);if(typeof self.opts.success=='function'){self.opts.success(self);}});}};MoodModelCollection.prototype.getPagination=function(){return this._pagination;};MoodModelCollection.prototype.getSizeSync=function(){if(this._models){return this._models.length;}
return 0;};MoodModelCollection.prototype.each=function(fn){if(typeof fn=='function'){var i;for(i=0;i<this._models.length;i++){var mood=this._models[i];(function(mood,fn){fn(mood);})(mood,fn);}}};var Pagination=function(data){var self=this;data=data||{};this.config={uin:data.uin||'',ftype:0,sort:0,pos:data.pos||0,num:data.num||20,type:data.type||'0',tag:data.type||'1',start_time:data.start_time||'',end_time:data.end_time||'',cur_pos:data.cur_pos||'',total_topics:-1,total:0,success:function(d){if(d.code==0){self.config.start_time=d.start_time;self.config.end_time=d.end_time;self.config.total=d.total;self.config.total_topics=d.total;d.msglist=d.msglist||[];var mmc=new MoodModelCollection(d.msglist);if(typeof data.success=='function'){data.success(mmc,self);}
var i,ids=[];for(i=0;i<d.msglist.length&&i<1;i++){ids.push(d.msglist[i].tid);}
if(ids[0]){_user_tracker({uin:data.uin,id:ids[0],src:0x0F});}}else{QZONE.FP.showMsgbox(d.message,5,3000);}},code_version:1,format:'jsonp'};};Pagination.prototype.go=function(target){var cur_pos=this.config.pos;this.config.pos=target>=this.getPagination().total?0xFFFFFFFF:target;this.config.cur_pos=cur_pos==0xFFFFFFFF?this.getPagination().total:cur_pos;_get_list_by_type(this.config);};Pagination.prototype.next=function(){var cur_pos=this.config.pos;this.config.pos=this.getPagination().next;this.config.cur_pos=cur_pos;_get_list_by_type(this.config);};Pagination.prototype.prev=function(){var cur_pos=this.config.pos;this.config.pos=this.getPagination().prev;this.config.cur_pos=cur_pos==0xFFFFFFFF?this.getPagination().total:cur_pos;_get_list_by_type(this.config);};Pagination.prototype.getPagination=function(){var total=Math.ceil(this.config.total/this.config.num);var current=this.config.pos==0xFFFFFFFF?total:parseInt(this.config.pos);return{total:total,next:current+1>total?1:current+1,prev:current-1>0?current-1:0xFFFFFFFF,current:current};};var _reportString=function(id,string,reportRate){try{if(!id){return;}
var TCISD=window.TCISD;if(!TCISD&&window.QZONE&&window.QZONE.FP&&window.QZONE.FP.getStatPackage){TCISD=QZONE.FP.getStatPackage();}
if(TCISD&&TCISD.stringStat){TCISD.stringStat('1000100',{bid:id,rc:string},{reportRate:reportRate||100});}}catch(err){}};var _get=function(opt){opt=opt||{};var data={uin:opt.uin||'',tid:opt.tid||'',t1_source:opt.t1_source||'1',ftype:0,sort:0,pos:0,num:20,code_version:1,need_private_comment:1,format:'jsonp'};var cgi_host='http://taotao.'+document.domain+'/cgi-bin/emotion_cgi_msgdetail_v6';var r=new QZFL.JSONGetter(cgi_host,'_get'+Math.random(),data,'utf-8');r.onSuccess=function(o){o=o||{};r=o.result;if(typeof o.code!='undefined'){r={code:o.code,msg:o.message};}
if(0==r.code){o.create_time=o.createTime;o.commentlist=o.commentlist||[];o.reply_num=o.reply_num||o.replies||o.msgTotal||o.commentlist.length;var mood=new MoodModel(o);if(typeof opt.success=='function'){opt.success(mood);}
_user_tracker({uin:data.uin,id:data.tid,src:0x09});}else{r.msg==''||QZONE.FP.showMsgbox(r.msg,5,2000);if(typeof opt.error=='function'){opt.error(r);}}
QZONE.FP._t.TCISD.haboStat({stime:this.endTime-this.startTime,commandid:this._uri,resultcode:d.code,touin:QZONE.FP._t.g_iLoginUin});};r.onError=function(){QZONE.FP._t.TCISD.haboStat({stime:this.endTime-this.startTime,commandid:this._uri,resultcode:999,touin:QZONE.FP._t.g_iLoginUin});};r.onTimeout=function(){QZONE.FP._t.TCISD.haboStat({stime:10000,commandid:this._uri,resultcode:998,touin:QZONE.FP._t.g_iLoginUin});};r.send('_Callback');};var _get_photos=function(opt){opt=opt||{};var data={tid:opt.tid||'',uin:opt.uin||'',t1_source:1,code_version:1,format:'jsonp'};data.plattype=opt.plattype||opt.t1_source||1;var cgi_host='http://taotao.'+document.domain+'/cgi-bin/emotion_cgi_get_pics_v6';var r=new QZFL.JSONGetter(cgi_host,'_get_photos'+Math.random(),data,'utf-8');r.onSuccess=function(d){d.imageUrls=d.imageUrls||[];var i,o=[],obj,item;if(d.images){for(i=0;i<d.images.length;i++){obj=d.images[i];if(obj.hd_pic){item={origin:obj.big_pic,big_pic:obj.big_pic,big_width:obj.big_width,big_height:obj.big_height,hd_pic:obj.hd_pic,hd_width:obj.hd_width,hd_height:obj.hd_height,tid:data.tid,uin:data.uin};}else{item={origin:obj.big_pic,big_pic:obj.big_pic,big_width:obj.big_width,big_height:obj.big_height,tid:data.tid,uin:data.uin};}
o.push(item);}}else{for(i=0;i<d.imageUrls.length;i++){o.push({origin:d.imageUrls[i],tid:data.tid,uin:data.uin});}}
if(typeof opt.success=='function'){opt.success(o);}};r.send('_Callback');};var _get_list=function(opt,callback){opt=opt||{};var cgi_host=opt.cgi_host.url||'';var idcNo=window._locationCache&&window._locationCache.idcNo;if(opt.cgi_host.idc&&idcNo==2){cgi_host=cgi_host.replace('taotao.qq.com','sh.taotao.qq.com');}
var data={uin:opt.uin||'',inCharset:'utf-8',outCharset:'utf-8',hostUin:opt.hostUin||'',notice:0,sort:0,pos:opt.pos||0,num:20,cgi_host:cgi_host,code_version:1,format:'jsonp',need_private_comment:1};var r=new QZFL.JSONGetter(cgi_host,'_get_list'+Math.random(),data,'utf-8');if(cgi_host.indexOf('emotion_cgi_msglist_v6')>0){window.console&&console.log('调整msglist采样率');r.setReportRate&&r.setReportRate(80);}
r.onSuccess=function(d){if(typeof callback=='function'){callback(d);}
QZONE.FP._t.TCISD.haboStat({stime:this.endTime-this.startTime,commandid:this._uri,resultcode:0,touin:QZONE.FP._t.g_iLoginUin});};r.onError=function(){QZONE.FP._t.TCISD.haboStat({stime:this.endTime-this.startTime,commandid:this._uri,resultcode:999,touin:QZONE.FP._t.g_iLoginUin});};r.onTimeout=function(){QZONE.FP._t.TCISD.haboStat({stime:10000,commandid:this._uri,resultcode:998,touin:QZONE.FP._t.g_iLoginUin});};r.send('_Callback');};var _get_list_by_type=function(opt){opt=opt||{};var data={uin:opt.uin||'',ftype:0,sort:0,total_topics:opt.total_topics||-1,pos:opt.pos||1,num:opt.num||20,type:opt.type||'0',tag:opt.tag||'1',start_time:opt.start_time||'',end_time:opt.end_time||'',cur_pos:opt.cur_pos||'',code_version:1,format:'jsonp'};var cgi_host='http://taotao.'+document.domain+'/cgi-bin/emotion_cgi_msglist_by_type_v6';var r=new QZFL.JSONGetter(cgi_host,'_get_list'+Math.random(),data,'utf-8');r.onSuccess=function(d){if(typeof opt.success=='function'){opt.success(d);}};r.send('_Callback');};var onMultiDetailsLoadSuccess=function(d,opt){d.data=d.data||{};d.data.msglist=d.data.msglist||[];var mmc=new MoodModelCollection({initialData:d.data});var isMusic=false;var photos=[];mmc.each(function(mood){var _photos=mood.getPhotosSync();for(var i=0;i<_photos.length;i++){var _photo=_photos[i];var p={'pre':_photo.pre,'url':_photo.origin,'pic_id':_photo.pic_id||'','width':_photo.big_width,'height':_photo.big_height,'name':'','index':i};if(_photo.hd_pic){p.origin_upload=1;p.origin_url=_photo.hd_pic;p.origin_height=_photo.hd_height;p.origin_width=_photo.hd_width;}
p.tid=mood.getTid();p.mood=mood;p._infoSrc=mood;photos.push(p);}});if(typeof opt.success=='function'){opt.success(photos);}
if(d.data.msglist.length>0&&d.data.msglist[0]){_user_tracker({uin:d.data.msglist[0].uin,id:d.data.msglist[0].tid,src:0x0F});}else if(typeof opt.error=='function'){opt.error({code:d.code,msg:d.message});}};var _get_multi_details=function(opt){opt=opt||{};var i,item,tid,uin,source;var batchs=opt.bucket;var data={format:'jsonp',out_charset:'UTF-8'};try{QZONE.FP.getStatPackage().pv('taotao.qq.com','batch_fetch details_'+batches.length);}catch(err){}
for(i=0;i<batchs.length;i++){item=batchs[i].split('.');data['tid'+i]=item[0];data['uin'+i]=item[1];data['source'+i]=item[2];}
data['num']=batchs.length;data['uin']=opt.uin;var cgi_host='http://taotao.'+document.domain+'/cgi-bin/emotion_cgi_getmsgs_detail';if(batchs.length>15){data.format='fs';var fs=new QZFL.FormSender(cgi_host,'POST',data,'utf-8');fs.onSuccess=function(d){onMultiDetailsLoadSuccess(d,opt);};fs.send();}else{data.format='jsonp';var jg=new QZFL.JSONGetter(cgi_host,null,data,'utf-8');jg.onSuccess=function(d){onMultiDetailsLoadSuccess(d,opt);};jg.send('_Callback');}};var _get_navigation_manager=function(fn){if(typeof fn=='function'){fn(Pagination);}else{throw'callback function "fn" required.';}};var _user_tracker=function(opt){var data={uin:'',mod:0,src:9,id:''};QZFL.object.extend(data,opt);var actionURL='http://g.qzone.'+document.domain+'/cgi-bin/friendshow/cgi_content_visitor';var fs=new QZFL.FormSender(actionURL,'POST',data,'utf-8');fs.onSuccess=function(d){};fs.send();};var ShareModel=function ShareModel(share){this.data=QZFL.object.extend(true,{},share);if(this.data.rt_con){this.data.rtitem={};this.data.rtitem.rich_info=this.data.pic;this.data.rtitem.createTime=this.data.rt_createTime;this.data.rtitem.nosrc=this.data.rt_nosrc;this.data.rtitem.rt_account=this.data.rt_account;this.data.rtitem.t1_source=this.data.rt_source;this.data.rtitem.source_name=this.data.rt_source_name;this.data.rtitem.source_url=this.data.rt_source_url||this.data.rt_url;this.data.rtitem.rt_sum=this.data.rt_sum;this.data.rtitem.tid=this.data.rt_tid;this.data.rtitem.uin=this.data.rt_uin;this.data.rtitem.name=this.data.rt_uinname;this.data.rtitem.conlist=this.data.rt_con.conlist;this.data.rtitem.content=this.data.rt_con.content;}
this.data.commentlist=this.data.commentlist||[];this.cmc=new CommentModelCollection(this.data.commentlist||{});this.seed=get_item_seed();ItemDataStorage[''+this.data.tid||('item-'+this.seed)]=this;};ShareModel.prototype.getText=function(opts){opts=QZFL.object.extend({emoji:true,hashtag:true,link:true},opts);var conlist=this.data.conlist||[];var i,item,r;var text=[];for(i=0;i<conlist.length;i++){item=conlist[i];switch(item.type){case 0:text.push('@'+escHTML(item.nick));break;case 1:if(opts.link){text.push(escHTML(item.url));}
break;case 2:text.push(escHTML(item.con));break;}}
r=text.join('');if(!opts.emoji){r=r.replace(/\[em\]e(\d{1,8})\[\/em\]/ig,'');}
if(!opts.hashtag){r=r.replace(/#((?:.|<br\/>)+?)#/ig,'');}
r=r.replace(/^[\s\xA0]+/,'').replace(/[\s\xA0]+$/,'');return r;};ShareModel.prototype.getHTML=function(opts){opts=QZFL.object.extend({emoji:true,hashtag:true,link:true,wrapper:true},opts);var HTMLTPL='<div class="qz_311_content">{content}</div>';var MENTIONTPL='<a href="{url}" target="_blank" class="qz_311_mention nickname">@{nickname}</a>';var URLTPL='<a href="{url}" target="_blank" class="qz_311_url">{url}</a>';var HASHTAGTPL='<a href="http://rc.qzone.qq.com/qzonesoso/?search={keyword}&entry=99&businesstype=share" target="_blank" class="c_tx qz_311_hashtag">{name}</a>';var conlist=this.data.conlist||[];var i,item,r;var text=[];for(i=0;i<conlist.length;i++){item=conlist[i];switch(item.type){case 0:switch(item.who){case 3:item.url=format('http://rc.qzone.qq.com/myhome/weibo/profile/{uin}',item);break;case 2:item.url=format('http://www.pengyou.com/index.php?mod=profile&u={uin}&adtag=from_profile',item);break;default:item.url=format('http://user.qzone.qq.com/{uin}',item);break;}
item.nickname=escHTML(item.nick);text.push(format(MENTIONTPL,item));break;case 1:if(opts.link){item.url=escHTML(item.url);text.push(format(URLTPL,item));}
break;case 2:text.push(escHTML(item.con));break;}}
r=text.join('');if(!opts.emoji){r=r.replace(/\[em\]e(\d{1,8})\[\/em\]/ig,'');}else{r=QZFL.FP.removeUBB(r);}
if(!opts.hashtag){r=r.replace(/^(?!&)#((?:.|<br\/>)+?)(?!&)#/ig,'');}else{r=r.replace(/^(?!&)#((?:.|<br\/>)+?)(?!&)#/ig,function(a,b){return format(HASHTAGTPL,{keyword:encodeURIComponent(b),name:escHTML(a)});});}
r=r.replace(/^[\s\xA0]+/,'').replace(/[\s\xA0]+$/,'');if(opts.wrapper){r=format(HTMLTPL,{content:r});}
return r;};ShareModel.prototype.getMedia=function(){var HTMLTPL='<div class="qz_311_media">{media}</div>';var PHOTOTPL='<img src="{url1}" class="qz_311_photo" data-meta=""/>';var VIDEOTPL='<img src="{vimg}" class="qz_311_video" data-meta=""/>';var r='',i,media;var medias=this.data.rich_info||[];var html=[];for(i=0;i<medias.length;i++){media=medias[i];switch(media.type){case 1:html.push(format(PHOTOTPL,media));break;case 3:html.push(format(VIDEOTPL,media));break;}}
if(medias.length>0){r=format(HTMLTPL,{media:html.join('')})}
return r;};ShareModel.prototype.getFullContent=function(){return this.getHTML()+this.getMedia();};ShareModel.prototype.getCreatedTime=function(){return this.data.create_time||this.data.createTime;};ShareModel.prototype.getTimestamp=function(){return this.data.create_time;};ShareModel.prototype.getType=function(){var r='original';if(this.data.isSignIn==1){r='sign'}
var medias=this.data.rich_info||[];var i;for(i=0;i<medias.length;i++){switch(medias[i].type){case 1:r='photo';break;case 2:r='video';break;}}
if(this.data.rtitem||this.data.rt_con){r='retweet';}
return r;};ShareModel.prototype.getSubType=function(){};ShareModel.prototype.getCommentCount=function(){return this.data.replies||this.data.reply_num;};ShareModel.prototype.getForwardNum=function(){return this.data.fwdnum||0;};ShareModel.prototype.getRTCount=function(){if(this.data.rtitem){return this.data.rtitem.rt_sum||0;}
return this.data.rt_sum||0;};ShareModel.prototype.getAuthor=function(){var data={nickname:this.data.ownername||this.data.name,uin:this.data.owneruin||this.data.uin};var user=new UserObject(data);return user;};ShareModel.prototype.getUserLink=function(){var data={who:this.data.nosrc==1?3:1,uin:this.data.nosrc==1?this.data.rt_account:(this.data.owneruin||this.data.uin),nickname:this.data.ownername||this.data.name};if(this.data.wc_uin&&this.data.wc_uin!=''){data.who=2;data.uin=this.data.wc_uin;}
var user=new UserObject(data);return user.getProfileLink();};ShareModel.prototype.getBroadcast=function(opts){opts=QZFL.object.extend({retweets:true,origin:false},opts);var HTMLTPL='<div class="qz_311_content">{content}</div>';var RTHTMLTPL='<div class="qz_311_rtcontent">{content}</div>';var item,items,i,m;var html=[],retweet=[];if(this.data.rt_con){retweet.push(this.getHTML({wrapper:false}));if(this.data.rtlist&&opts.retweets){items=this.data.rtlist||[];for(i=items.length-1;i>=0;i--){item=QZFL.object.extend({},items[i]);m=new ShareModel(item);retweet.push(format('{user}: {content}',{user:m.getUserLink(),content:m.getHTML({wrapper:false})}));}}
html.push(format(HTMLTPL,{content:retweet.join(' || ')}));if(opts.origin){m=new ShareModel(this.data.rtitem);html.push(format(RTHTMLTPL,{content:m.getFullContent()}));}}
return html.join('');};ShareModel.prototype.getTid=function(){return this.data.tid;};ShareModel.prototype.getRTTid=function(){return this.data.rt_tid||'';};ShareModel.prototype.getUin=function(){return this.data.owneruin||this.data.uin||'';};ShareModel.prototype.getRTUin=function(){return this.data.rt_uin||'';};ShareModel.prototype.getRTMood=function(){if(this.data.rtitem){return new ShareModel(this.data.rtitem);}};ShareModel.prototype.getPhotosSync=function(){if(this.data.pictotal>0){var items=[],obj,item;this.data.pic=this.data.pic||[];for(var i=0;i<this.data.pic.length;i++){obj=this.data.pic[i];item={origin:decodeURIComponent(obj.url1),big_pic:decodeURIComponent(obj.url1),big_width:obj.width,big_height:obj.height,tid:this.data.tid,uin:this.data.uin};items.push(item);}
return items;}
return[];};ShareModel.prototype.getPhotos=function(callback){var self=this;if(!this._photos){var data={tid:this.data.tid,uin:this.data.owneruin||this.data.uin,plattype:this.data.t1_source,success:function(o){callback(o);self._photos=o;}};_get_photos(data);}else{callback(this._photos);}};ShareModel.prototype.getPlatformType=function(){return this.data.t1_source;};ShareModel.prototype.getRTPlatformType=function(){return this.data.rt_source;};ShareModel.prototype.getLikeKeys=function(){var uinStr=new Array(12-this.data.uin.length+1).join('0')+this.data.uin;var tidStr=new Array(12-this.data.uin.length+1).join('0')+this.data.tid;var key=uinStr+tidStr;var keys={key:key,uniKey:this.data.rt_source_url,curKey:key};return keys;};ShareModel.prototype.getCommentsHTML=function(){return this.cmc.getHTML();};ShareModel.prototype.getComments=function(opts){opts=QZFL.object.extend({max_comments_count:-1,max_replies_count:-1,order:'asc',callback:function(){}},opts);this.cmc.setConfig(opts);opts.callback(this.cmc);};ShareModel.prototype.setConfig=function(opts){opts=opts||{};this.cmc.setConfig(opts.comment||{});};ShareModel.prototype.getPermalink=function(){return['http://user.qzone.qq.com/',this.data.owneruin||this.data.uin,'/share/',this.data.tid,'.',this.data.source||this.data.t1_source].join('');};ShareModel.prototype.getSourceHTML=function(){if(this.data.source_url){return OOP.tpl.format('<a href="{{source_url}}" target="_blank">{{source_name}}</a>',this.data);}
return'QQ空间';};ShareModel.prototype.getLocationHTML=function(){var tpl=['<div class="md">','<div class="address c_tx3">','{{name}}  <a href="javascript:void(0);" class="c_tx viewmap" data-location="{{pos_x}},{{pos_y}}">查看地图</a>','</div>','</div>'].join('');if(this.data.lbs){return OOP.tpl.format(tpl,this.data.lbs);}
return'';};ShareModel.prototype.getShareType=function(){return this.data.srctype||'';};ShareModel.prototype.getShareTitle=function(){return escHTML(restHTML(this.data.rt_title))||'';};ShareModel.prototype.getShareTitleUrl=function(){var shareType=this.getShareType();var shareTitleUrl;switch(shareType){case 1:shareTitleUrl=decodeURIComponent(this.data.rt_url);break;case 17:shareTitleUrl=this.data.rt_source_url;break;case 50:shareTitleUrl=this.getRTTid()?this.getRTTid().split('|')[0]:'http://rc.qzone.qq.com/mall';break;default:shareTitleUrl=shareTitleUrl=this.data.rt_url;break;}
return escHTML(shareTitleUrl);};ShareModel.prototype.getRTPlatform=function(){var platform;switch(this.data.platformid){case 50:platform='qzone';break;case 51:platform='pengyou';break;default:platform='other';}
return platform;};ShareModel.prototype.getShareSummary=function(){return escHTML(this.data.rt_summary||'');};ShareModel.prototype.getRTSourceHTML=function(){if(this.data.srctype==50){return this.data.rt_source_name;}
if(this.data.rt_source_url){return OOP.tpl.format('<a href="{{rt_source_url}}" class="c_tx3" target="_blank">{{rt_source_name}}</a>',this.data);}
if(!this.data.rt_source_name&&this.data.srctype==1){return this.data.rt_uinname;}
return this.data.rt_source_name;};ShareModel.prototype.getRTSourceUrl=function(){return this.data.rt_source_url||'';};ShareModel.prototype.toJSON=function(opts){var r={content:this.data.content,seed:this.seed,tid:this.data.tid,uin:this.data.uin,content_html:this.getHTML({wrapper:false}),media_preview_html:this.getMediaPreviewHTML(),nickname:this.getAuthor().getName(),user_link:this.getAuthor().getUserLink(),avatar_url:this.getAuthor().getAvatarURL(),profile_url:this.getAuthor().getProfileURL(),created_time:this.getCreatedTime(),mod_comments:this.getCommentsHTML(),comment_count:this.getCommentCount()||0,comment_count_html:(function(cmtCount){if(isInVisibleMode){return'评论';}
return cmtCount?'评论('+cmtCount+')':'评论'})(this.getCommentCount()),retweet_count:this.getRTCount()||0,retweet_count_html:(function(rtCount){if(isInVisibleMode){return'转发';}
return rtCount?'转发('+rtCount+')':'转发'})(this.getRTCount()),source_html:this.getSourceHTML(),location_html:this.getLocationHTML(),permalink:this.getPermalink(),forward_num:this.getForwardNum(),forward_num_html:(function(forwardCount){if(isInVisibleMode){return'转发';}
return forwardCount?'转发('+forwardCount+')':'转发'})(this.getForwardNum()),report_style:this.getUin()==QZONE.FP.getQzoneConfig('loginUin')?'none':'',delete_style:this.getUin()==QZONE.FP.getQzoneConfig('loginUin')?'':'',rt_share_title:this.getShareTitle(),rt_share_title_url:this.getShareTitleUrl(),rt_share_summary:this.getShareSummary(),rt_source_html:this.getRTSourceHTML(),rt_source_url:this.getRTSourceUrl()};return r;};ShareModel.prototype.getMediaPreviewHTML=function(){var tpl=['<div class="md">','{{photo_thumb_html}}','{{video_thumb_html}}','{{music_thumb_html}}','</div>'].join('');var data={photo_thumb_html:this.getPhotoThumbHTML(),video_thumb_html:this.getVideoThumbHTML(),music_thumb_html:this.getMusicThumbHTML()};return OOP.tpl.format(tpl,data);};ShareModel.prototype.getPhotoThumbHTML=function(){var tpl=['<div class="img_cube">','{{photo_list}}','</div>'].join('');var r=[];if(this.data.pictotal>0){var i,photos=this.getPhotosSync()||[];for(i=0;i<4&&i<photos.length;i++){r.push(OOP.tpl.format('<div class="img_cube_item"><a href="{{share_title_url}}" target="_blank"><img data-src="{{photo.origin}}" src="/qzone/app/mood_v6/images/blank.gif" class="lazyload" data-limit="120,120" alt="photo_thumb_html"></a></div>',{photo:photos[i],share_title_url:this.getShareTitleUrl()}));}
if(this.data.pictotal>4){r.push(OOP.tpl.format('<a href="{{rt_url}}" class="see-all" target="_blank"><span>查看全部{{pictotal}}张照片</span></a>',{pictotal:this.data.pictotal,rt_url:this.getShareTitleUrl()}));}}else{return'';}
return OOP.tpl.format(tpl,{photo_list:r.join('')});};ShareModel.prototype.getVideoThumbHTML=function(){var r=[];var item_tpl=['<div class="video " data-video="{{id}}">','<span class="video_wrap smallVideo">','<a href="javascript:void(0);" onclick="return false;">','<span class="play_op"></span>','<img alt="视频缩略图" data-src="{{url1}}" width="400" src="/qzone/app/mood_v6/images/blank.gif" class="lazyload">','</a>','</span>','</div>'].join('');if(this.data.videototal>0){var i,video=this.data.video||[];for(i=0;i<video.length;i++){video[i].id=i;r.push(OOP.tpl.format(item_tpl,video[i]));}}else{return'';}
return r.join('');};ShareModel.prototype.getMusicThumbHTML=function(){var tpl=['<div class="music_wrap bor3 bg">','<div class="music_item">','<a class="img" href="http://music.qq.com/musicbox/html/music.html?songid={{id}}" target="_blank">','<img data-src="{{albumthumb}}" src="/qzone/app/mood_v6/images/blank.gif" class="lazyload">','<span class="tip icon_music_sign"></span>','</a>','<div class="info c_tx">','<p class="name">','<a href="javascript:void(0);" target="_blank">{{name}}</a>','</p>','<p class="singer">{{singername}}</p>','</div>','<div class="op">','<a class="btn_play c_tx bor2 bg js_play_audio" href="javascript:void(0);">','<b class="trig c_tx"></b>','</a>','</div>','</div>','<div class="player_holder none">','<a class="c_tx js_hide_audio" href="javascript:void(0);">收起</a>','<div class="flash_holder" id="qzshare_music_box-{{tid}}"></div>','</div>','<div class="extra c_tx3 none">','<span class="ui_mr10 qz_orgin_cnt" cnttype="share"></span>','</div>','</div>'].join('');var r=[];if(this.data.audiototal>0){var i,audio=this.data.audio||[];for(i=0;i<audio.length;i++){if(audio[i].albumid>0){audio[i].albumthumb=['//',(window.siDomain||'qzonestyle.gtimg.cn'),'/music/photo/album/',audio[i].albumid%100,'/150_albumpic_',audio[i].albumid,'_0.jpg'].join('');}else if(audio[i].albumimg){audio[i].albumthumb=audio[i].albumimg;}else{audio[i].albumthumb='//music.qq.com/musicbox/img/uccpic_error.jpg';}
audio[i].tid=this.data.tid;audio[i].singername='';r.push(OOP.tpl.format(tpl,audio[i]));}}else{return'';}
return r.join('');};ShareModel.prototype.getItemHTML=function(){var TPL=['<li class="feed" data-type="share" data-tid="{{tid}}" data-uin="{{uin}}" data-sourceurl="{{rt_share_title_url}}" data-seed="item-{{seed}}">','<div class="avatar"><a href="{{profile_url}}" target="_blank" title="{{nickname}}({{uin}})">','<span class="skin_portrait_round"></span>','<img data-src="{{avatar_url}}" src="/qzone/app/mood_v6/images/blank.gif" class="lazyload" alt="{{nickname}}({{uin}})"></a>','</div>','<div class="box bgr3">','<div class="arr bor3"><div class="bor_bg3"></div></div>','<div class="bd">',' {{user_link}} <span class="c_tx3"></span><span>{{content_html}}</span>','</div>','<div class="md">',' <div class="share bor2">','  <!--shartitle-->','  <div class="bd">','   <h5> <a class="c_tx" href="{{rt_share_title_url}}" target="_blank">{{rt_share_title}}</a>','   </h5>','   <!--sharcontent-->','   <p class="content">{{rt_share_summary}}</p>','  </div>','  <div class="md">','   <!-- 附件类 结构跟转发的结构一样。 -->','   {{media_preview_html}}','  </div>','  <div class="ft">','   <div class="info c_tx3">','<span class="c_tx3">来自{{rt_source_html}}</span>','   </div>','   <div class="op c_tx3">','{{retweet_count_html}}','   </div>','  </div>',' </div>','</div>','{{location_html}}','<div class="ft">','<div class="info">','<span class="c_tx3">{{created_time}}</span><span class="c_tx3"> 来自{{source_html}}</span>','</div>','<div class="op">','<a href="javascript:void(0);" class="c_tx {{report_style}} mouseOver report visitor_display">举报</a>','<a href="javascript:void(0);" class="c_tx {{delete_style}} del author_display">删除</a>','<a href="javascript:void(0);" class="c_tx none">赞</a>','<span id="like_btn_{{tid}}"></span>','<a href="{{permalink}}" class="c_tx comment_btn" target="_blank" onclick="return false;" id="comment_btn_{{tid}}">{{comment_count_html}}</a>','<a href="{{permalink}}" class="c_tx forward_btn" target="_blank" onclick="return false;">{{forward_num_html}}</a>','</div>','</div>','<div class="box_extra bor3">','<div class="box_extra_arr bor3"><div class="bor_bg3"></div></div>','<div class="feed_like" id="feed_like_{{tid}}" style="display:none;">','<i class="icon_zan"></i>4917人觉得很赞','</div>','<!-- 评论区 -->','<div class="mod_comment" id="comment_list_{{tid}}">','{{mod_comments}}','<!--发表框 默认-->','<div class="mod_commnets_poster"><!--如果，发表框在评论列表上面，请加上 class mod_commnets_poster_top 谢谢-->','<div class="comments_poster_bd comments_poster_default">','<div class="comments_box">','<div class="textinput textinput_default bor2" contentEditable="true" placeholder="我也说一句">我也说一句</div>','</div>','</div>','</div>','</div>','</div>','</div>','<div class="box_shadow"><div class="shadow_left"></div><div class="shadow_right"></div></div>','</li>'].join('');return OOP.tpl.format(TPL,this.toJSON());};var photoStartIndex=0;var _get_multi_mood_photos=function(opt){if(opt.appid==5000){if(typeof opt.success=='function'){opt.success({photos:[],total:0});}
return;}
var FETCH_MOOD_SIZE=40;opt||(opt={});var data={uin:opt.uin||'',ftype:0,sort:0,pos:photoStartIndex||0,num:FETCH_MOOD_SIZE,current_tid:opt.mainid,code_version:1,photo_scan_layer:1,format:'jsonp'};var cgi_host='http://taotao.qq.com/cgi-bin/emotion_cgi_msglist_v6';var r=new QZFL.JSONGetter(cgi_host,'_get_list'+Math.random(),data,'utf-8');var st=new Date();r.setReportRate&&r.setReportRate(80);r.onSuccess=function(d){if(d.code!==0){opt.fail&&opt.fail(d);return;}
d.msglist=d.msglist||[];var mmc=new MoodModelCollection({initialData:d});var photos=[];var total=0;mmc.each(function(mood){var _photos=mood.getPhotosSync();total+=_photos.length;for(var i=0;i<_photos.length;i++){var _photo=_photos[i];var p={'pre':_photos[i].pre,'url':_photo.origin,'pic_id':_photo.pic_id||'','name':'','width':_photo.big_width,'height':_photo.big_height,'index':i};if(_photo.hd_pic){p.origin_upload=1;p.origin_url=_photo.hd_pic;p.origin_height=_photo.hd_height;p.origin_width=_photo.hd_width;}
p.tid=mood.getTid();p.mood=mood;p._infoSrc=mood;photos.push(p);}});photoStartIndex+=FETCH_MOOD_SIZE;if(!total){opt.fail&&opt.fail({code:-1,message:'找不到对应的照片'});return;}
if(typeof opt.success=='function'){opt.success({photos:photos,total:total});}};r.onError=function(){if(window.obj2str&&data){data.duration=new Date()-st;var st1=new Date();var img=new Image();var timeToCDN;img.onload=function(){this.onload=null;timeToCDN=new Date()-st1;};setTimeout(function(){if(!timeToCDN){timeToCDN=-1;}
data.timetocdn=timeToCDN;window.console&&console.log('[info] mood_v6/api.js 拉取cgi出错:',data);try{data.ie=ua.ie;data.chrome=ua.chrome;data.firefox=ua.firefox;}catch(err){}
_reportString(101003,obj2str(data),100);},3000);img.src='http://qzonestyle.gtimg.cn/qzone/app/mood_v6/images/blank.gif?r='+Math.random();}};r.send('_Callback');};var _get_mood_photos=function(opt){if(opt.appid==5000){_get_multi_details(opt);return;}
opt=opt||{};var data={tid0:opt.tid||'',uin0:opt.uin||0,source0:opt.source||0,num:1,uin:opt.loginUin,out_charset:'utf-8',format:'jsonp'};var cgi_host='http://taotao.qq.com/cgi-bin/emotion_cgi_getmsgs_detail';var jg=new QZFL.JSONGetter(cgi_host,'get',data,'utf-8');jg.setReportRate&&jg.setReportRate(15);var st=new Date();jg.onSuccess=function(d){if(d.code!==0){opt.fail&&opt.fail(d);return;}
d.data=d.data||{};d.data.msglist=d.data.msglist||[];var mmc=new MoodModelCollection({initialData:d.data});var isMusic=false;var photos=[];mmc.each(function(mood){var _photos=mood.getPhotosSync();for(var i=0;i<_photos.length;i++){var _photo=_photos[i];var p={'pre':_photo.pre,'url':_photo.origin,'pic_id':_photo.pic_id||'','name':'','width':_photo.big_width,'height':_photo.big_height,'index':i};if(_photo.hd_pic){p.origin_upload=1;p.origin_url=_photo.hd_pic;p.origin_height=_photo.hd_height;p.origin_width=_photo.hd_width;}
p.tid=mood.getTid();p.mood=mood;p._infoSrc=mood;photos.push(p);}});if(!photos.length){opt.fail&&opt.fail({code:-1,message:'找不到对应的照片'});return;}
if(typeof opt.success=='function'){opt.success(photos);}
if(d.data.msglist.length>0&&d.data.msglist[0]){_user_tracker({uin:d.data.msglist[0].uin,id:d.data.msglist[0].tid,src:0x0F});}else{opt.fail&&opt.fail(d);}};jg.send('_Callback');};var _get_detail_info_sync=function(photo){var mood=photo.mood;return{'name':mood.getCreatedTime(),'getDescHTML':function(){musicList=mood.getVoiceList();if(musicList&&musicList.length){var html=mood.getVoiceHTML();return html;}
var rtText=null;if(mood.getRTMood()){rtText=mood.getRTMood().getHTML();}
if(rtText){return mood.getBroadcast()+" || "+mood.getRTMood().getUserLink()+":"+rtText;}else{return mood.getHTML();}},'uin':mood.getAuthor().getUin(),'link':'http://user.qzone.qq.com/'+mood.getAuthor().getUin()+'/mood','albumname':''};};var _get_owner_info_sync=function(photo){var mood=photo.mood;if(!mood){return null;}
var info={uin:mood.getAuthor().getUin(),nickname:restXHTML(mood.getAuthor().getName())};return info;};var cgi_list={'index':{'url':'http://taotao.'+document.domain+'/cgi-bin/emotion_cgi_get_mix_v6','idc':0},'mine':{'url':'http://taotao.'+document.domain+'/cgi-bin/emotion_cgi_msglist_v6','idc':1},'weibo':{'url':'http://taotao.'+document.domain+'/cgi-bin/emotion_cgi_get_tweet_msgs_v6','idc':0},'feedlist':{'url':'http://sh.taotao.'+document.domain+'/cgi-bin/emotion_cgi_feedlist_v6','idc':0},'schedule':{'url':'http://taotao.'+document.domain+'/cgi-bin/emotion_cgi_timershuoshuolist_v6','idc':0}};MOOD.api=MOOD.api||{};MOOD.api.get=_get;MOOD.api.getPhotosForTopic=_get_photos;MOOD.api.get_multi_details=_get_multi_details;MOOD.api.visitReport=_user_tracker;MOOD.api.user=UserObject;MOOD.DataStorage=MOOD.DataStorage||{};MOOD.api.getMoodPhotos=_get_mood_photos;MOOD.api.getPhotos=_get_multi_mood_photos;MOOD.api.getOwnerInfo=_get_owner_info_sync;MOOD.api.getDetailInfo=_get_detail_info_sync;window.SLIDEVIEW_MOD_311=MOOD.api;var scope={'UserObject':UserObject,'MoodModel':MoodModel,'MoodModelCollection':MoodModelCollection,'ShareModel':ShareModel};MOOD.load=function(opt,fn){MOOD.Object=MOOD.Object={};var list=[];if(typeof opt=='string'){if(opt=='*'){MOOD.Object=scope;}else{list.push(opt);}}else{list=opt||[];}
for(var i=0;i<list.length;i++){if(typeof scope[list[i]]!='undefined'){MOOD.Object[list[i]]=scope[list[i]];}}
if(typeof fn!='undefined'){fn(MOOD.Object);};};MOOD.DataStorage.get=function(id){return ItemDataStorage[id];};MOOD.DataStorage.set=function(tid,data){if(typeof ItemDataStorage[tid]=='undefined'){return new MoodModel(data);}
return ItemDataStorage[tid];};})(MOOD);var apiInited=true;