
var BASEDOMAIN=TOP.g_Base_Domain,MAINDOMAIN=TOP.g_Main_Domain,loginUin=0,hostUin=0,userInfoCache,feedInit=false,currTab='',cityInit=false,isowner=false,addClass=QZFL.css.addClassName,delClass=QZFL.css.removeClassName,addEvent=QZFL.event.addEvent,delEvent=QZFL.event.removeEvent,tc=QZONE.FP.getStatPackage(),trim=TOP.trim,provinces=[],cities={},likeData={},foldStat={},likeGet=false,alpha=1,isLikeTab=false,isFeedTab=false,isInfoTab=false,likeLength=11,isAuth=QZONE.FP.getUserBitmap(52);function init(){var loginUin=TOP.checkLogin(),type=TOP.g_type,hostUin=TOP.g_iUin,tab=getParameter("tab"),tcisd=QZONE.FP.getStatPackage(),fp=QZONE.FP;if(TOP.g_GFPLite){addClass($('icon_container'),'none');addClass($('owner_info_cont'),'none');}
if(loginUin||(type!='M'&&type!='S')){if((TOP.checkLogin()==TOP.g_iUin)&&(QZONE.cookie.get("skey"))){addEvent($("edit_icon_link"),"click",function(evt,fp,tcisd){fp&&fp.toApp('/profile/qqtx');QZFL.event.preventDefault(evt);},[fp,tcisd]);addEvent($('edit_base_info'),'click',function(evt,fp,tcisd){fp&&fp.toApp('/profile/qzbase');tcisd&&tcisd.hotClick('profile_space.signature.changebasic','uinfo.qzone.qq.com');QZFL.event.preventDefault(evt);},[fp,tcisd]);addEvent($('edit_favor_info'),'click',function(evt,fp,tcisd){fp&&fp.toApp('/profile/qzinterest');QZFL.event.preventDefault(evt);},[fp,tcisd]);addEvent($('edit_favor'),'click',function(evt,fp,tcisd){fp&&fp.toApp('/profile/qzinterest');tcisd&&tcisd.hotClick('profile_space.signature.changeinterests','uinfo.qzone.qq.com');QZFL.event.preventDefault(evt);},[fp,tcisd]);delClass($("edit_base_info"),"none");delClass($("edit_favor_info"),"none");delClass($("select_icon"),"none");delClass($("inter_edit"),"none");isowner=true;}
if(tab==""){if(isowner){tab='info';}else{tab='feeds';}}
addClass($('info_loading'),'none');if(tab=='like'){isLikeTab=true;showLikeTab();}
if(tab=='feeds'){isFeedTab=true;showFeedTab();}
if(tab=='info'){isInfoTab=true;showInfoTab();}
getUserInfo();setTimeout(function(){getStateCityCode();},0);if(isowner){$("icon_container").innerHTML='<a href="javascript:;" onclick="popupEditor();return false;" class="bor2"><img id="user_icon" src="'+QZONE.FP.getPURL(TOP.g_iUin,100)+'"/></a>';}else{$("icon_container").innerHTML='<img id="user_icon" src="'+QZONE.FP.getPURL(TOP.g_iUin,100)+'"/>';}}else{delClass($('nologin'),'none');addClass($('feed_container'),'none');addClass($('info_preview'),'none');addClass($('info_loading'),'none');$("icon_container").innerHTML='<a class="bor2"><img id="user_icon" src="'+QZONE.FP.getPURL(TOP.g_iUin,100)+'"/></a>'}
if(isAuth){getFamousInfo();}
addEvent($("info_link"),"click",showInfoTab);addEvent($("feed_link"),"click",showFeedTab);addEvent($("city_link"),"click",showCityTab);addEvent($("like_link"),"click",showLikeTab);if(!TOP.g_GFPLite){getPhotos(hostUin);}}
function getParameter(name){var r=new RegExp("(\\?|#|&)"+name+"=([^&#]*)(&|#|$)");var m=location.href.match(r);return(!m?"":m[2]);}
var _fixPhotoData=function(photoData){var MAX_PHOTO_COUNT=6;var result=[];for(var i=0;photoData&&photoData.photos&&i<photoData.photos.length;i++){var photo=photoData.photos[i];if(!photo){continue;}
var _isShuoshuo=(photo.appid=='311');var ownerUin=QZONE.FP.getQzoneConfig('ownerUin');var fixedPhoto={appid:photo.appid,albumid:photo.albumId,albumname:photo.albumName,photoid:photo.lloc,photoname:photo.name,picjump:'http://user.qzone.qq.com/'+photo.uin+'/photo/new',albumjump:'http://user.qzone.qq.com/'+photo.uin+'/photo/new',size:0,sloc:photo.sloc,url:photo.url.replace(/&rf=[^&]+/,'')+'&rf=qzone_profile',topicid:_isShuoshuo?[ownerUin,photo.skey,1].join('_'):photo.albumId,pickey:_isShuoshuo?[photo.skey,ownerUin,photo.albumId,photo.lloc].join(','):photo.lloc,pre:photo.pre.replace(/&rf=[^&]+/,'').replace(/\/[mabico]\//,'/a/')+'&rf=qzone_profile'};result.push(fixedPhoto);}
return result.slice(0,MAX_PHOTO_COUNT);}
function getPhotos(uin){var url='http://ic2.qzone.qq.com/cgi-bin/feeds/feeds2_html_picfeed_qqtab',data={'appid':4,'notice':0,'hostUin':QZONE.FP.getQzoneConfig('ownerUin'),'inCharset':'utf-8','outCharset':'utf-8','format':'jsonp','source':'qqinfotab','plat':'qzone','uin':QZONE.FP.getQzoneConfig('loginUin'),'list':'1','contain':0,'refer':'qqinfotab','fuin':QZONE.FP.getQzoneConfig('ownerUin')},jg;jg=new QZFL.JSONGetter(url,'feeds2_html_picfeed_qqtab',data,'utf-8');jg.onSuccess=function(responseData){if(responseData&&!responseData.code){showPhotos(_fixPhotoData(responseData.data)||[]);}};jg.send('_Callback');}
function showPhotos(photoArray){var html,len=photoArray.length,dom;if(len){html=['<ul>'];for(var i=0;i<len;i++){html.push(genPhotoHTML(photoArray[i]));}
html.push('</ul>');dom=$('photo_list');dom.innerHTML=html.join('');delClass(dom,'none');QZFL.event.delegate(dom,'a','click',function(evt){var tc=TOP.TCISD,url,albumid,photoid,appid,topicId,picKey,pre;tc&&tc.hotClick('profile_space.recentpics','uinfo.qzone.qq.com');albumid=this.dataset?this.dataset.albumid:this.getAttribute('data-albumid');photoid=this.dataset?this.dataset.photoid:this.getAttribute('data-photoid');appid=this.dataset?this.dataset.appid:this.getAttribute('data-appid');topicId=this.dataset?this.dataset.topicid:this.getAttribute('data-topicid');picKey=this.dataset?this.dataset.pickey:this.getAttribute('data-pickey');pre=this.dataset?this.dataset.pre:this.getAttribute('data-pre');var param={appid:appid,from:"profile",ownerUin:QZONE.FP.getQzoneConfig('ownerUin'),topicId:topicId,picKey:picKey,pre:pre,timeStamp:new Date()}
QZONE.FP.openViewer(param);QZFL.event.preventDefault(evt);});}}
function genPhotoHTML(data){var tmpl='<li><a href="javascript:;" style="width:102px;height:100px" class="thumbnail bor2" data-topicid="{topicid}" data-pickey="{pickey}" data-pre="{pre}" data-appid="{appid}" data-url="{picjump}" data-albumid="{albumid}" data-photoid="{photoid}"><img onload="resizeImage(this)" src="{pre}" alt="{photoname}"></a></li>';if(data.url){data.photoname=QZFL.string.escHTML(data.photoname);return QZFL.string.format(tmpl,data);}else{return'';}}
function getUserInfo(){var CGI_URL="http://"+BASEDOMAIN+"/cgi-bin/user/cgi_userinfo_get_all",data={"uin":TOP.g_iUin,"vuin":TOP.checkLogin(),fupdate:1,"rd":Math.random()},jg=new QZFL.JSONGetter(CGI_URL,"cgi_userinfo_get_all",data,"utf-8");jg.onSuccess=function(re){if(!~~re.code){re=re.data;userInfoCache=re;initView(re);renderProgress();addClass($('info_loading'),'none');if(!isLikeTab&&!isFeedTab){delClass($('info_preview'),'none');}}else{if(re.code==-3000){QZONE.FP.showLoginBox("mall",function(){init();});}else{re.message&&(QZONE.FP.showMsgbox(re.message));}}};jg.onError=showError;jg.send("_Callback");var data={hostuin:TOP.g_iUin},CGI_UCG_URL="http://snsapp.qzone.qq.com/cgi-bin/qzonenext/getplcount.cgi";creq=new QZFL.JSONGetter(CGI_UCG_URL,'getplcount',data,"utf-8");creq.onSuccess=function(o){if(o&&o.count&&o.result&&o.result.code==0){function displayNumberMoreExactly(num){var ret;if(num<0){ret=0;}else if(num<10000){ret=num;}else if(num<100000){ret=Math.floor(num/1000);ret=ret/10;ret=ret+'<sub>万</sub>';}else if(num<990000){ret=Math.floor(num/10000)+'<sub>万</sub>';}else if(num>990000&&num<Number.MAX_VALUE){ret='99<sub>万</sub>';}else{ret=0;}
return ret;};var blog=$("profile-blog-cnt"),xc=$("profile-photo-cnt"),ss=$("profile-mood-cnt"),info=o.count;blog.innerHTML=displayNumberMoreExactly(info.RZ);xc.innerHTML=displayNumberMoreExactly(info.XC);ss.innerHTML=displayNumberMoreExactly(info.SS);delClass($("profile-cnt"),'none');}};creq.onError=QZFL.emptyFn;creq.send("_Callback");if((TOP.checkLogin()==TOP.g_iUin)&&(QZONE.cookie.get("skey"))){delClass($("edit_icon_info"),'none');}}
function popupEditor(){var title='修改头像照片',src=QZFL.media.getFlashVersion().major>9?'/qzone/setting/profile_native_icon.html':'/qzone/newprofile/profile_select_image.html';QZONE.FP.popupDialog(title,{src:src+"?mode=8&type=2"},410,410,false);}
function setUserIcon(){$('user_icon').src=QZONE.FP.getPURL(loginUin,100)+"?rd="+Math.random();clearIconCache();}
function clickPicNumber(){QZONE.FP.toApp('/photo');}
function clearIconCache(){var loginUin=TOP.checkLogin(),iconArr=[QZONE.FP.getPURL(loginUin,100),QZONE.FP.getPURL(loginUin,50),QZONE.FP.getPURL(loginUin,30)];for(var i=0;i<3;i++){var xhr=new QZFL.XHR(iconArr[i],"getIcon"+i,"GET",null,true,true);xhr.charset="utf-8";xhr.onSuccess=function(){var d;if(d=TOP.$('ownerIcon')){d.src=iconArr[1]+"?rd="+Math.random();}};xhr.send();}}
function getFamousInfo(){var CGI_URL='http://p1.qzone.qq.com/cgi-bin/famous_space_get_info',data={"uin":TOP.g_iUin,"vuin":TOP.checkLogin(),"rd":Math.random()},jg=new QZFL.JSONGetter(CGI_URL,"vpage_authinfo",data,"utf-8");jg.onSuccess=function(re){if(re.ret==0){var desc=re.data.desc;if(desc.length>40){$('auth_detail').title=desc;$('auth_detail').innerHTML=desc.substring(0,40)+"...";}else{$('auth_detail').innerHTML=desc;}
delClass($('auth_panel'),'none');}};jg.onError=showError;jg.send("_Callback");}
function getLikeData(){var CGI_URL="http://page.qq.com/cgi-bin/profile/interest_get",data={"uin":TOP.g_iUin,"vuin":TOP.checkLogin(),"flag":1,"rd":Math.random(),"fupdate":1,"g_tk":QZFL.pluginsDefine&&QZFL.pluginsDefine.getACSRFToken()},jg=new QZFL.JSONGetter(CGI_URL,"interest_get",data,"utf-8");QZONE.FP.showMsgbox("获取数据中...",6,10000);jg.onSuccess=cacheLikeData;jg.onError=showError;jg.send("_Callback");}
function cacheLikeData(re){QZONE.FP.hideMsgbox();if(!~~re.code){re=re.data;var items,t=[],html='',notify=[],start=12;likeData=re;likeGet=true;for(var i=0;i<likeLength;i++){html='';if(typeof re[i]!='undefined'){items=re[i].items;if(items.length>0){t=[];if(items.length>6){for(var j=0;j<6;j++){var oname=escHTML(items[j].topic),tname=QZFL.string.getRealLen(oname)>20?QZFL.string.cut(oname,20):oname
uin=typeof items[j].uin!='undefined'?items[j].uin:0;if(typeof items[j].page!='undefined'&&items[j].page==1){t.push('<li><p class="user_pic"><a class="c_tx q_namecard" link="nameCard_'+uin+'" target="_blank" href="http://page.qq.com/'+encodeURIComponent(items[j].topic)+'"><img onload="imgOnload(this);" alt="'+escHTML(items[j].topic)+'" src="'+'http://page.qq.com/cgi-bin/profile/page_logo?key='+encodeURIComponent(items[j].topic)+'&size=50"></a></p><p><a class="c_tx q_namecard" link="nameCard_'+uin+'" title="'+oname+'" target="_blank" href="http://page.qq.com/'+encodeURIComponent(items[j].topic)+'">'+tname+'</a></p></li>');}else{t.push('<li><p class="user_pic"><img onload="imgOnload(this);" alt="'+escHTML(items[j].topic)+'" src="'+'http://page.qq.com/cgi-bin/profile/page_logo?key='+encodeURIComponent(items[j].topic)+'&size=50"></p><p><span title="'+oname+'">'+tname+'</span></p></li>');}}
delClass($('a_'+i),'none');}else{for(var j=0;j<items.length;j++){var oname=escHTML(items[j].topic),tname=QZFL.string.getRealLen(oname)>20?QZFL.string.cut(oname,20):oname
uin=typeof items[j].uin!='undefined'?items[j].uin:0;if(typeof items[j].page!='undefined'&&items[j].page==1){t.push('<li><a class="c_tx q_namecard" link="nameCard_'+uin+'" target="_blank" href="http://page.qq.com/'+encodeURIComponent(items[j].topic)+'"><p class="user_pic"><img onload="imgOnload(this);" alt="'+escHTML(items[j].topic)+'" src="'+'http://page.qq.com/cgi-bin/profile/page_logo?key='+encodeURIComponent(items[j].topic)+'&size=50"></p></a><p><a class="c_tx q_namecard" link="nameCard_'+uin+'" title="'+oname+'" target="_blank" href="http://page.qq.com/'+encodeURIComponent(items[j].topic)+'">'+tname+'</a></p></li>');}else{t.push('<li><p class="user_pic"><img onload="imgOnload(this);" alt="'+escHTML(items[j].topic)+'" src="'+'http://page.qq.com/cgi-bin/profile/page_logo?key='+encodeURIComponent(items[j].topic)+'&size=50"></p><p><span title="'+oname+'">'+tname+'</span></p></li>');}}}
html=t.join('');}else{html='暂未填写';}}else{html='暂未填写';}
if(i<start){$('ul_'+i).innerHTML=html;}else{notify.push(html);}
QZONE.namecard.init($("like_container"));}
QZONE.FP.scrollNotify=function(pixelToBottom){if(!QZFL.css.hasClassName($('like_container'),'none')&&start<12){var html=notify.shift(),s=$('ul_'+start);s&&(s.innerHTML=html);start++;html=notify.shift(),s=$('ul_'+start);s&&(s.innerHTML=html);start++;}};}}
function resizeImage(t){var w=t.width,h=t.height;if(w>h){t.style.top=-((h*98)/w-98)/2+'px';t.style.width='98px';}else if(w==h){t.style.height='98px';}else{t.style.left=-((w*98)/h-98)/2+"px";t.style.height='98px';}};function imgOnload(t){var w=t.width,h=t.height;if(w>h){t.style.left=-((w*50)/h-50)/2+"px";t.style.height='50px';}else if(w==h){t.style.height='50px';}else{t.style.top=-((h*50)/w-50)/2+'px';t.style.width='50px';}}
function fold(id){if(typeof foldStat[id]=='undefined'){var items=likeData[id].items,t=[];for(var j=0;j<items.length;j++){if(typeof items[j].page!='undefined'&&items[j].page==1){var uin=typeof items[j].uin!='undefined'?items[j].uin:0;t.push('<li><p class="user_pic"><a class="c_tx q_namecard" link="nameCard_'+uin+'" target="_blank" href="http://page.qq.com/'+encodeURIComponent(items[j].topic)+'"><img onload="imgOnload(this);" class="" alt="'+escHTML(items[j].topic)+'" src="'+'http://page.qq.com/cgi-bin/profile/page_logo?key='+encodeURIComponent(items[j].topic)+'&size=50"></a></p><p><a class="c_tx q_namecard" link="nameCard_'+uin+'" title="点击查看详情" target="_blank" href="http://page.qq.com/'+encodeURIComponent(items[j].topic)+'">'+escHTML(items[j].topic)+'</a></p></li>');}else{t.push('<li><p class="user_pic"><img onload="imgOnload(this);" class="" alt="'+escHTML(items[j].topic)+'" src="'+'http://page.qq.com/cgi-bin/profile/page_logo?key='+encodeURIComponent(items[j].topic)+'&size=50"></p><p>'+escHTML(items[j].topic)+'</p></li>');}}
$('ul_'+id+'1').innerHTML=t.join('');addClass($('ul_'+id),'none');delClass($('ul_'+id+'1'),'none');foldStat[id]=1;$('a_'+id).innerHTML='收起&uarr;'}else{if(foldStat[id]==1){addClass($('ul_'+id+'1'),'none');delClass($('ul_'+id),'none');foldStat[id]=0;$('a_'+id).innerHTML='更多&darr;'}else{addClass($('ul_'+id),'none');delClass($('ul_'+id+'1'),'none');foldStat[id]=1;$('a_'+id).innerHTML='收起&uarr;'}}
QZONE.namecard.init($("like_container"));}
function getCommonFriendList(){var CGI_URL="http://"+TOP.g_R_Domain+"/cgi-bin/tfriend/friend_get_common_friends.cgi",data={"uin":TOP.g_iUin},jg=new QZFL.JSONGetter(CGI_URL,"friend_get_common_friends",data,"gb2312");jg.onSuccess=initCommonFriend;jg.onError=showError;jg.send("_Callback");}
function getStateCityCode(){var jg=new QZFL.JSONGetter("http://"+TOP.imgcacheDomain+"/qzone/address/1.js","address",null,"utf-8");jg.onSuccess=function(re){provinces=re.s;cities=re.c;if(typeof userInfoCache!='undefined'){initAddress();}};jg.onError=showError;jg.send("callback");}
function getMood(){var CGI_URL="http://taotao.qq.com/cgi-bin/emotion_cgi_firstutf8",data={"uin":TOP.g_iUin,"rd":Math.random()},jg=new QZFL.JSONGetter(CGI_URL,"qz_first_utf8",data,"utf-8");jg.onSuccess=function(re){if(typeof(re.items)!="undefined"){if(typeof(re.items[0])!="undefined"){$('mood_viewer').innerHTML=re.items[0].title;$('mood_date').innerHTML=re.items[0].pubDate;}}else{$('mood_viewer').innerHTML="暂未获取说说信息";}};jg.onError=showError;jg.send("callback");}
function showError(){}
function initView(re){var birthtxt,dateArr,emojiEle,emojiHTML=[],vipSpan;$("nickname_n").innerHTML=((trim(re.nickname)!="")?trim(QZONE.FP.removeUBB(escHTML(re.nickname))):"未填写");vipSpan=$('vip_span');vipSpan.innerHTML=QZONE.FP.getUserVipHTML('l',{'withYear':1,'className':'ui_mr5'});addEvent(vipSpan,'click',function(evt){tc&&tc.hotClick('isd.vip.normal.profile','mall.qzone.qq.com');});delClass($('nickname_icons'),'none');if(isAuth){delClass($('icon_auth'),'none');}
re.emoji=re.emoji||[];for(var i=0,len=re.emoji.length;i<len;i++){emojiHTML.push('<img src="',siDomain,'qzone_v6/img/emoji/',re.emoji[i],'.png" />');}
emojiEle=$('emoji');emojiEle.innerHTML=emojiHTML.join('');delClass(emojiEle,'none');QZONE.FP.getOwnerQZLevelIconHTMLAsyn(function(a){var span;if(a){span=$('qzoneLevel_span');span.innerHTML=a;span.className='';QZFL.event.addEvent(span,'click',function(){tc&&tc.hotClick('point-records','flower.qzone.qq.com');});}},1);if(re.sex_type==0){var s="";if(re.sex==1){s="男";}else if(re.sex==2){s="女";}
$('sex').innerHTML=re.sex==-1?'未填写':s;}else{addClass($('sex_li'),'none');}
if(re.age_type==0){var ag=(re.age==-1?'未填写':re.age);$('age').innerHTML=re.age==-1?'未填写':((trim(re.age)!="")?ag:"未填写");}else{addClass($('age_li'),'none');}
if(re.birthday_type==0){birthtxt=[re.birthyear||1980,/^(0[1-9]|1[012])-(0[1-9]|[12][01-9]|3[01])$/.test(re.birthday)?re.birthday:'01-01'].join('-');if(!/^\d{4}-\d{2}-\d{2}$/.test(birthtxt)){birthtxt='1980-01-01';}
dateArr=birthtxt.split('-'),b=getUserBirthdayStr(re,dateArr[0]-0,dateArr[1]-0,dateArr[2]-0);$('birthday').innerHTML=re.birthday=='00-00'?"未填写":((trim(re.birthday)!="")?b:"未填写");}else{addClass($('birthday_li'),'none');}
if(re.constellation_type==0){var con=re.constellation;$('astro').innerHTML=con==-1?'未填写':getAstroName(con);}else{addClass($('astro_li'),'none');}
initAddress();$('marriage').innerHTML=re.marriage==-1?'未填写':({1:'单身',2:'已婚',3:'保密',4:'恋爱中',5:'已订婚',6:'分居',7:'离异',0:'未填写'}[re.marriage]);$('blood').innerHTML={0:'其他',1:'A',2:'B',3:'O',4:'AB',5:'其他'}[re.bloodtype];$("career").innerHTML=(trim(re.career)!="")?trim(escHTML(re.career)):"未填写";$('company').innerHTML=(trim(re.company)!="")?trim(escHTML(re.company)):"未填写";$('caddress').innerHTML=trim(re.cb).length>0?escHTML(trim(re.cb)):"未填写";addClass($('user_interest_head'),'none');addClass($('user_interest_viewer'),'none');setFrameHeight();}
function initAddress(){var re=userInfoCache;if(re.address_type==0){if(trim(re.country+re.province+re.city)!=""){$('live_address').innerHTML='<span class="spacing">'+re.country+'</span> '+' <span class="spacing">'+re.province+'</span> '+' <span class="spacing">'+re.city+'</span>';}else{$('live_address').innerHTML='未填写';}}else{addClass($('live_address_li'),'none');}
if(re.home_type==0){if(trim(re.hco+re.hp+re.hc)!=""){$('hometown_address').innerHTML='<span class="spacing">'+re.hco+'</span> '+' <span class="spacing">'+re.hp+'</span> '+' <span class="spacing">'+re.hc+'</span>';}else{$('hometown_address').innerHTML='未填写';}}else{addClass($('hometown_address_li'),'none');}
if((typeof re.cco!='undefined')&&(typeof re.cp!='undefined')&&(typeof re.cc!='undefined')&&trim(re.cco+re.cp+re.cc)!=""){$('company_caddress').innerHTML=(trim(re.cco+" "+re.cp+" "+re.cc+" "+re.cb)!="")?('<span class="spacing">'+trim(re.cco)+'</span> '+' <span class="spacing">'+trim(re.cp)+'</span> '+' <span class="spacing">'+trim(re.cc)+'</span>'):"未填写";}else{$('company_caddress').innerHTML='未填写';}}
function showInfoTab(){if(currTab!='info'){addClass($('info_tab'),'nowtag');delClass($('feed_tab'),'nowtag');delClass($('like_tab'),'nowtag');delClass($('city_tab'),'nowtag');addClass($('feed_container'),'none');addClass($('like_container'),'none');addClass($('city_container'),'none');if(TOP.checkLogin()){delClass($('info_preview'),'none');}else{delClass($('nologin'),'none');}
currTab='info';}
tc.pv("uinfo.qzone.qq.com","/qzone/profile/index_"+currTab+".html");}
function showFeedTab(){if(currTab!='feeds'){addClass($('feed_tab'),'nowtag');delClass($('info_tab'),'nowtag');delClass($('like_tab'),'nowtag');delClass($('city_tab'),'nowtag');addClass($('info_preview'),'none');addClass($('like_container'),'none');addClass($('city_container'),'none');if(!feedInit){var src='http://ic2.'+(TOP.g_ICSet||'')+'qzone.qq.com/cgi-bin/feeds/feeds_html_module?i_uin='+TOP.g_iUin+'&i_login_uin='+TOP.g_iLoginUin+'&style='+(g_StyleID+"").replace("v6/","")+'&version='+parent.g_version+'&needDelOpr=true&hideExtend=false&showcount=15&MORE_FEEDS_CGI='+
encodeURIComponent('http://ic2.'+(TOP.g_ICSet||'')+'qzone.qq.com/cgi-bin/feeds/feeds_html_act_all')+'&refer=2',d=$('feed_container');if(QZFL.userAgent.ie==6){d.innerHTML='<iframe id="frameFeedList" width="100%" height="500" allowtransparency="true" scrolling="no" frameborder="0" ></iframe>';setTimeout(function(){$("frameFeedList").src=src;},0)}else{d.innerHTML='<iframe id="frameFeedList" width="100%" height="500" allowtransparency="true" scrolling="no" frameborder="0" src="'+src+'"></iframe>';}
feedInit=true;}
delClass($('feed_container'),'none');currTab='feeds';}
addClass($('nologin'),'none');tc.pv("uinfo.qzone.qq.com","/qzone/profile/index_"+currTab+".html");}
function showCityTab(){if(currTab!='city'){addClass($('city_tab'),'nowtag');delClass($('info_tab'),'nowtag');delClass($('like_tab'),'nowtag');delClass($('feed_tab'),'nowtag');addClass($('info_preview'),'none');addClass($('like_container'),'none');addClass($('feed_container'),'none');if(!cityInit){$("frameCity").src='http://'+TOP.imgcacheDomain+'/city_v1/static/qzonegrd/index.html';cityInit=true;}
delClass($('city_container'),'none');currTab='city';}
addClass($('nologin'),'none');tc.pv("uinfo.qzone.qq.com","/qzone/profile/index_"+currTab+".html");}
function showLikeTab(){if(!likeGet){getLikeData();}
if(currTab!='like'){addClass($('like_tab'),'nowtag');delClass($('info_tab'),'nowtag');delClass($('feed_tab'),'nowtag');delClass($('city_tab'),'nowtag');addClass($('info_preview'),'none');addClass($('feed_container'),'none');addClass($('city_container'),'none');delClass($('like_container'),'none');currTab='like';}
addClass($('nologin'),'none');tc.pv("uinfo.qzone.qq.com","/qzone/profile/index_"+currTab+".html");}
function initCommonFriend(re){if(typeof(re.title)!="undefined"){renderCommenFriend(re.title,re.flist);}else{QZONE.FP.showMsgbox(re.error.msg,5,3000);}}
function renderCommenFriend(title,flist){if(flist.length>0){var items=[];for(var i=0;i<flist.length;i++){var n=(trim(flist[i].nick)=="")?flist[i].uin:flist[i].nick;items.push('<li><a class="list_portrait" href="http://user.qzone.qq.com/'+flist[i].uin+'" target="_blank"><img src="'+flist[i].url+'" alt="去'+n+'的空间转转" /></a>');items.push('<a href="http://user.qzone.qq.com/'+flist[i].uin+'" target="_blank">'+n+'</a></li>');}
$("cf_list").innerHTML=items.join("");$("cf_title").innerHTML=title;}else{if(title=="您没有设置公开好友"){$("cf_title").innerHTML="公开好友";$('cf_none').innerHTML="您没有设置公开好友";}
delClass($("cf_none"),'none');}
delClass($("cf_panel"),'none');}
function setFrameHeight(){var bdy=setFrameHeight.body||(setFrameHeight.body=document.getElementsByTagName('body')[0]);if(bdy){try{var height=parseInt(frameElement.style.height),h=QZFL.dom.getSize(bdy)[1];if(height!=h){frameElement.height=h;}}catch(e){}}}
function getUserBirthdayStr(info,byear,bmonth,bdate){var b='',lunar=[];if(info.islunar&&info.islunar==1){if(TOP.g_iUin==TOP.checkLogin()){lunar=convertSolarToLunar(byear,bmonth,bdate);b=lunar[1]+lunar[2]+"(农历)";}else{b=getCapitalNum(bmonth,true)+getCapitalNum(bdate,false)+"日(农历)";}}else{b=bmonth+"月"+bdate+"日";}
return b;}
function renderProgress(){var o=userInfoCache,value=0,interest=o.interest,interestValue=0,profileValue=0,spaceValue=0;if(o.nickname){profileValue+=5;}
if(o.sex!=0){profileValue+=5;}
profileValue+=7;if(o.marriage!=-1){profileValue+=5;}
if(o.bloodtype!=-1){profileValue+=2;}
if(o.career){profileValue+=4;}
if(o.company){profileValue+=2;}
if(o.hco||o.hp||o.hc){profileValue+=5;}
if(o.country||o.province||o.city){profileValue+=7;}
if(o.cco||o.cp||o.cc||o.cb){profileValue+=1;}
if(o.spacename){spaceValue+=4;}
if(o.signature){spaceValue+=2;}
if(o.desc){spaceValue+=3;}
value=profileValue+interestValue+spaceValue;if(value>100){value=100;}
if(value==NaN){value=50;}
$("percent_div").style.width=value+"%";$("percent_txt").innerHTML=value+"%";}
function getAstroName(m){var astroName={1:'白羊座',2:'金牛座',3:'双子座',4:'巨蟹座',5:'狮子座',6:'处女座',7:'天秤座',8:'天蝎座',9:'射手座',10:'魔羯座',11:'水瓶座',12:'双鱼座'};return astroName[m+1];}
function getCityCode(p,c){var cs=cities[p];if(cs){for(var i=0;i<cs.length;i++){if(cs[i][0]==c){var _c=parseInt(cs[i][1],10)>9?cs[i][1]:"0"+cs[i][1];return getStateCode(p)+_c;break;}}}
return 0;}
function getStateCode(p){for(var i=0;i<provinces.length;i++){if(provinces[i][0]==p){return provinces[i][1];}}}
QZFL.pageEvents.pageBaseInit();QZFL.pageEvents.onloadRegister(init);/*  |xGv00|cb5fa3dcad8f44f5c60c4f3ee033b3cf */