(function(){MOOD.getFrameNode=function(){return parent.QZFL.dom.get("LayPageContainer")||parent.QZFL.dom.get("pageApp")};MOOD.viewport_=function(a){a=a||window;var b=0;"number"==typeof a.pageYOffset?b=a.pageYOffset:a.document.body&&a.document.body.scrollTop?b=a.document.body.scrollTop:a.document.documentElement&&a.document.documentElement.scrollTop&&(b=a.document.documentElement.scrollTop);a=a.innerHeight||a.document.documentElement.clientHeight||a.document.body.clientHeight;return{top:b,bottom:b+
a,height:a}};MOOD.isVisiable=function(a){var b=this.getFrameNode(),b=b?b.scrollTop:0,e=MOOD.viewport_(parent);$e(a);a=QZFL.dom.getPosition(a);top_diff=a.top-e.bottom-b;bottom_diff=a.bottom-e.top-b;return 0>=top_diff&&0<=bottom_diff+0};MOOD.loadIfVisiable=function(a,b){var e=a.getAttribute("data-img-load"),d=MOOD.isVisiable(a),c="rf=mood_app";"1"==QZONE.FP._t.QZFL.cookie.get("QZ_FE_WEBP_SUPPORT")&&(c+="&t=5");d&&"load"!=e&&(a.setAttribute("data-img-load","load"),a.getAttribute("data-tid"),$e(a).find("img").each(function(){if($e(this).hasClass("typeset-lazyload")){$e(this).removeClass("typeset-lazyload");
var a=this.getAttribute("data-src"),b=this.getAttribute("data-midsrc"),d=this.getAttribute("data-bigsrc");-1<(a||b||d).indexOf("http://p.qpimg.cn/cgi-bin/cgi_imgproxy")&&(c="");a&&c&&(a+=(-1<a.indexOf("?")?"&":"?")+c);b&&c&&(b+=(-1<b.indexOf("?")?"&":"?")+c);d&&c&&(d+=(-1<d.indexOf("?")?"&":"?")+c);var e=this.getAttribute("pic-width"),p=this.getAttribute("pic-height"),q=parseInt(this.getAttribute("pic-index"),10)+1;if(a){var l;QZFL.dom.searchChain(this,"parentNode",function(a){if(a&&$e(a).hasClass("img-item-"+
q))return l=a,!0});var b=QZFL.dom.getSize(l),g=b[0],f=b[1],b=400==g||400==f,h=this,m=new Image;m.onload=function(){this.width<g||this.height<f?(this.width/this.height>g/f?h.height=f:h.width=g,h.src=e>f&&p>f?d:this.src):(this.width/this.height>g/f?h.height=f:h.width=g,h.src=this.src)};m.src=b?d:a}}if($e(this).hasClass("lazyload")&&($e(this).removeClass("lazyload"),a=this.getAttribute("data-src"),b=this.getAttribute("data-isphoto"),-1<a.indexOf("http://p.qpimg.cn/cgi-bin/cgi_imgproxy")&&(c=""),a)){1==
b&&c&&(a+=(-1<a.indexOf("?")?"&":"?")+c);b=(this.getAttribute("data-limit")||"").split(",");2!=b.length&&(b=[400,300]);var n=400==b[0];QZFL.media.reduceImage(n?0:1,b[0],b[1],{trueSrc:a.replace("&amp;","&"),img:this,callback:function(a,b,d,c,e){n||(b=parseInt(QZFL.dom.getStyle(a,"width"),10),c=-(parseInt(QZFL.dom.getStyle(a,"height"),10)-c)/2,d=-(b-d)/2,c&&QZFL.dom.setStyle(a,"margin-top",c+"px"),d&&0>d&&QZFL.dom.setStyle(a,"margin-left",d+"px"))}})}}))};MOOD.loadVisiableItems=function(){$e(".mod_feed_lst#msgList li.feed").each(function(a,
b){MOOD.loadIfVisiable(this,b)})};MOOD.getDetailSuc=function(a){if(0>a.code)return{code:a.code,msg:a.message};var b={};b.source_name="\u670b\u53cb\u7f51"!=a.source_name&&"QQ\u7a7a\u95f4"!=a.source_name||isQzone?a.source_name:"";b.rt_source_name="\u670b\u53cb\u7f51"!=a.rt_source_name&&"QQ\u7a7a\u95f4"!=a.rt_source_name||isQzone?a.rt_source_name||"":"";b.auth_flag=a.auth_flag||0;b.right=a.right||1;b.commentlist=a.commentlist||[];b.replies=a.replies||a.msgTotal||b.commentlist.length;b.total=1;b.msglist=
[a];b.usrinfo=a.usrinfo;return b};MOOD.render=function(a){var b=QZFL.userAgent.windows?6>QZFL.userAgent.windows?"os_winxp":"os_win7":"os_mac";$e("html").addClass(b);MOOD.load("*",function(b){new b.MoodModelCollection({uin:MOOD.env.uin,type:MOOD.env.tab,hostUin:QZONE.FP.getQzoneConfig("onwerUin"),initialData:a,success:function(a){var b={mood:{comment:{max_comments_count:"mine"==MOOD.env.tab||"detail"==MOOD.env.tab?5:0,max_replies_count:5}}};"detail"==MOOD.env.tab&&(b.mood.comment.max_comments_count=
20,QZONE.FP.isFamousZone()&&(b.mood.comment.max_comments_count=0));a.setConfig(b);var b=document.getElementById("msgList"),e=a.getPagination();if("feedlist"==MOOD.env.tab&&1<e.page)QZFL.dom.insertAdjacent(b,2,a.getHTML());else{if(0>QZFL.object.route(a,"opts.initialData.code")){console.log("[ERROR] mood/index.js controller.load \u52a0\u8f7d\u6570\u636e\u5f02\u5e38\uff0c\u9519\u8bef\u7801:",QZFL.object.route(a,"opts.initialData.code"));b.innerHTML=QZFL.object.route(a,"opts.initialData.message")||QZFL.object.route(a,
"opts.initialData.msg")||"";return}if(0<a.getSizeSync())b.innerHTML=a.getHTML();else{a:{var k;switch(MOOD.env.tab){case "weibo":k="empty_home_sync";break;case "index":k="empty_feed_post";break;case "feedlist":case "mine":k=MOOD.env.loginUin==MOOD.env.uin?"empty_home_post":"empty_guest_post";break;case "schedule":k="empty_timing_post";break;case "detail":a="\u8be5\u6761\u8bf4\u8bf4\u5df2\u88ab\u5220\u9664";break a}a=tmpl('<img class="empty_pic_message" src="http://<%=siDomain%>/qzone_v6/img/shuoshuo/<%=imageName%>.png">',
{imageName:k,siDomain:siDomain})}b.innerHTML=a}}MOOD.loadVisiableItems()}})})}})();
/*  |xGv00|ae9695367a83d9aaa74379bc64674520 */