
window.requirejSolution||(window.defineRequirejSolution=function(){var base=window.g_Parent||parent;var map={76:1,20:2,74:3};var exp=base.QZONE.FrontPage.isAlphaUser(true)&&(!base.ua.ie||base.ua.ie>8)?2:(base.location.search!='?debug'&&map[base.g_iLoginUin%100]||0);var stamp={0:20130809,1:20130809,2:20130809,3:20130809};var url=['http://',base.siDomain||'qzonestyle.gtimg.cn','/qzone/app/jSolution/jSolution_1.0_qzone',exp?'_exp_'+exp:'','.js?max_age=31536000&ver=',stamp[exp]].join('');var callbacks=[];var onReady=function(){jSolution('1.0',function(j$){if(callbacks){for(var i=0,j=callbacks.length;i<j;i++){callbacks[i](j$);}
window.requirejSolution=function(callback){callback(j$);callback=null;};url=callbacks=onReady=null;}});};window.requirejSolution=function(callback){callbacks.push(callback);callback=null;if(window.jSolution){onReady();return;}
if(callbacks.length<=1){QZFL.imports([url],onReady);}};window.requirejSolution_url=url;})();/*  |xGv00|20b26fe399d750e07a2c5e85af22822a */
seajs.config({charset:'utf-8',timeout:5*60*1000,debug:0,paths:{'v8':'http://'+siDomain+'/qzone/v8/','app':'http://'+siDomain+'/qzone/app','mood':'http://'+(window.siDomain||'qzonestyle.gtimg.cn')+'/qzone/app/mood_v6'},alias:{'jquery':'http://'+siDomain+'/ac/lib/jquery/jquery-'+g_V.jq,'app/v8/config/1.0':'http://'+(window.siDomain||'qzonestyle.gtimg.cn')+'/c/=/qzone/app/v8/config/(.js,_.js,a.js,b.js,c.js,d.js,e.js,f.js,).js','migrate-plugin':'v8/engine/migrate-plugin.js'},preload:['migrate-plugin','app/v8/config/1.0']});/*  |xGv00|529fafcda151e122df8ac3d6ec21caad */
define('tcisd',null,function(require,exports,module){var env=require('app/v8/env/1.0');return env.base.TCISD;});/*  |xGv00|b5a28b2352d4edc95fb47e1acee930e8 */var throttle=function(a,b,c){return function(){var d=arguments;clearTimeout(null);setTimeout(function(){a.apply(b,d)},c||100)}};MOOD["interface"]={callExt:function(a,b){var c=this;QZFL.lang.isArray(b)||(b=[b]);seajs.use("app/mood_v6/script/msglist_ext",function(d){throttle(function(){d[a].apply(c,b)},d,200)()})}};
QZFL.object.extend(MOOD.util,{goProfile:function(a,b){if(a)switch(b+""){case "3":window.open("http://rc.qzone.qq.com/myhome/weibo/profile/"+a,"_blank");break;default:30<a.length?window.open("http://www.pengyou.com/index.php?mod=profile&u="+a+"&adtag=from_profile","_blank"):MOOD.util.go("index.html?tab=mine"+(a?"&uin="+a:""))}else MOOD.util.go("index.html?tab=mine")},showMention:function(a,b){QZFL.imports("http://"+siDomain+"/qzone/app/mood_v6/api/api.js",function(){var c=QZFL.FP.removeUBB(escHTML(a)),
c=c.replace(/(?:@\{uin:([^\}]*),nick:([^\},]*)(?:,who:(\d+))?\})|[^@]+/g,function(a,b,c,h){return b?(new MOOD.api.user({nickname:restXHTML(c||b),uin:b,who:h||1})).getProfileLink():a});$e(".new_comment_content_"+b).setHtml(c)})},getDateStr:function(a,b){var c,d,e,f,h,g;b=b||"YY-mm-dd";c=a?new Date(1E3*a):new Date;d=c.getFullYear();e=c.getMonth()+1;f=c.getDate();h=c.getHours();g=c.getMinutes();c=c.getSeconds();return b.replace("YY",d).replace("mm",e).replace("dd",f).replace("H",h).replace("i",g).replace("s",
c)},friendlyTime:function(a){return timeFormatString(new Date(1E3*a))},voiceFix:function(a){return a?"none":""}});
MOOD.event={init:function(){QZFL.event.addEvent(document.body,"click",MOOD.event.clickProxy)},clickProxy:function(a){var b=QZFL.event.getTarget(a);QZFL.dom.searchChain(b,"parentNode",function(a){if(a==window.document)return!1;a=$e(a);a.hasClass("goProfile")&&(MOOD.sendEvent("goProfile"),MOOD.util.goProfile(a.getAttr("profileUin"),a.getAttr("profilePft")));if(a.hasClass("goDetail")){var d=MOOD.lastComment.getItemElement(a);if(!d)return;d=$e(d).getAttr("tid");mood=MOOD.DataStorage.get(d);if(!mood||
!mood.data)return;MOOD.util.go("index.html?ref="+location.pathname+"&_tid="+mood.data.tid,{uin:mood.data.uin,tid:mood.data.tid,source:mood.data.t1_source})}if(a.hasClass("goSearch"))return MOOD.sendEvent("goSearch"),setTimeout(function(){MOOD.topic.search(a.getAttr("keyword"))},100),!1;if(a.hasClass("last_comment_button"))return MOOD.lastComment.popupComment(a),!0;if(a.hasClass("last_retweet_button"))return MOOD.lastComment.popupRetweet(a),!0;if(a.hasClass("mod-hot-change"))return MOOD.sendHotClick("/hottopic_change"),
t.refreshHotWords(),QZFL.event.preventDefault(a),!0;if(a.hasClass("topic_op_link"))return d=QZFL.dom.searchElementByClassName(b,"topic_item"),t.dolike(d),QZFL.event.preventDefault(a),!0;a.hasClass("ico_weibo")&&MOOD.sendEvent("guideToWeibo");a.hasClass("ico_qzone")&&MOOD.sendEvent("guideToQZone");a.hasClass("go_home")&&MOOD.sendEvent("go_home")})}};MOOD.widget={loadPager:function(a){window.F4A=window.F4A||{};QZFL.imports("http://"+QZONE.FP._t.siDomain+"/qzone/app/controls/pager/pager.js",a)}};
MOOD.poster={makeFakeFeed:function(a,b){var c=/(?:@\{uin:([\w-_]+),nick:([^\},]*)(?:,who:(\d+))?\})/;QZFL.console.print("new feed tid:"+a.t1_tid);b.skipMsgbox?b.skipMsgbox=!1:a.secret&&c.test(a.content)?QZONE.FP.showMsgbox("\u79c1\u5bc6\u8bf4\u8bf4\u53d1\u8868\u6210\u529f\uff01\u8be5\u6761\u8bf4\u8bf4\u4ec5\u81ea\u5df1\u53ef\u89c1\uff0c\u88ab\u63d0\u53ca\u7684\u7528\u6237\u4e0d\u80fd\u6536\u5230\u63d0\u9192\uff01",4,3E3):QZONE.FP.showMsgbox("\u53d1\u8868\u6210\u529f",4,2E3);b.skipMakeFeed?b.skipMakeFeed=
!1:(a.uin=a.t1_uin,a.t1_name=a.t1_uin,a.name=a.t1_name==a.t1_uin?QZONE.FP.getNickname():a.t1_name,a.createTime=a.t1_time,a.tid=a.t1_tid,a.source_name=a.t1_source_name,a.source_url=a.t1_source_url,a.certified=a.auth_flag||0,MOOD.updateFeeds(a),t.loadVisiableItems());a.secret&&MOOD.sendEvent("publish_private_mood")},init:function(a){var b,c=this;qzlog.info({cm:"MOOD_APP",cf:"init MoodPoster START"});seajs.use(["app/v8/controls/mood_poster/1.0","app/v8/utils/monitor/1.0","app/v8/controls/mood_poster/mood_editor_config/1.0"],
function(a,e,f){b=a.create({needSideBar:!0,needSyncQQ:!0,needSyncWeibo:!0,needSyncSetting:!0,needAuthorizeSetting:!0,needTimerSetting:!0,pluginConfig:{basicPlugins:f.BASIC_PLUGINS,imagePlugins:f.IMAGE_PLUGINS,funnyPlugins:f.FUNNY_PLUGINS,otherPlugins:f.OTHER_PLUGINS},resourceContainerConfig:{image:{needTypeset:!0,needDnd:!0,needOp:!0,addImageEntry:{local:!0,album:!0,screenCapture:!0,meitu:!0}}}});b.renderOn(document.getElementById("QM_Mood_Poster_Container"));MOOD.poster=b;b.addListener("onTemplateMoodPostSuccess",
function(a){c.makeFakeFeed(a,b)});b.addListener("onPluginPostSuccess",function(a){c.makeFakeFeed(a,b)});b.addListener("onPostSuccess",function(a){c.makeFakeFeed(a,b)});try{if(-1<top.location.href.indexOf("auto_show_funny")){b.onReady(function(){this.getUpupPoster(function(a){a.show();a.onFlashReady(function(){this.setInitialContent("")});this.hide()})});e.pv("taotaoact.qzone.qq.com","/mood_poster/auto_show_funny");return}if(-1<top.location.href.indexOf("poster=emoticon/avatar")){b.onReady(function(){b.getMoodEditor().initPlugins();
b.getMoodEditor().getFuncAttachBar(function(a){a&&a.callByPath("tabItems.emoticon.tabButton.onClick")})});e.pv("taotaoact.qzone.qq.com","/mood_poster/auto_show_avatar");return}-1<top.location.href.indexOf("auto_show_bubble")&&(b.onReady(function(){b.callByPath("moodEditor.loadPlugins",{template:{version:"2.0",enable:!0}},{onSuccess:function(){this.fireEvent("TEMPLATE_BTN_CLICKED")}})}),e.pv("taotaoact.qzone.qq.com","/mood_poster/auto_show_bubble"));-1<top.location.href.indexOf("auto_show_qutu")&&
(b.onReady(function(){b.callByPath("moodEditor.loadPlugins",{qutu:{version:"1.0",enable:!0}},{onSuccess:function(){var a=this;a.addEvent("MOOD_POSTER_QUTU_PLUGIN_READY",function(){a.fireEvent("QUTU_BTN_CLICKED")})}})}),e.pv("taotaoact.qzone.qq.com","/mood_poster/auto_show_qutu"));if(-1<top.location.href.indexOf("auto_show_flash_img"))b.onReady(function(){b.callByPath("moodEditor.loadPlugins",{flare_font:{version:"1.0",enable:!0}},{onSuccess:function(){var a=this;a.addEvent("MOOD_POSTER_FLARE_FONT_PLUGIN_READY",
function(){a.fireEvent("FLARE_FONT_BTN_CLICKED")})}})})}catch(h){e.pv("taotaoact.qzone.qq.com","/mood_poster/auto_show_error")}qzlog.info({cm:"MOOD_APP",cf:"init MoodPoster FINISHED"})})}};
MOOD.lastComment={itemElement:null,getItemElement:function(a){a=QZFL.event.getTarget(a);var b=null;QZFL.dom.searchChain(a,"parentNode",function(a){if(a==window.document)return!1;if(QZFL.css.hasClassName(a,"comment_feed")&&"LI"==a.tagName)return b=a,!0});return this.itemElement=b},getMoodData:function(a){a=this.getItemElement(a);a=$e(a).getAttr("tid");return(a=MOOD.DataStorage.get(a))&&a.data},dataMap:function(a){for(var b=t.l.msglist,c=0;c<b.length;c++){var d=b[c];if(d.tid==a)return d}},popup:function(a,
b){var c=this,d=["http://"+siDomain+"/qzone/app/mood_v6/plugin/CRPopupModel.js","http://"+siDomain+"/qzone/app/jSolution/jSolution_1.0_qzone.js"];with(QZONE.FP._t)QZFL.imports(d,function(){new CRPopupModel({type:b,item:{uin:a.uin,tid:a.tid},onPosted:function(a){c.countAll(a)}})})},popupComment:function(a){a=this.getMoodData(a);this.popup(a,1);MOOD.sendEvent("popup_newest_comment")},popupRetweet:function(a){a=this.getMoodData(a);this.popup(a,2);MOOD.sendEvent("popup_newest_retweet")},countOne:function(a){a=
$e(this.itemElement).find("."+a+"_num");var b=parseInt(a.getHtml());a.setHtml(++b)},countAll:function(a){for(var b=0;b<a.length;b++)this.countOne(a[b])}};
(function(){MOOD.mapTips={show:function(b,c,d){a.popupId&&a.hide();c=['<iframe id="checkinframe" src="http://',QZONE.FP._t.imgcacheDomain,"/qzone/app/controls/map/tips.html#posx=",c,"&posy=",d,'" allowtransparency frameborder="0" scrolling="no" style="width:300px;height:200px;"></iframe>'].join("");d={timeout:-1,backgroundColor:QZONE.FP._t.g_OFPLite?"#F5F6F6":"#FFFDF4",contentPadding:1,noQueue:!0,id:"TipsPopup",arrowPoint:1,arrowEdge:1,closeButtonSize:14,closeButtonColor:"red",width:302,height:202,
x:-14,y:3};var e=QZFL.dom.getXY(frameElement.parentNode),f=QZFL.dom.getXY(b),h=QZONE.FP._t.QZFL.dom.getClientHeight();e[1]+f[1]+220>h+QZONE.FP.getScrollTop()&&(d.arrowPoint=4,d.arrowEdge=3);a.popupId=QZFL.widget.tips.show(c,b,d);setTimeout(function(){QZFL.event.addEvent(document.body,"click",a.hide)},100)},hide:function(){QZFL.widget.tips.close(QZFL.widget.tips.instances[a.popupId]);QZFL.event.removeEvent(document.body,"click",a.hide);a.popupId=null}};var a=MOOD.mapTips})();
QZFL.object.extend(MOOD.util,{Forward:function(a){QZFL.imports("http://"+siDomain+"/qzone/app/controls/forwardingBox/forwardingBoxFacade.js",function(){QZONE.ICFeeds.App.ForwardingBox.bootstrap("",a);MOOD.sendEvent("retweet")},{charset:"utf-8"})}});
MOOD.sendPV=function(a){a&&setTimeout(function(){var b="taotao.qzone.qq.com",c=a;if("pengyou.com"==document.domain)switch(b="xiaoyou.qq.com",a){case "title":c="index/twitterv2.php";break;case "mytitle":c="index/twitterv2.php";QZONE.PY&&QZONE.PY.hasLeftBar&&QZONE.PY.hasLeftBar()&&(c="index/twitterv2/tab.php");break;case "guesttitle":c="index/twitterv2/tab.php";break;case "detail":c="index/twitterv2/detail.php";break;case "setting":c="index/twitterv2/setting.php";break;default:c=a}QZONE.FP.getStatPackage().pv(b,
"/"+c)},0)};MOOD.TCISDClick=function(a,b,c){b=b||"/";c=c||"taotaoact.qzone.qq.com";window.console&&console.log("TCISD:",a,b,c);try{QZONE.FP._t.TCISD.hotClick(a,c,b)}catch(d){}};MOOD.TCISDClick.batchBind=function(a,b){b=QZFL.object.extend({eventType:"mousedown",url:null,domain:null,container:document},b||{});var c={};QZFL.each(a,function(a,e){c[e]=function(){MOOD.TCISDClick(a,b.url,b.domain)}});MOOD.batchDelegate(c,b.container,b.eventType,!0)};
MOOD.batchDelegate=function(){var a=function(a,c){var d;$e(c).each(function(c){if(!d&&(c==a||QZFL.dom.isAncestor(c,a)))return d=c,!1});return d};return function(b,c,d,e){d=d||"click";c=c||document;QZFL.each(b,function(b,h){QZFL.event.delegate(c,h,d,function(c){var k=QZFL.event.getButton(c),l=QZFL.event.getTarget(c);!(l=a(l,h))||"click"==d&&0!=k&&l&&"A"==l.tagName&&0==(l.href||"").indexOf("http://")||(b(l),"A"!=l.tagName||e||QZFL.event.preventDefault(c))})})}}();
MOOD.sendEvent=function(a){a&&(a=a+"/v"+MOOD.version,setTimeout(function(){QZONE.FP.getStatPackage().pv("taotaoact.qzone.qq.com","/"+a)},0))};MOOD.sendHotClick=function(a){a&&setTimeout(function(){QZONE.FP.getStatPackage().hotClick(a,"taotaoact.qzone.qq.com")},0)};MOOD.pageStart=function(a){a();MOOD.event.init()};var mood=mood||{};mood.jumpPage=MOOD.jumpPage=function(a,b){MOOD.sendEvent("clickname");MOOD.util.goProfile(a,b)};
MOOD.jumpToAudit=function(){window.open("http://user.qzone.qq.com/"+QZONE.FP.getQzoneConfig("loginUin")+"/mood/jumpToAudit","_blank")};MOOD.resizeImage=function(a,b,c){if(!0!=a.loaded){a.loaded=!0;var d=new Image;d.onload=function(){d.width>b?(a.width=b,a.style.width=b+"px"):(a.width=d.width,a.style.width=d.width+"px");a.style.height="auto";a.style.display="block"};d.src=a.src}};MOOD.Music=MOOD.Music||{};
MOOD.Music.getAlbumImage=function(a){a=a||0;return 0<a?["//edu.qzs.qq.com/music/photo/album/",a%100,"/150_albumpic_",a,"_0.jpg"].join(""):"//music.qq.com/musicbox/img/uccpic_error.jpg"};
MOOD.Setting=function(a,b,c,d){var e=["sign_sync_ss","ss_sync_sign","ss_sync_tweet","ss_sync_share","sync_view"],f={},h,g;for(h=0;h<e.length;h++)g=e[h],f[g]=a[g];f[b]=c;f.hostuin=t.uin;a=MOOD.domain.getUrl("signset");f=new QZFL.FormSender(a,"post",f,"utf-8");f.onSuccess=function(a){MOOD.sendEvent("setting_submit_success");QZONE.FP.showMsgbox("\u8bbe\u7f6e\u6210\u529f",4,2E3);d&&d()};f.onError=function(a){MOOD.sendEvent("setting_submit_faild");QZONE.FP.showMsgbox("\u670d\u52a1\u5668\u5fd9\uff0c\u8bf7\u7a0d\u540e\u91cd\u8bd5\u3002")};
f.send()};
(function(a){var b={};a.domain={load:function(c,d,e){c=a.util.getHttpParams("uin")||QZONE.FP.getQzoneConfig("ownerUin");d=d=window._locationCache||{};d.result=d.result||{};e="taotao.qq.com";0==d.result.code?1==d.idcNo?e="taotao.qq.com":2==d.idcNo&&(e="sh.taotao.qq.com"):d={idcNo:1,result:{code:0},uin:c};d.uin=d.uin||c;window.locationCache=window.locationCache||[];window.locationCache.push(d);b["o"+c]=e},get:function(a,d){var e="o"+(a||"");d&&(e=e+"_"+d);return"string"==b[e]?b[e]:"taotao.qq.com"}}})(MOOD=MOOD||
{});
(function(){var a={index:["emotion_cgi_get_mix_v6",0],msglist:["emotion_cgi_msglist_v6",1],timer:["emotion_cgi_timershuoshuolist_v6",0],del_timer:["emotion_cgi_del_timershuoshuo_v6",0],pubnow_timer:["emotion_cgi_pubnow_timershuoshuo_v6",0],del:["emotion_cgi_delete_v6",0],comment:["emotion_cgi_comment_v6",0],delcomment:["emotion_cgi_delcomment_v6",0],reply:["emotion_cgi_addreply_v6",0],delreply:["emotion_cgi_delreply_v6",0],forward:["emotion_cgi_forward_v6",0],signset:["emotion_cgi_signset_v6",0],
setting:["emotion_cgi_setting_v6",0],mutireplies:["emotion_cgi_mutireplies_v6",0],multitopcomments:["emotion_cgi_multitopcomments_v6",0],addtopcomment:["emotion_cgi_addtopcomment_v6",0],getcomments:["emotion_cgi_getcomments_v6",0],get_pics:["emotion_cgi_get_pics_v6",0]};MOOD.domain.getUrl=function(b,c){var d=a[b],e="taotao.qq.com";d[1]&&(e=MOOD.domain.get(c));return"http://"+e+"/cgi-bin/"+d[0]}})();
(function(){function a(a){var b=null;QZFL.dom.searchChain(a,"parentNode",function(a){if(a==window.document)return!1;if(QZFL.css.hasClassName(a,"feed")&&"LI"==a.tagName)return b=a,!0});return b}function b(a){var b=null;QZFL.dom.searchChain(a,"parentNode",function(a){if(a==window.document)return!1;if(QZFL.css.hasClassName(a,"qz_shuoshuo_audio")&&"DIV"==a.tagName)return b=a,!0});return b}MOOD.MsgList=function(a){QZFL.object.extend(this,{extUrl:"http://"+QZONE.FP._t.siDomain+"/qzone/app/mood_v6/script/msgListExt.js?max_age=600&r="+
MOOD.version,callExt:MOOD["interface"].callExt,container:""},a);this.el=$e($(this.container));this.clickProxy();this.mouseProxy()};MOOD.MsgList.prototype={clickProxy:function(){var c=this;c.el.bind("click",function(d){var e=QZFL.event.getTarget(d),f=a(e),h=$e(f).getAttr("data-tid"),g=MOOD.DataStorage.get(h);if(g){var k=!1;QZFL.dom.searchChain(e,"parentNode",function(a){if(a==window.document)return!1;if(k)return!0;if(("IMG"==e.tagName||"A"==e.tagName)&&QZFL.css.hasClassName(a,"smallPic"))return g.data.timershuoshuo||
"pengyou.com"==document.domain?c.callExt("showBigPic",[g,f]):c.callExt("showSlideView",[g,e]),k=!0;if(QZFL.css.hasClassName(a,"see-all")){if(202==g.data.appid)return!0;c.callExt("showBigPic",[g,f]);return k=!0}if(QZFL.css.hasClassName(a,"passwrod_required"))return c.callExt("passwrodRequired",[g,f]),k=!0;if(QZFL.css.hasClassName(a,"apply_access"))return c.callExt("applyAccess",[g,f]),k=!0;if(QZFL.css.hasClassName(a,"edit_btn"))return QZONE.FP.showMsgbox("\u52a0\u8f7d\u4e2d...",6,5E3),c.callExt("edit",
[g,f]),k=!0;if(QZFL.css.hasClassName(a,"viewmap"))return c.callExt("viewMap",[g,f]),k=!0;if(QZFL.css.hasClassName(a,"js_play_record"))return a=b(e),c.callExt("playRecord",[g,f,a]),k=!0;if("A"==e.tagName&&QZFL.css.hasClassName(a,"timer_del"))return c.callExt("timer_del",[g,f]),k=!0;if("A"==e.tagName&&QZFL.css.hasClassName(a,"del"))return c.callExt("del",[g,f]),k=!0;if("A"==e.tagName&&QZFL.css.hasClassName(a,"timer_send_now"))return c.callExt("timer_send_now",[g,f]),k=!0;if("A"==e.tagName&&QZFL.css.hasClassName(a,
"forward_btn"))return c.callExt("showForward",[g,e]),k=!0;if("A"==e.tagName&&QZFL.css.hasClassName(a,"comment_btn"))return controller.initCommentModule(g.data,function(a){a.isCommentBoxVisible()||(a.show(),a.focus())}),k=!0;if("A"==e.tagName&&QZFL.css.hasClassName(a,"qz_like_btn"))return k=!0;if("A"==e.tagName&&QZFL.css.hasClassName(a,"rt_forward_btn"))return c.callExt("rtShowForward",[g,f]),k=!0;if("A"==e.tagName&&QZFL.css.hasClassName(a,"rt_comment_btn"))return c.callExt("rtShowComment",[g,f]),
k=!0;"A"==e.tagName&&QZFL.css.hasClassName(a,"report")&&(c.callExt("report",[g,f]),k=!0);if(QZFL.css.hasClassName(a,"smallVideo"))return c.callExt("playVideo",[g,f]),k=!0;if(QZFL.css.hasClassName(a,"js_play_audio"))return c.callExt("playAudio",[g,f]),k=!0;if(QZFL.css.hasClassName(a,"js_hide_audio"))return c.callExt("stopAudio",[g,f]),k=!0;if(QZFL.css.hasClassName(a,"goDetail"))return QZFL.event.preventDefault(d),c.callExt("goDetail",[g,f,a]),k=!0,!1;if(QZFL.css.hasClassName(a,"smallVote"))return c.callExt("showVote",
[g,f,e]),k=!0;if(QZFL.css.hasClassName(a,"smallAttach"))return c.callExt("showAttach",[g,f]),k=!0;if(QZFL.css.hasClassName(a,"js_collapse"))return QZFL.event.preventDefault(),c.callExt("collapse",[g,f]),k=!0;if(QZFL.css.hasClassName(a,"to_public"))return c.callExt("toPublic",[g,f]),k=!0;if(QZFL.css.hasClassName(a,"has_more_con"))return a=QZFL.css.hasClassName(a,"more_active"),c.callExt("showMoreContent",[g,f,1,a]),k=!0;if(QZFL.css.hasClassName(a,"rt_has_more_con"))return a=QZFL.css.hasClassName(a,
"more_active"),c.callExt("showMoreContent",[g,f,2,a]),k=!0});if(k)return QZFL.event.preventDefault(),!1}});(function(a,b,c){var h=$("msgList");QZFL.event.delegate(h,a,"mouseenter",function(a){"function"==typeof b&&b.call(this,a,this)});QZFL.event.delegate(h,a,"mouseleave",function(a){"function"==typeof c&&c.call(this,a,this)})})(".qz_shuoshuo_audio",function(a,b){QZFL.css.addClassName(b,"bor_bg6");QZFL.css.removeClassName(b,"bor2")},function(a,b){QZFL.css.addClassName(b,"bor2");QZFL.css.removeClassName(b,
"bor_bg6")})},mouseProxy:function(){var a=this.el.elements[0];seajs.use(["jquery","migrate-plugin"],function(b,e){b(a).on("mouseenter",".feed",function(a){b(a.currentTarget).addClass("feed_hover").find(".mouseOver").show()}).on("mouseleave",".feed",function(a){b(a.currentTarget).removeClass("feed_hover").find(".mouseOver").hide()});b(document).on("mouseenter",".more-edit-items",function(a){b(a.currentTarget).addClass("dropdown-open")}).on("mouseleave",".more-edit-items",function(a){b(a.currentTarget).removeClass("dropdown-open")});
b(document).on("click","a[role=menuitem]",function(){b(".more-edit-items").removeClass("dropdown-open")});b(document).on("mouseenter","a[role=menuitem]",function(a){b(a.currentTarget).addClass("bg2")}).on("mouseleave","a[role=menuitem]",function(a){b(a.currentTarget).removeClass("bg2")})})}}})();
(function(){var a=function(a){var b=function(){};this.config={IMG_LINK_TPL:'<a href="{link}" bosstrace="{bosstrace}" target="{target}" ><img src="{img}" bosstrace="{bosstrace}" url="{link}" alt="qboss_ad_image" /></a>',img_pid:"",img_container:null,img_onload:b,text_pid:"",text_container:null,text_onload:b,board_id:2096,support_multi:!0};a=a||{};QZFL.object.extend(this.config,a)};a.prototype.addImgOnLoadListener=function(a){"function"==typeof a&&(this.config.img_onload=a)};a.prototype.addTextOnLoadListener=
function(a){"function"==typeof a&&(this.config.text_onload=a)};a.prototype.show=function(){var a=this,b=function(b){var c=a.config.IMG_LINK_TPL,d=0,f=b||[];0<f.length&&(d=Math.floor(Math.random()*f.length),f[d].objExtData=(new Function("return"+f[d].extdata))(),f[d].objExtData.bosstrace=f[d].bosstrace,f[d].objExtData.target=-1!=f[d].objExtData.link.indexOf("javascript")?"":"_blank",a.config.img_container.innerHTML=format(c,f[d].objExtData));if(1<f.length&&a.config.support_multi){b=[];for(var g=0;g<
f.length;g++)b.push("<span>&#9679;</span>"),f[g].objExtData=(new Function("return"+f[g].extdata))(),f[g].objExtData.bosstrace=f[g].bosstrace;b.push('<div class="mask"></div>');$e(".pop_apps_wrap div.switcher").setHtml(b.join(""));var h=function(){$e(".pop_apps_wrap div.switcher span").each(function(a,b){b==d?$e(a).addClass("current"):$e(a).removeClass("current")})};h();setInterval(function(){d++;d>f.length-1&&(d=0);a.config.img_container.innerHTML=format(c,f[d].objExtData);h()},5E3)}else $e(".pop_apps_wrap div.switcher").setHtml("");
a.config.img_onload()},c=this.config.board_id,d={uin:QZONE.FP.getQzoneConfig("loginUin"),board_id:c},d=new QZFL.JSONGetter("http://boss.qzone.qq.com/fcg-bin/fcg_get_strategy",null,d,"utf-8");d.onSuccess=function(a){a=a||{};0==a.code&&a.data[c]&&0<a.data[c].items.length&&b(a.data[c].items)};d.send("_Callback")};window.Sponsors=a;var b=function(a){if(a=QZFL.event.getTarget(a))a=a.getAttribute("bosstrace")||"",(new Image).src="http://boss.qzone.qq.com/fcg-bin/fcg_rep_strategy?from=1&uin="+QZONE.FP.getQzoneConfig("loginUin")+
"&qboper=2&bosstrace="+a},c={img_pid:"qzone_shuoshuo_img_1",img_container:$("qzone_shuoshuo_img_1"),img_onload:function(){$e("#pop_apps_sponsors").removeClass("none");$e("#pop_apps_split").removeClass("none");$e("#qzone_shuoshuo_img_1").onClick(b)},text_pid:"qzone_shuoshuo_imgtxt_1",text_container:$("qzone_shuoshuo_imgtxt_1"),text_onload:function(){$e("#pop_apps_sponsors").removeClass("none");$e("#pop_apps_split").removeClass("none")}};(new a(c)).show();var d={IMG_LINK_TPL:'<a href="{link}" target="{target}"><img src="{img}" bosstrace="{bosstrace}" url="" alt="qboss_ad_image"/></a>',
img_container:$("bottom-sponsor"),board_id:2199,support_multi:!1,img_onload:function(){$e("#bottom-sponsor").onClick(b)}};setTimeout(function(){(new a(d)).show()},3E3)})();
(function(){seajs.use(["jquery"],function(a){a.getScript("http://taotao.qq.com/cgi-bin/cgi_sogou_hotwords?g_tk="+QZONE.FP.getACSRFToken()).done(function(){window.sogou_web_hdpic&&window.sogou_web_hdpic.data&&window.sogou_web_hdpic.data.length&&a(tmpl('<div class="word_spread side_panel"><div class="hd"><h3>\u5927\u5bb6\u90fd\u5728\u770b</h3></div><div class="bd"><ul><%for(var i=0;words && i<words.length && i<3;i++){%><li><a target="_blank" href="<%=escHTML(words[i].url)%>" title="<%=escHTML(words[i].title)%>"><%=escHTML(cut(words[i].title,30,\'..\'))%></a></li><%}%></ul></div></div><div class="split_line bor2"></div>',{words:(sogou_web_hdpic.data||
[]).sort(function(){return Math.random()-0.5}).sort(function(){return Math.random()-0.4}).sort(function(){return Math.random()-0.6})})).insertBefore(a('#app_mod [data-rel="mood_help"]'))})})})();
MOOD.topic={updateCount:function(a,b){b=b||[];var c,d=b.length,e=[];for(c=0;c<d;c++)e.push(b[c].likekey);c="http://"+QZONE.FP._t.g_R_Domain+"/cgi-bin/qzonesoso/cgi_qzonesoso_showlike";var f={uin:QZONE.FP.getQzoneConfig("loginUin"),keys:e.join(","),t:(new Date).getTime()};0<d&&(d=new QZFL.JSONGetter(c,null,f,"utf-8"),d.onSuccess=function(a){a=a.data||[];if(e.length==a.length)for(var b=0,c;b<a.length;b++)c="#"+e[b],$e(c).setHtml(a[b].count+a[b].liked)},d.send("callback"))},showHot:function(a){var b=
this,c={uin:QZONE.FP.getQzoneConfig("loginUin")},c=new QZFL.JSONGetter("http://r.qzone.qq.com/cgi-bin/qzonesoso/cgi_qzonesoso_hotword",null,c,"utf-8");c.onSuccess=function(c){if(0==c.ret&&c.data&&(c.data.resultdata=c.data.resultdata||[])){var e=tmpl(MOOD.tmp.hotTopic,{items:c.data.resultdata});$e($(a)).setHtml(e);b.updateCount(a,c.data.resultdata)}};c.send("callback");c={img_pid:"qzone_shuoshuo_img_1",img_container:$("qzone_shuoshuo_img_1"),img_onload:function(){$e("#pop_apps_sponsors").removeClass("none");
$e("#pop_apps_split").removeClass("none")},text_pid:"qzone_shuoshuo_imgtxt_1",text_container:$("qzone_shuoshuo_imgtxt_1"),text_onload:function(){$e("#pop_apps_sponsors").removeClass("none");$e("#pop_apps_split").removeClass("none")}};(new Sponsors(c)).show()},search:function(a){"qq.com"==document.domain?QZONE.FP.Search(a,{type:"mood"}):(a="http://www.pengyou.com/index.php?mod=twitterv2&act=topic#key="+encodeURI(a),window.open(a));return!1}};
function searchHot(a){13==QZFL.event.getEvent().keyCode&&(QZONE.FP.sendPV("taotao.qzone.qq.com","search"),MOOD.topic.search(a.value))}$e("#hotkeysearch").onBlur(function(){""==this.value&&(this.value="\u641c\u7d22\u5176\u4ed6\u70ed\u95e8\u8bdd\u9898...")});$e("#hotkeysearch").onFocus(function(){"\u641c\u7d22\u5176\u4ed6\u70ed\u95e8\u8bdd\u9898..."==this.value&&(this.value="")});$e("#hotkeysearch").onKeyPress(function(){searchHot(this)});
$e("#hotkeysearchbtn").onClick(function(){QZONE.FP.sendPV("taotao.qzone.qq.com","search");MOOD.topic.search($("hotkeysearch").value)});window.MOOD=window.MOOD||{};window.QZONE=window.QZONE||{};QZONE.FP=QZONE.FP||parent.QZONE.FrontPage;parent.QZFL.object.map(parent.QZFL.string,window);parent.QZFL.object.map(parent.QZFL.util,window);parent.QZFL.object.map(parent.QZFL.lang,window);MOOD.tmp=MOOD.tmp||{};MOOD.util=MOOD.util||{};
QZFL.object.extend(MOOD.util,{initLoader:function(a){var b=a.callbacks;a.onSuccess||(a.onSuccess=function(){for(var a;a=b.shift();)a.apply(null,arguments)})},loaders:{F4A:function(){var a=arguments.callee;MOOD.util.initLoader(a);if(window.F4A)a.onSuccess();else QZFL.imports("http://"+parent.siDomain+"/qzone/app/f4a/F4A_1.2.lite.js?max_age=600&ver=20120111",a.onSuccess)},jSolution:function(){var a=arguments.callee;MOOD.util.initLoader(a);if(window.jSolution)a.onSuccess();else MOOD.util.require("F4A",
function(){QZFL.imports("http://"+parent.siDomain+"/qzone/app/jSolution/jSolution_1.0_qzone.js",a.onSuccess)})},attachmentThumbnail:function(){var a=arguments.callee;MOOD.util.initLoader(a);MOOD.util.require("jSolution",function(){jSolution["1.0"].load({resName:"ThumbnailFacade",nsName:"/controls/attachBar",nsVer:"3.0",onSuccess:a.onSuccess})})}},require:function(a,b){var c=MOOD.util.loaders[a];(c.callbacks||(c.callbacks=[])).push(b);c()},getHttpParams:function(a){a=location.href.match(RegExp("(\\?|#|&)"+
a+"=([^&#]*)(&|#|$)"));return decodeURIComponent(a?a[2]:"").replace(/\+/g," ")},go:function(a,b){var c="";a.match(/^http/)||(c="http://"+parent.imgcacheDomain,a.match(/^\//)||(c+="/qzone/app/mood_v6/html/"));c+=a;b&&(c+="#"+genHttpParamString(b));try{window.location.href=c}catch(d){frameElement.src=c}},HTML:function(a){var b=/(?:@\{uin:([^\}]*),nick:([^\},]*)(?:,who:(\d+))?\})|[^@]+/g,c={"%7D":"}","%2C":",","%25":"%"};a=((a||"")+"").split(/(#(?:.|<br\/>)+?#)/g);for(var d="",e="",f,h,g,k,l=0;l<a.length;l++){e=
a[l];g=!1;h=f="";f=e.replace(/#((?:.|<br\/>)+?)#/g,function(a,b,c){g=!0;a="";return a='<a href="http://rc.qzone.qq.com/qzonesoso/?search='+encodeURIComponent(b)+'" target="_blank">#'+escHTML(b)+"#</a>"});if(!g){f="";mentions=e.split(/(@(?!^\{)[\{]uin\:[a-z\d]+\,nick\:[^}]*[\}])/g);for(e=0;e<mentions.length;e++)mention=mentions[e],k=!1,mention=mention.replace(b,function(a,b,d,e){if(d)for(var f in c)d=d.replace(f,c[f]);return b?(k=!0,format('@<a title="{uin}" target="_blank" href="http://user.qzone.qq.com/{uin}" class="c_tx">{name}</a>',
{uin:b,name:escHTML(d)})):escHTML(a)}),k||(mention=mention.replace(/((?:https|ftp|http):\/\/[-A-Z0-9+&@#\/%?=~_|!:,.;]*[-A-Z0-9+&@#\/%=~_|])/ig,'<a href="$1" target="_blank">$1</a>')),h+=mention;f=h}d+=f}return QZFL.FP.removeUBB(d)},getContent:function(a,b,c,d,e,f){var h=MOOD.util.getContent;h.tmpFn=h.tmpFn||tmpl(MOOD.tmp.content);return h.tmpFn({items:a,tid:c,uin:d,certified:e,nosafecheck:f||0})||MOOD.util.HTML(b)},parseContent:function(a){a=((a||"")+"").split(/(#(?:.|<br\/>)+?#)/g);for(var b=!1,
c="",d="",e=0;e<a.length;e++)tag=a[e],b=!1,c="",c=tag.replace(/#((?:.|<br\/>)+?)#/g,function(a,c,d){b=!0;a=QZONE.FP.removeUBB(QZONE.FP.replaceIconTag(escHTML(c)));return'<a href="http://rc.qzone.qq.com/qzonesoso/?search='+encodeURIComponent(c)+'" target="_blank">#'+a+"#</a>"}),b||(c=QZONE.FP.removeUBB(QZONE.FP.replaceIconTag(escHTML(tag)))),d+=c;return d},getRemark:function(a,b){var c;QZONE.FP.getRemarkList(function(a){c=a;$e(".remarkUin").each(function(){var a=$e(this),b=a.getAttr("uin");c[b]&&a.setHtml(escHTML(restHTML(c[b])))})});
this.getRemark=function(a,b){return c&&c[a]?escHTML(restHTML(c[a]||b||a)):['<span class="remarkUin" uin="',a,'">',escHTML(b||a),"</span>"].join("")};return this.getRemark(a,b)},applyAccess:function(a){a=new QZONE.FormSender("http://"+QZONE.FP._t.g_W_Domain+"/cgi-bin/tfriend/applyentryright.cgi","POST",{vUin:QZONE.FP._t.g_iLoginUin,hUin:a,fupdate:1,rd:Math.random()},"utf-8");a.onSuccess=function(a){"succ"==a.ret||0==a.code?QZONE.FP.showMsgbox('\u7533\u8bf7\u5df2\u53d1\u9001\uff0c\u8bf7\u6ce8\u610f\u67e5\u770b\u201c\u597d\u53cb\u6d88\u606f\u901a\u77e5"',
4,2E3):QZONE.FP.showMsgbox(a.msg||a.message,1,2E3)};a.onError=function(){QZONE.FP.showMsgbox("\u5f88\u62b1\u6b49\uff0c\u5f53\u524d\u4f7f\u7528\u7684\u4eba\u6570\u8fc7\u591a\uff0c\u8bf7\u4f11\u606f\u4e00\u4f1a\u513f\u518d\u6765",1,2E3)};a.send()}});
(function(){var a={};this.tmpl=function c(d,e){var f=/\W/.test(d)?new Function("obj","var p=[],print=function(){p.push.apply(p,arguments);};with(obj){p.push('"+d.replace(/[\r\t\n]/g," ").split("<%").join("\t").replace(/((^|%>)[^\t]*)'/g,"$1\r").replace(/\t=(.*?)%>/g,"',$1,'").split("\t").join("');").split("%>").join("p.push('").split("\r").join("\\'")+"');}return p.join('');"):a[d]=a[d]||c(document.getElementById(d).innerHTML);return e?f(e):f}})();
(function(){var a;a||(a=function(b,c,d){if("[object RegExp]"!==Object.prototype.toString.call(c))return a._nativeSplit.call(b,c,d);var e=[],f=0,h=(c.ignoreCase?"i":"")+(c.multiline?"m":"")+(c.sticky?"y":"");c=RegExp(c.source,h+"g");var g,k,l;b+="";a._compliantExecNpcg||(g=RegExp("^"+c.source+"$(?!\\s)",h));if(void 0===d||0>+d)d=Infinity;else if(d=Math.floor(+d),!d)return[];for(;k=c.exec(b);){h=k.index+k[0].length;if(h>f&&(e.push(b.slice(f,k.index)),!a._compliantExecNpcg&&1<k.length&&k[0].replace(g,
function(){for(var a=1;a<arguments.length-2;a++)void 0===arguments[a]&&(k[a]=void 0)}),1<k.length&&k.index<b.length&&Array.prototype.push.apply(e,k.slice(1)),l=k[0].length,f=h,e.length>=d))break;c.lastIndex===k.index&&c.lastIndex++}f===b.length?!l&&c.test("")||e.push(""):e.push(b.slice(f));return e.length>d?e.slice(0,d):e},a._compliantExecNpcg=void 0===/()??/.exec("")[1],a._nativeSplit=String.prototype.split);String.prototype.split=function(b,c){return a(this,b,c)}})();
var resizeImage=function(a,b,c){if(!0!=a.loaded){a.loaded=!0;var d=new Image;d.onload=function(){d.width>b?(a.width=b,a.style.width=b+"px"):(a.width=d.width,a.style.width=d.width+"px");a.style.height="auto";a.style.display="block"};console.log("resizeImage",this);d.src=a.src}},resizeImageHandler=function(){var a=this,b=this.getAttribute("data-src"),c=(this.getAttribute("data-limit")||"").split(",");if(2==c.length){var d=parseInt(c[0],10),e=parseInt(c[1],10),f=new Image;f.onload=function(){var b=this.width/
this.height,c=d/e;this.width>d&&this.height>e&&(b<=c?a.width=d:a.height=e);a.style.display="block";f.onload=null};f.src=b}};
(function(){window.controller={tab:MOOD.env.tab,uin:MOOD.env.uin,login_uin:""+QZONE.FP.getQzoneConfig("loginUin"),login_name:""+QZONE.FP.getQzoneConfig("loginUin"),updateLoginInfo:function(a){console.log("updateLoginInfo",a);a&&"object"==typeof a.logininfo&&(this.login_name=a.logininfo.name,this.login_uin=a.logininfo.uin)},getTitle:function(){return""},updateTitle:function(a){a&&a.usrinfo&&a.usrinfo.uin!=QZONE.FP.getQzoneConfig("loginUin")&&(a=escHTML(a.usrinfo.name)+"\u7684\u8bf4\u8bf4",$e(".mod_tab .friend_feed_head").setHtml(a).show())},
getDetailSuc:function(b){if(0>b.code)return{code:b.code,msg:b.message};var c={};c.source_name="\u670b\u53cb\u7f51"!=b.source_name&&"QQ\u7a7a\u95f4"!=b.source_name||isQzone?b.source_name:"";c.rt_source_name="\u670b\u53cb\u7f51"!=b.rt_source_name&&"QQ\u7a7a\u95f4"!=b.rt_source_name||isQzone?b.rt_source_name||"":"";c.auth_flag=b.auth_flag||0;c.right=b.right||1;c.commentlist=b.commentlist||[];c.replies=b.replies||b.msgTotal||c.commentlist.length;c.total=1;c.msglist=[b];a.updateTitle(b);return c},getProfileHtml:function(){var a=
window._preloadCache;return a&&a.usrinfo?(a.usrinfo.msgnum=a.usrinfo.msgnum||0,tmpl(MOOD.tmp.profile)(a.usrinfo)):""},getLastCommentHtml:function(){}};var a=controller})();var t=t||controller;controller.image_displayDetail=function(a){var b=a.comment.getTopic();QZONE.FP.openViewer({appid:311,from:"shuoshuo",ownerUin:b.getHostUin(),topicId:b.getId()+"_1",picKey:b.getId().split("_")[1]+","+a.id,pre:a.url,timeStamp:new Date})};
QZFL.object.extend(controller,{commentModuleConfig:{commentListConfig:{pageSize:5,showPaginationForm:!1,showAllLinkConfig:{innerTemplate:'\u67e5\u770b\u5168\u90e8<span id="${id}_totalNumLabel"></span>\u6761\u8bc4\u8bba',urlTemplate:function(a){var b="";a.getPlatform&&(b=a.getPlatform());return a?"qq.com"==document.domain?"http://user.qzone.qq.com/"+a.getByPath("poster.id")+"/mood/"+a.getId()+"."+b:"http://baseapp.pengyou.com/"+a.getByPath("poster.id")+"/mood/"+a.getId()+"."+b:""},onClick:function(a){a=
a.topic;if("detail"==t.tab)return a.setByPath("comments.pageNum",1),!1;location.href="index.html?uin="+a.getByPath("poster.id")+"&tid="+a.getId().split("_").pop()+"&need_cmt=1&source="+a.getByPath("platform")||0;return!1}},showRepliesByDefault:!0,itemConfig:{imageIconConfig:{},imageButtonConfig:{},userLinkConfig:{target:"_self",urlTemplate:function(a){if(a)switch(a.getPlatform()){case a.PLATFORM.PENGYOU:return"http://baseapp.pengyou.com/"+a.getId()+"/mood/";case a.PLATFORM.QZONE:return"http://user.qzone.qq.com/"+
a.getId()+"/mood/"}return"#"},onClick:function(a){a=a.user;mood.jumpPage(a.getId(),a.getPlatform());return!1}},topicLinkConfig:{template:function(a,b){return a&&b?['<a href="javascript:void(0);" onclick="MOOD.topic.search(unescape(\'',escape(b),'\'));return false;" class="c_tx">',escHTML(a),"</a>"].join(""):""}}}},commentBoxConfig:{contentMaxLength:500,emoticonSupported:!0,presentTargetUin:0,checkBoxConfig:[],needPrivateComment:1},appid:311},updateFeeds:function(a){QZFL.lang.isArray(a)?QZFL.each(a,
function(a){t.updateFeed(a)}):t.updateFeed(a)},updateFeed:function(a){var b="mood_"+a.tid;if(MOOD.DataStorage.get(a.tid))QZFL.console.print(b+" existed.");else{QZFL.console.print("updateFeed: "+b);a.created_time=(new Date).valueOf();a.source_name="\u670b\u53cb\u7f51"!=a.source_name&&"QQ\u7a7a\u95f4"!=a.source_name||isQzone?a.source_name:"";a.rt_source_name="\u670b\u53cb\u7f51"!=a.rt_source_name&&"QQ\u7a7a\u95f4"!=a.rt_source_name||isQzone?a.rt_source_name:"";var b=MOOD.DataStorage.set(a.tid,a),c=
document.createElement("div");c.innerHTML=b.getItemHTML();b=$e(c).find("li").elements[0];c=$("msgList");c.childNodes[0]?c.insertBefore(b,c.childNodes[0]):c.appendChild(b);t.initCommentModule(a);t.loadVisiableItems();try{var d=$e(".feed_num a").getHtml(),d=parseInt(d,10);d++;$e(".feed_num a").setHtml(d);$e(".empty_pic_message").hide()}catch(e){}}},renderLikeButton:function(a){$e(".mod_feed_lst#msgList li.feed").each(function(){var a=this.getAttribute("data-tid");(a=MOOD.DataStorage.get(a))&&t.likeButton(a)})},
likeButton:function(a){var b=$("like_btn_"+a.data.tid);b&&1!=b.getAttribute("data-handled")&&(function(a,b){var e=a.data,f="",h="";if(f=1==e.pictotal?!0:!1)var g=e.pic[0].unilikekey,k=e.pic[0].curlikekey;e.rt_tid&&e.rt_nosrc?(f=["http://user.qzone.qq.com/119/mood/",e.rt_tid,".",e.rt_source].join(""),h=["http://user.qzone.qq.com/",e.uin,"/mood/",e.tid,".",e.t1_source].join("")):e.rt_tid?(f=["http://user.qzone.qq.com/",e.rt_uin,"/mood/",e.rt_tid,".",e.rt_source].join(""),h=["http://user.qzone.qq.com/",
e.uin,"/mood/",e.tid,".",e.t1_source].join("")):f&&(g||k)?(f=g||k,h=k||g):h=f=["http://user.qzone.qq.com/",e.uin,"/mood/",e.tid,".",e.t1_source].join("");g={key:["http://user.qzone.qq.com/",e.owneruin||e.uin,"/mood/",e.tid].join(""),uniKey:f,curKey:h};g=a.getLikeKeys();QZONE.FP.addUGCLike(b,{uniKey:g.uniKey,curKey:g.curKey},{btnStyle:3,template:{keepInSameRow:!0,refreshTipBack:function(a,b){if(document){var c=document.getElementById("feed_like_"+e.tid);c&&(b?(c.innerHTML=b,c.style.display=""):c.style.display=
"none")}},TIP:['<span><i class="ui_ico icon_hand ui_ico_f qz_like_hand hand"></i><?if {ilike}>"0"?>\u6211<?/if?><?if {ilike}>"0"?><? cif{rCnt}>"0"?>\u548c<?/cif?><?/if?><?loop times="2" ?><a href="http://user.qzone.qq.com/{uin}" target="_blank" class="c_tx" title="{nick}">{shortNick}</a><?if {count}<{length}?>\u3001<?/if?>&nbsp;<?/loop?>{etc}<?if {rCnt}>"0"?><a href="javascript:void(0);" onclick="QZONE.FP.getLikeList(\'',f,'\');MOOD.sendEvent(\'clickLikePeopleNum\');return false;" class="c_tx">{peopleCount}</a><?/if?><?if {cnt}>"0"?>\u89c9\u5f97\u5f88\u8d5e<?/if?></span>'].join("")},
onLike:function(){try{MOOD.sendEvent("like"+location.pathname)}catch(a){}},onCancelLike:function(){try{MOOD.sendEvent("unlike"+location.pathname)}catch(a){}}})}(a,b),b.setAttribute("data-handled",1))},isAbleTo:function(a,b){var c=b.getByPath("poster.uin"),d=QZONE.FP.getQzoneConfig("loginUin"),e=b.getByPath("topic.poster.id");return"reportComment"==a?c!=d:"reportReply"==a?!1:"removeComment"==a||"removeReply"==a?e==d||c==d?!0:!1:"postReply"==a?!0:!1},isAbleTo4Share:function(a,b){return"reportComment"==
a||"reportReply"==a?!1:t.isAbleTo(a,b)},extendCommentSync:function(a){if(4<=a.ugc_right)return[];var b=[{checkBoxChecked:0,checkBoxLabel:"\u540c\u65f6\u8f6c\u53d1",checkBoxLocalKey:"with_fwd",showCheckBox:1}];(a.to_tweet||a.wbid)&&QZONE.FP.getUserBitmap(41)&&QZONE.FP.getLoginBitmap(41)&&b.push({checkBoxChecked:0,checkBoxLabel:"\u70b9\u8bc4\u5230\u5fae\u535a",checkBoxLocalKey:"to_tweet",showCheckBox:1});return b},adaptMoodCommentData:function(a){for(var b={},c=[],d,e=0;e<a.length;e++){b=a[e];d=[];
if(b.list_3)for(var f=0;f<b.list_3.length;f++){var h=b.list_3[f];d.push({id:h.tid,content:h.content,poster:{id:h.uin,name:h.name,platform:h.t3_source},postTime:h.create_time})}c.push({id:b.tid,content:b.content,poster:{id:b.uin,name:b.name,platform:b.t2_source},pic:b.pic,postTime:b.create_time,replies:d,source:"","private":b["private"],targetImage:b.targetImage})}return c},initCommentModule:function(a,b){MOOD.commentModule=MOOD.commentModule||{};var c=MOOD.commentModule[a.tid];c?b&&b(c):a.timershuoshuo||
(a.auth_flag=a.auth_flag||0,a.source_name=!a.source_name||"\u670b\u53cb\u7f51"!=a.source_name&&"QQ\u7a7a\u95f4"!=a.source_name||isQzone?a.source_name:"",a.rt_source_name=!a.rt_source_name||"\u670b\u53cb\u7f51"!=a.rt_source_name&&"QQ\u7a7a\u95f4"!=a.rt_source_name||isQzone?a.rt_source_name:"",a.commentTotal=a.replies,c=controller.commentModuleConfig.commentListConfig.itemConfig,"detail"==controller.tab?(c.imageIconConfig.onClick=null,c.imageButtonConfig.onClick=controller.image_displayDetail):(c.imageIconConfig.onClick=
controller.image_displayDetail,c.imageButtonConfig.onClick=null),"detail"==controller.tab?(controller.commentModuleConfig.commentListConfig.pageSize=20,controller.commentModuleConfig.commentListConfig.defaultPageNum=1):(controller.commentModuleConfig.commentListConfig.pageSize=5,controller.commentModuleConfig.commentListConfig.defaultPageNum=0),"share"==a.source_type?requirejSolution(function(c){c.load({ids:["/controls/commentModule:3.0:prototype","/controls/commentModule/viewModel:3.0_common:prototype",
"/requests/base:3.0:prototype"],onSuccess:function(c,d,h){MOOD.commentModule[a.tid]=c.create({config:controller.commentModuleConfig,dataContext:d.create({id:a.uin+"_"+a.tid,hostUin:QZONE.FP.getQzoneConfig("ownerUin"),poster:d.UserViewModel.create({id:a.uin,name:a.name}),cgiUrls:{postReply:"http://sns.qzone.qq.com/cgi-bin/qzshare/cgi_qzshareaddcomment?fupdate=2",postComment:"http://sns.qzone.qq.com/cgi-bin/qzshare/cgi_qzshareaddcomment?fupdate=2",removeComment:"http://sns.qzone.qq.com/cgi-bin/qzshare/cgi_qzsharedeletecomment?fupdate=2",
loadComments:"http://sns.qzone.qq.com/cgi-bin/qzshare/cgi_qzshareget_comment?fupdate=2"},strategy:{isAbleTo:t.isAbleTo4Share},request:h.create({get_onReceived:function(b){0!==b.code?(b.code=0,b.message="",b.data={comments:[]}):b.data.total&&($("comment_btn_"+a.tid).innerHTML="\u8bc4\u8bba("+b.data.total+")")}}),inCharset:"utf-8",outCharset:"utf-8"}),placeHolder:$("comment_list_"+a.tid)});b&&b(MOOD.commentModule[a.tid])}})}):requirejSolution(function(c){c.load({ids:["/controls/commentModule:3.0:prototype",
"/controls/commentModule/viewModel:3.0_common:prototype","/requests/moodRequest:3.1:prototype","/strategies/moodRequestStrategy:3.1:prototype"],onSuccess:function(c,d,h,g){g=2==(window._locationCache||{idcNo:1}).idcNo?"sh.":"";h={id:a.uin+"_"+a.tid,hostUin:QZONE.FP.getQzoneConfig("ownerUin"),poster:{id:a.uin,name:a.name,platform:a.t1_source},CommentViewModel:d.CommentViewModel.derive({className:"moodCommentViewModel",methods:{getReportData:function(){return{appname:"qzone",subapp:"shuoshuo_comment",
jubaotype:"article",t1_tid:(this.getByPath("topic.id")||"").replace(this.getByPath("topic.poster.id")+"_",""),t1_uin:this.getByPath("topic.poster.id"),t1_source:this.getByPath("topic.platform")||1,t2_tid:this.getByPath("id"),t2_uin:this.getByPath("poster.id")}}}}),cgiUrls:{entopComment:format("http://taotao.{domain}/cgi-bin/emotion_cgi_addtopcomment_v6",{domain:document.domain}),loadComments:format("http://taotao.{domain}/cgi-bin/emotion_cgi_getcmtreply_v6?need_private_comment=1",{domain:document.domain,
domainPrefix:"mine"==t.tab?g:""}),postComment:format("http://taotao.{domain}/cgi-bin/emotion_cgi_addcomment_ugc",{domain:document.domain}),removeComment:format("http://taotao.{domain}/cgi-bin/emotion_cgi_delcomment_ugc",{domain:document.domain}),postReply:format("http://taotao.{domain}/cgi-bin/emotion_cgi_addreply_ugc",{domain:document.domain}),removeReply:format("http://taotao.{domain}/cgi-bin/emotion_cgi_delreply_ugc",{domain:document.domain})},strategy:{isAbleTo:t.isAbleTo},request:h.create({get_onReceived:function(a){0!==
a.code&&(a.code=0,a.message="",a.data={comments:[]})}})};"detail"==t.tab&&1==a.certified&&1!=getParameter(location.href,"need_cmt")?h.CommentListViewModel=d.CommentListViewModel.derive({properties:{pageNum:{initialValue:0}},methods:{load:function(){this.getPageNum();if(this.getTopic())this.setSourceData({comments:[],total:a.total}),this.load=arguments.callee.base;else return arguments.callee.base.apply(this,arguments)}}}):h.CommentListViewModel="mine"==controller.tab||"detail"==controller.tab?d.CommentListViewModel.derive({properties:{pageNum:{initialValue:"detail"==
controller.tab?1:0},pageSize:{initialValue:"detail"==controller.tab?20:5},order:{initialValue:0}},methods:{load:function(){var b=this.getPageNum(),c=this.getTopic();if("detail"==controller.tab){if(c&&1===b&&a.commentlist&&a.commentlist.length){this.setSourceData({comments:controller.adaptMoodCommentData(a.commentlist),total:a.cmtnum});this.load=arguments.callee.base;return}}else if(c&&0===b&&a.commentlist&&a.commentlist.length){this.setSourceData({comments:controller.adaptMoodCommentData(a.commentlist),
total:a.cmtnum});this.load=arguments.callee.base;return}return arguments.callee.base.apply(this,arguments)}}}):d.CommentListViewModel.derive({properties:{pageNum:{initialValue:0},pageSize:{initialValue:5},coverPageSize:{initialValue:5},converOrder:{initialValue:1}}});g=controller.commentModuleConfig;g.commentBoxConfig.checkBoxConfig=t.extendCommentSync(a);MOOD.commentModule[a.tid]=c.create({config:g,dataContext:d.create(h),placeHolder:$("comment_list_"+a.tid)});b&&b(MOOD.commentModule[a.tid])}})}))},
actionResponse:function(a){switch(MOOD.env.action){case "comment":a&&(a.show(),a.focus())}},appScrollHandler:function(){console.log("appScrollHandler")},viewport_:function(a){a=a||window;var b=0;"number"==typeof a.pageYOffset?b=a.pageYOffset:a.document.body&&a.document.body.scrollTop?b=a.document.body.scrollTop:a.document.documentElement&&a.document.documentElement.scrollTop&&(b=a.document.documentElement.scrollTop);a=a.innerHeight||a.document.documentElement.clientHeight||a.document.body.clientHeight;
return{top:b,bottom:b+a,height:a}},getFrameNode:function(){return 5==parent.g_version?parent.QZFL.dom.get("frameContainer"):parent.QZFL.dom.get("LayPageContainer")||parent.QZFL.dom.get("pageApp")},isVisiable:function(a){var b=this.getFrameNode(),b=b?b.scrollTop:0,c=t.viewport_(parent);$e(a);a=QZFL.dom.getPosition(a);top_diff=a.top-c.bottom-b;bottom_diff=a.bottom-c.top-b;return 0>=top_diff&&0<=bottom_diff+0},loadIfVisiable:function(a,b){var c=a.getAttribute("data-img-load"),d=a.getAttribute("data-comment-load"),
e=t.isVisiable(a),f="rf=mood_app";"1"==QZONE.FP._t.QZFL.cookie.get("QZ_FE_WEBP_SUPPORT")&&(f+="&t=5");var h=a.getAttribute("data-tid");e&&"load"!=c&&(a.setAttribute("data-img-load","load"),$e(a).find("img").each(function(){if($e(this).hasClass("typeset-lazyload")){$e(this).removeClass("typeset-lazyload");var a=this.getAttribute("data-src"),b=this.getAttribute("data-midsrc"),c=this.getAttribute("data-bigsrc");-1<(a||b||c).indexOf("http://p.qpimg.cn/cgi-bin/cgi_imgproxy")&&(f="");a&&f&&(a+=(-1<a.indexOf("?")?
"&":"?")+f);b&&f&&(b+=(-1<b.indexOf("?")?"&":"?")+f);c&&f&&(c+=(-1<c.indexOf("?")?"&":"?")+f);var d=this.getAttribute("pic-width"),e=this.getAttribute("pic-height"),h=parseInt(this.getAttribute("pic-index"),10)+1;if(a){var q;QZFL.dom.searchChain(this,"parentNode",function(a){if(a&&$e(a).hasClass("img-item-"+h))return q=a,!0});var b=QZFL.dom.getSize(q),n=b[0],m=b[1],b=400==n||400==m,p=this,r=new Image;r.onload=function(){this.width<n||this.height<m?(this.width/this.height>n/m?p.height=m:p.width=n,
p.src=d>m&&e>m?c:this.src):(this.width/this.height>n/m?p.height=m:p.width=n,p.src=this.src)};r.src=b?c:a}}if($e(this).hasClass("lazyload")&&($e(this).removeClass("lazyload"),a=this.getAttribute("data-src"),b=this.getAttribute("data-isphoto"),-1<a.indexOf("http://p.qpimg.cn/cgi-bin/cgi_imgproxy")&&(f=""),a)){1==b&&f&&(a+=(-1<a.indexOf("?")?"&":"?")+f);b=(this.getAttribute("data-limit")||"").split(",");2!=b.length&&(b=[400,300]);var s=400==b[0];QZFL.media.reduceImage(s?0:1,b[0],b[1],{trueSrc:a,img:this,
callback:function(a,b,c,d,e){s||(b=parseInt(QZFL.dom.getStyle(a,"width"),10),d=-(parseInt(QZFL.dom.getStyle(a,"height"),10)-d)/2,c=-(b-c)/2,d&&QZFL.dom.setStyle(a,"margin-top",d+"px"),c&&0>c&&QZFL.dom.setStyle(a,"margin-left",c+"px"))}})}}));e&&"load"!=d&&((a.setAttribute("data-comment-load","load"),c=MOOD.DataStorage.get(h),c)?1<c.data.right||(qzlog.info({cm:"MOOD_APP",cf:"initCommentModule-"+b+" START"}),t.initCommentModule(c.data,"detail"==t.tab?function(){t.actionResponse();qzlog.info({cm:"MOOD_APP",
cf:"initCommentModule-"+b+" FINISHED"})}:function(){qzlog.info({cm:"MOOD_APP",cf:"initCommentModule-"+b+" FINISHED"})})):console.log("tid:"+h))},loadVisiableItems:function(){qzlog.info({cm:"MOOD_APP",cf:"loadVisiableItems START"});var a=this;a.loadVisiableItems._loadTimer||(a.loadVisiableItems._loadTimer=setTimeout(function(){var b=0;$e(".mod_feed_lst#msgList li.feed").each(function(a,d){t.loadIfVisiable(this,d);if(1!=a.getAttribute("data-like-handled")&&10>b){b++;var e=a.getAttribute("data-tid"),
e=MOOD.DataStorage.get(e);t.likeButton(e);a.setAttribute("data-like-handled",1)}});a.loadVisiableItems._loadTimer=null},100))},resetScrollHandler:function(){t._scroll_timer=null;t._min_scroll_time=200;t._last_scroll_time=0;t._last_scroll_top=0},_scroll_timer:null,_min_scroll_time:200,_last_scroll_time:0,_last_scroll_top:0,scrollHandler:function(){if(!t._scroll_timer){var a=(new Date).getTime(),b=t._min_scroll_time;a-t._last_scroll_time>t._min_scroll_time&&(b=0);t._scroll_timer=window.setTimeout(function(){t._last_scroll_time=
(new Date).getTime();t.loadVisiableItems();var a=QZONE.FP._t.QZFL.dom.getClientHeight(),b=QZONE.FP._t.QZFL.dom.getScrollTop(),e=QZONE.FP._t.QZFL.dom.getScrollHeight();"feedlist"==t.tab&&a+b>e-200&&b-10>t._last_scroll_top&&(t._last_scroll_top=b,t.mmc&&(t.mmc.fetch(),console.log("\u6eda\u52a8\u52a0\u8f7d\u54e6")),console.log(e,a+b,a,b));t._scroll_timer=null},b)}},fixNum:function(){seajs.use("app/v8/requests/mood_request/1.0",function(a){a.get({id:"shuoshuoinfo_v6",data:{uin:t.uin},onSuccess:function(a){a&&
0<=a.total&&$e(".feed_num a").setHtml(a.total)},onError:function(a){}})})},loadBanner:function(){t.MenuHandler();isOwner&&QZFL.imports("/qzone/v6/v6_config/moodbanner.js")},updateMenu:function(a){switch(a){case "detail":$e(".feed_wrap .feed_head").show();break;case "weibo":$e(".feed_wrap .feed_head").hide();$e(".nav_weibo").find("a").addClass("selected");break;case "feedlist":case "mine":case "schedule":$e(".feed_wrap .feed_head").show();$e(".nav_my").find("a").addClass("selected");break;case "index":$e(".feed_wrap .feed_head").hide();
$e(".nav_home").find("a").addClass("selected");break;case "hot":$e(".feed_wrap .feed_head").hide();$e(".nav_hot").find("a").addClass("selected");break;default:$e(".feed_wrap .feed_head").hide()}},MenuHandler:function(){QZONE.FP.getUserBitmap(41)&&QZONE.FP.getQzoneConfig("loginUin")||$e(".nav_weibo").addClass("none");$e(".shuoshuo_menu ul li a").onClick(function(a){var b=QZFL.event.getTarget(a);if("menu_wall"==b.getAttribute("id")||"menu_wall"==b.parentNode.getAttribute("id"))return!0;QZFL.event.preventDefault(a);
a=$e(this).getAttr("data-tab");$e(".shuoshuo_menu ul li a").removeClass("selected");$e(this).addClass("selected");t.tab=a;isQzone||"feedlist"!=t.tab||(t.tab="mine");"hot"==t.tab?t.getHotList(1,function(){t.load(t.tab)}):t.load(t.tab);t.updateMenu(t.tab);t.updateTitle();t.resetScrollHandler();return!1});t.updateMenu(t.tab)},userTracker:function(a){if("qq.com"==document.domain){var b={uin:"",mod:0,src:9,id:""};QZFL.object.extend(b,a);a=new QZFL.FormSender("http://g.qzone.qq.com/cgi-bin/friendshow/cgi_content_visitor",
"POST",b,"utf-8");a.onSuccess=function(a){};a.send()}}});t=t||controller;
QZFL.object.extend(controller,{load:function(a,b){window._preloadCache&&9999==window._preloadCache.code?window._preloadCache=null:window._preloadCache&&0==window._preloadCache.code&&(window._preloadCache.msglist=window._preloadCache.msglist||window._preloadCache.posts);t.updateTitle(window._preloadCache);t.updateCurrentTabStyle(a);MOOD.commentModule={};MOOD.load("*",function(b){t.mmc=new b.MoodModelCollection({uin:t.uin,type:a,hostUin:t.uin,initialData:window._preloadCache,success:function(b){if(!window._preloadCache){b.setConfig({mood:{comment:{max_comments_count:0}}});
var c=document.getElementById("msgList"),f=b.getPagination();if("feedlist"==t.tab&&1<f.page)QZFL.dom.insertAdjacent(c,2,b.getHTML());else{if(0>QZFL.object.route(b,"opts.initialData.code")){console.log("[ERROR] mood/index.js controller.load \u52a0\u8f7d\u6570\u636e\u5f02\u5e38\uff0c\u9519\u8bef\u7801:",QZFL.object.route(b,"opts.initialData.code"));c.innerHTML=QZFL.object.route(b,"opts.initialData.message")||QZFL.object.route(b,"opts.initialData.msg")||"";return}0<b.getSizeSync()?c.innerHTML=b.getHTML():
c.innerHTML=t.getEmptyPageTip()}}controller.onPageRendered(a,b)}});window._preloadCache?window._preloadCache=null:t.mmc.fetch()})},init:function(){qzlog.info({cm:"MOOD_APP",cf:"controller.init START"});t.reportPV();new MOOD.MsgList({container:"msgList"});$e(".profile").setHtml(t.getProfileHtml());window._preloadCache&&9999===window._preloadCache.code&&(document.getElementById("error_tip_cont").style.display="block");t.showReview();t.load(t.tab);MOOD.poster.init("poster");t.getLastCommentHtml();var a=
MOOD.util.getHttpParams("referer");a&&-1!=a.indexOf("hot_topic")&&($("hot_topic_bd").onclick=function(a){for(a=QZFL.event.getTarget(a);a&&a!=this;){if("topic_item"==a.className){MOOD.sendHotClick("/hottopic_click");break}a=a.parentNode}},t.showHotWords(),$("msgList").setAttribute("data-tab","hot_topic"));t.eventHandler();t.loadBanner();t.runStyleFailedMonitor();setTimeout(function(){QZFL.imports("http://"+(window.siDomain||"qzonestyle.gtimg.cn")+"/utp/dnsget.js")},5E3);switch(t.tab){case "hot":t.updateNickname();
t.updateCount();break;case "feedlist":t.updateTabUrl();break;case "mine":t.updateTabUrl();break;case "detail":t.updateTabUrl()}"detail"==t.tab&&QZFL.event.addEvent(window,"hashchange",function(){window.console&&console.log("hashchange");try{window.location.reload()}catch(a){}});qzlog.info({cm:"MOOD_APP",cf:"controller.init FINISHED"})},eventHandler:function(){QZFL.event.removeEvent(parent,"scroll",t.scrollHandler);QZFL.event.addEvent(parent,"scroll",t.scrollHandler);try{var a;a=5==parent.g_version?
parent.QZFL.dom.get("frameContainer"):parent.QZFL.dom.get("LayPageContainer");QZFL.event.removeEvent(a,"scroll",t.scrollHandler);QZFL.event.addEvent(a,"scroll",t.scrollHandler)}catch(b){}QZFL.event.addEvent(window,"unload",function(){window.console&&console.log("mood app unload fired!");try{QZFL.event.removeEvent(parent,"scroll",t.scrollHandler);var a=parent.QZFL.dom.get("LayPageContainer");QZFL.event.removeEvent(a,"scroll",t.scrollHandler)}catch(b){}})},_reportString:function(a,b,c){try{if(a){var d=
window.TCISD;!d&&window.QZONE&&window.QZONE.FP&&window.QZONE.FP.getStatPackage&&(d=QZONE.FP.getStatPackage());d&&d.stringStat&&d.stringStat("1000100",{bid:a,rc:b},{reportRate:c||100})}}catch(e){}},initFavoriteWidget:function(){window.seajs&&window.seajs.use(["app/favorite/script/favorite_for_app/1.0","jquery"],function(a,b){if(a&&b){var c=QZONE.FP.getQzoneConfig().loginUin;b("#msgList").find(".add_favorite_container").each(function(d,e){var f=b(e),h=f.parents("li:first"),g=h.attr("data-tid"),h=h.attr("data-uin");
(g=a.init({data:{id:g,owneruin:h,uin:c},container:f[0],who:"shuoshuo"}))&&f.hasClass("need_bg2")&&b(g.template).mouseenter(function(){f.addClass("bg2")}).mouseleave(function(){f.removeClass("bg2")})});qzlog.info({cm:"MOOD_APP",cf:"init favorite widget FINISHED"})}})},onPageRendered:function(a,b){0<b.getSizeSync()&&(document.getElementById("error_tip_cont").style.display="none");controller.initFavoriteWidget();var c=b.getPagination();qzlog.info({cm:"MOOD_APP",cf:"init pager widget START"});"feedlist"!=
a&&MOOD.widget.loadPager(function(){t.pager=new F4A.widget.Pager($("pager"),{pageSize:c.rowsPerPage,currentPage:c.page,totalNum:c.totalRecords,onTurn:function(a){"hot"==t.tab?t.getHotList(a,function(a){t.load(t.tab,a)}):(MOOD.commentModule={},t.mmc.fetch({page:a}))}});qzlog.info({cm:"MOOD_APP",cf:"init pager widget FINISHED"})});t.loadVisiableItems();"hot"==a&&t.updateCount();var d=frameElement&&QZFL.dom.getPosition(frameElement).top||0,e=t.viewport_(parent).top;"feedlist"!=a&&e>d&&QZONE.FP.setScrollTop(0);
t.reportPV()},runStyleFailedMonitor:function(){try{"block"===$e(".network_busy").getStyle("display")&&(window.console&&console.log("load css failed"),t.pingCDN(function(a){a.uin=MOOD.env.getLoginUin();window.console&&console.log("go css failed");t._reportString("101004",obj2str(a),100)}))}catch(a){}},pingCDN:function(a){var b={},c=new Date,d=new Image,e;d.onload=function(){this.onload=null;e=new Date-c};setTimeout(function(){e||(e=-1);b.timetocdn=e;try{b.ie=ua.ie,b.chrome=ua.chrome,b.firefox=ua.firefox}catch(c){}a&&
a(b)},3E3);d.src="http://qzonestyle.gtimg.cn/qzone/app/mood_v6/images/blank.gif?r="+Math.random()},showHotMood:function(){var a=$e(".feed_commend_note");a.removeClass("none");t.showHotMood._inited?$e(".feed_commend").hide():(a.onClick(function(){$e(".feed_commend").show();QZFL.imports("/qzone/app/mood_v6/plugin/popular_mood.js",function(){QZONE.FP._t.MoodUseHot=window.UseHot=new HotMood})}),a.onHover(function(){a.addClass("bg2")}),a.onMouseOut(function(){a.removeClass("bg2")}),t.showHotMood._inited=
!0)},hideHotMood:function(){$e(".feed_commend_note").addClass("none");$e(".feed_commend").hide()},showHotWords:function(){var a={uin:QZONE.FP.getQzoneConfig("loginUin"),param:4},a=new QZFL.JSONGetter("http://r.qzone.qq.com/cgi-bin/right_frame.cgi","_get"+Math.random(),a,"utf-8");a.onSuccess=function(a){0==a.code&&(MOOD.hot_topic=a.data.module_4.data,t.refreshHotWords())};a.onError=function(a){};a.send("_Callback")},refreshHotWords:function(){var a=MOOD.hot_topic||[];MOOD.lang.randomArray(a);for(var b=
"",c=0;c<a.length&&3>c;c++)b+=a[c].html;b&&(b=b.replace(/_blank/g,"_top"),$("hot_topic_bd").innerHTML=b,$e("#hot_topic").removeClass("none"))},showRecVideo:function(){var a={uin:QZONE.FP.getQzoneConfig("loginUin"),board_id:2049},a=new QZFL.JSONGetter("http://boss.qzone.qq.com/fcg-bin/fcg_get_strategy","_get"+Math.random(),a,"utf-8");a.onSuccess=function(a){0==a.code&&(a=JSON.parse(a.data["2049"].items[0].extdata),a=format('<div class="mod-sec-hd"><h3>{text}</h3></div><div class="mod-sec-bd"><div class="vedio-wrap"><img src="{picUrl}" data-link="{link}" /><a href="{link}" target="_top" class="btn-play-m {isVideo}" role="button"><i class="hide_clip">\u64ad\u653e</i></a></div></div>',
a),$("rec_vedio").innerHTML=a,$e("#rec_vedio").removeClass("none"))};a.onError=function(a){};a.send("_Callback")},dolike:function(a){var b=a&&a.getAttribute("key");b&&(sd=new QZFL.FormSender("http://"+top.g_W_Domain+"/cgi-bin/likes/internal_dolike_app","post",{opuin:top.g_iLoginUin,unikey:b,curkey:b,from:0},"gb2312"),sd.onSuccess=function(c){0==c.ret&&(c=format('<a href="{key}?referer=hot_topic" target="_top"><span class="act_text c_tx">\u770b\u8be6\u60c5</span></a>',{key:b}),$e(a).find(".topic_op").setHtml(c))},
sd.send())},getEmptyPageTip:function(){var a="";switch(t.tab){case "weibo":a='<img class="empty_pic_message" src="http://ctc.qzonestyle.gtimg.cn/qzone_v6/img/shuoshuo/empty_home_sync.png">';break;case "index":a='<img class="empty_pic_message" src="http://ctc.qzonestyle.gtimg.cn/qzone_v6/img/shuoshuo/empty_feed_post.png">';break;case "feedlist":case "mine":a=isOwner?'<img class="empty_pic_message" src="http://ctc.qzonestyle.gtimg.cn/qzone_v6/img/shuoshuo/empty_home_post.png">':'<img class="empty_pic_message" src="http://ctc.qzonestyle.gtimg.cn/qzone_v6/img/shuoshuo/empty_guest_post.png">';
break;case "schedule":a='<img class="empty_pic_message" src="http://ctc.qzonestyle.gtimg.cn/qzone_v6/img/shuoshuo/empty_timing_post.png">';break;case "detail":a="\u8be5\u6761\u8bf4\u8bf4\u5df2\u88ab\u5220\u9664"}return a},reportPV:function(){t.isIndex=!1;switch(t.tab){case "detail":MOOD.sendPV("detail");break;case "list":MOOD.sendPV("microblog");break;case "mine":isOwner?MOOD.sendPV("mytitle"):MOOD.sendPV("guesttitle");break;case "timer":MOOD.sendPV("timer");break;case "index":MOOD.sendPV("title");
break;default:MOOD.sendPV(t.tab)}},showReview:function(){var a=window._preloadCache,b=$("censor_count");b&&a&&(b.innerHTML="\u5f53\u524d\u5f85\u5ba1\u6838\u8bc4\u8bba ("+(a.censor_count||0)+")")},getLocalDb:function(a){if(QZONE.FP.noShareDb)try{return QZONE.FP.noShareDb.get(a)}catch(b){}return""},setLocalDb:function(a,b){if(QZONE.FP.noShareDb)try{return QZONE.FP.noShareDb.set(a,b),!0}catch(c){}return!1},getHotPageNum:function(){var a=t.getLocalDb("mood_hot_page_time");if(a){var b=function(a){return Math.floor((a-
18E5)/864E5)},c=QZONE.FP.getSvrTime(),a=b(parseInt(a)),b=b(c.getTime());if(a==b)return b=t.getLocalDb("mood_hot_page_num"),(b=parseInt(b))?b+1:1}return 1},getHotList:function(a,b){var c=t.getHotPageNum(),d=OOP.tpl.format("//{{siDomain}}/qzone_v6/act/hotTopic/top20_{{random}}.js",{siDomain:siDomain,random:c}),d=new QZFL.JSONGetter(d,null,{},"utf-8");d.onSuccess=function(d){var f=[];d=window._LocalCacheCallbackData=d;for(var h=0;h<d.data.length&&20>h;h++)f.push(window._fakeData(d.data[h]));MOOD.lang.randomArray(f);
window._LocalCacheData=window._LocalCacheData||{};window._LocalCacheData.msglist=f;window._LocalCacheData.total=d.totalCnt;window._preloadCache=window._LocalCacheData;b(a);f=QZONE.FP.getSvrTime();t.setLocalDb("mood_hot_page_num",c);t.setLocalDb("mood_hot_page_time",f.getTime())};d.send("_Callback")},updateNickname:function(){var a=[];$e(".mod_feed_lst#msgList li.feed").each(function(){var b=this.getAttribute("data-tid");(b=MOOD.DataStorage.get(b))&&a.push(b.data.uin)});QZFL.FP.getPortraitList(a,function(a){$e(".nickname").each(function(c){c=
$e(this);var d=c.getAttr("data-uin");try{"undefined"!=typeof a[d+""]&&c.setHtml(escHTML(restHTML(a[d][6])))}catch(e){}})})},updateCurrentTabStyle:function(a){a=a||t.tab;var b=".feed_tab";"feedlist"==a?b+=" .all_tab":"mine"==a?b+=" .mood_tab":"schedule"==a&&(b+=" .timer_tab");isOwner||(b+="_visitor");$e(".feed_tab a").removeClass("current");$e(b).addClass("current")},updateTabUrl:function(){var a=$e(".feed_tab .all_tab_visitor"),b=a.getAttr("href"),c=$e(".feed_tab .mood_tab_visitor"),d=c.getAttr("href"),
e=MOOD.util.getHttpParams("uin")||QZONE.FP.getQzoneConfig("ownerUin");QZONE.FP.getQzoneConfig("isOwner")?1E4<e&&e!=QZONE.FP.getQzoneConfig("ownerUin")&&(a.setAttr("href",b+"&uin="+e),c.setAttr("href",d+"&uin="+e)):(a.setAttr("href",b+"&uin="+e),c.setAttr("href",d+"&uin="+e))},updateCount:function(){var a,b=[],c={};$e(".mod_feed_lst#msgList li.feed").each(function(){var d=this.getAttribute("data-tid");(d=MOOD.DataStorage.get(d))&&!this.getAttribute("data-countloaded")&&(d=d.data,a=["http://user.qzone.qq.com/",
d.uin,"/mood/",d.tid,".",d.t1_source].join(""),b.push(a),c[["http://user.qzone.qq.com/",d.uin,"/mood/",d.tid].join("")]=format("{uin}_{tid}_{t1_source}",d),this.setAttribute("data-countloaded",1))});var d={fupdate:1,unikey:b.join("<|>"),rd:Math.random()},d=new QZFL.JSONGetter("http://rsh.qzone.qq.com/cgi-bin/user/qz_opcnt2_sh",null,d,"utf-8");d.onSuccess=function(a){if(0==a.code){a.data=a.data||[];for(var b,d=0;d<a.data.length;d++){var g=a.data[d];b=g.current.newdata;if(c[g.current.key]){var k="comment_btn_"+
c[g.current.key],g="forward_btn_"+c[g.current.key];0<b.CS&&$(k)&&($(k).innerHTML=format("\u8bc4\u8bba({CS})",b));0<b.ZS&&$(g)&&($(g).innerHTML=format("\u8f6c\u53d1({ZS})",b))}}}};d.onError=function(){};d.send("_Callback")}});MOOD.updateFeeds=t.updateFeeds;
QZFL.event.onDomReady(function(){timeStampsPool[7]=new Date;top==window&&$e(document.body).setStyle("width","900px").setStyle("margin","0 auto");gTimeStampsPool[2]=new Date;MOOD.domain.load();MOOD.pageStart(controller.init);gTimeStampsPool[3]=new Date;timeStampsPool[8]=new Date;setTimeout(function(){if(3>Math.floor(10*Math.random())){var a=QZONE.FP.getStatPackage().createTimeStat("moodPageTime6",[175,367,6]);a.zero=gTimeStampsPool[0];a.timeStamps=gTimeStampsPool;a.report()}if(a={mine:[175,367,23],
detail:[175,367,24]}[MOOD.env.tab])a=QZONE.FP.getStatPackage().createTimeStat("moodPageTime_"+MOOD.env.tab,a),a.zero=timeStampsPool[0],a.timeStamps=timeStampsPool,a.report();QZFL.userAgent.ie&&9<=QZFL.userAgent.ie&&(window._timing_config={f1:175,f2:367,f3:9},QZFL.imports("/qzone/app/timing/timing.js",function(){}))},0);if("pengyou.com"==document.domain){var a=$e("body");a&&a.addClass("mod_py")}$e(".mod_tab_nav").removeClass("none");MOOD.TCISDClick.batchBind({"#msgList[data-tab=hot_topic] .ft .op .qz_like_btn":"hot_topic.likeButton",
"#msgList[data-tab=hot_topic] .ft .op .comment_btn":"hot_topic.commentButton","#msgList[data-tab=hot_topic] .ft .op .forward_btn":"hot_topic.forwardButton",".mod_tab_op a":"old_mood_entry"})});qzlog.info({cm:"MOOD_APP",cf:"LOAD_JS_FINISHED"});gTimeStampsPool[1]=new Date;timeStampsPool[6]=new Date;
/*  |xGv00|85217cad223236fcb0c15d15c46039b9 */